Stripping debug info before generating LLVM target
iree-org/iree pull request #10070
Opened 2022-08-11 08:13 UTC by vmurali

For https://github.com/iree-org/iree/issues/9726

2022-08-11 14:58 UTC, benvanik requested changes
Thanks for looking into this! I think we need to do it later in the process, though - having the debug information in LLVM during compilation is useful and things like stripping should generally be done at the very end of the process as part of final binary construction such that it's preserved as long as possible. When looking at LLVM compilation errors, objdump'ing the static objects, etc it's useful to have an association back to the original MLIR locations even if targeting release builds, and we don't want users to have to enable output debug symbols to see compilation errors. To follow normal compilation flows this would mean passing `--strip-debug` to the linker command we use based on this setting. This allows for people targeting static libraries (where they themselves perform the linking) to consistently control this setting as part of their deployment process, and let's us building the shared libraries control our own deployment process.

2022-08-11 16:30 UTC, vmurali commented
The original issue https://github.com/iree-org/iree/issues/9726#issue-1296754705 by @dcaballe says the debug info has to be stripped before generating LLVM code. The current flag `-iree-llvm-debug-symbols=false` already removes debug info from LLVM, right? So why is anything else needed if we want to let debug info go from MLIR to LLVM?

2022-08-11 16:42 UTC, benvanik commented
I'm not sure - `llvm-strip --strip-debug` can strip debug info from bitcode if a reproducer is needed or `strip --strip-debug` can be used for object files. An LLVM engineer wanting to build a reproducer can run that if they want, whereas today this is a user-level flag for deployment purposes and a user wouldn't expect error messages from the compiler to change based on it. I responded on that issue and I don't know why my past self didn't say that - past me was not paying attention :P

In general we try to take a [unix tools philosophy](https://en.wikipedia.org/wiki/Unix_philosophy)-style approach - someone needing to look up a bespoke flag is less good than having to look up a commonly available tool, and if we have to document either anyway then documenting the one we can point at a million stack overflow posts for is always better :)

There is no `mlir-strip` today but IMO there should be - then if you have a .mlir file with locs you can easily pipe it through `mlir-strip --strip-debug` and get the un-loc'ed file. It'd basically be parse, do exactly what you're doing here, and then print. When there's the binary format it could work with that too (today you can regex, but once binary that won't be possible). This would be a good upstream addition to complete the toolset!

2022-08-11 17:59 UTC, vmurali commented
That sounds like a useful tool indeed. And it should exist in MLIR (not IREE), right?

On a somewhat related note, it looks like, unlike for LLVM, there's no serialized binary format for MLIR (https://discourse.llvm.org/t/rfc-a-binary-serialization-format-for-mlir/63518). I suppose all passes generate textual .mlir files that can be stripped?

2022-08-11 18:03 UTC, benvanik commented
Yep! You could ask on discord/discourse and see if anyone wants to take it on but otherwise it should be fairly simple to get started and landed - a first version with just --strip-debug would be fine.

Correct, not yet - so today it's just text->text.

2022-08-11 22:38 UTC, dcaballe commented
Hey Ben, thanks for the feedback! This was expected to be a small starter task for Murali. The `mlir-strip` sounds really interesting but I think it's out of our scope right now. Debug information can be removed in different ways, as you well pointed out, but the key point here was *doing so within IREE's pipeline* so that we can examine the IR of MLIR and LLVM passes *in the specific order and with the specific setup used by our pipeline*, extract/modify the IR from them, etc. without having to worry about the debug information. That would be really helpful for debugging the IR.

I agree that we shouldn't couple this with `-iree-llvm-debug-symbols=false`. Perhaps, we could introduce another flag for this and invoke `StripDebugInfo`. This flag wouldn't be intended to generate a debug binary but to debug the IR itself. Would this make sense to you? It looks like a common development flag to me.

Thanks!

2022-08-12 00:15 UTC, benvanik commented
Gotcha, thanks for explaining as the intended workflow was not clear to me!

Sounds like you think this is a good workflow for MLIR codegen targeting LLVM: it's really useful to bias such things toward going upstream when there's not anything IREE-specific (as in this case) and I'm sure it'd be appreciated there as then anyone targeting LLVM from MLIR can benefit even if not coming through our tools. Learning how to contribute code upstream is an excellent starter task :)

There are other ways to do the stripping in-process that don't destructively mutate the module and that fit well upstream. What you are really asking for is more control over the MLIR -> LLVM translation: starting from there things get clearer as for example adding an upstream flag (`-mlir-strip-llvm-debuginfo`, etc)/constructor arg that disables https://github.com/llvm/llvm-project/blob/main/mlir/lib/Target/LLVMIR/ModuleTranslation.cpp#L394-L395 such that the debug info is not transferred from MLIR->LLVM leaves the original module intact while not producing debug info in the translated LLVM IR. And it'd be upstream where others can use it and all of our backends get it for free (including out-of-tree e.g. NOD ones) if they're calling `mlir::translateModuleToLLVMIR` (3 in our codebase so far and half a dozen upstream including from tools like `mlir-translate`). An IREE CPU-backend-specific flag doesn't help CUDA/ROCM/etc and it'd be nice not to end up with 16 copies of the flag pasted around our codebase as more backends are added.

If there's really no other way to accomplish what you want then adding a flag in the IREE compiler is possible but we need to try to delay the death from a thousand papercuts where possible (such as in this case). Every backend-specific flag we add is a burden and it's worse when it only ends up backend-specific because of the person working on it: it guarantees we'll end up with confusing duplication. We have some of that tech debt already but that's rarely a good reason to add more :)

RE mlir-strip: it sounds like you want the above translation stuff instead but I'll file an issue as it's an extremely simple starter project and would be very useful for both us and our users.

2024-05-14 16:12 UTC, benvanik commented
Closing stale PR.

2024-05-14 16:12 UTC, closed without merging