[spirv] Add verifier for lowering configurations
iree-org/iree pull request #10667
Opened 2022-10-05 23:24 UTC by yzhang93

The verification logic is following the constraints in #10500.

2022-10-07 18:55 UTC, antiagainst requested changes
Awesome, thanks for adding these! I Generally looks good; just some nits.

2022-10-07 18:55 UTC, antiagainst commented on compiler/src/iree/compiler/Codegen/SPIRV/SPIRVLowerExecutableTargetPass.cpp
> +    return moduleOp.emitError("expected workgroup size as three for SPIRV pipelines");
... workgroup size to have three dimensions for SPIR-V ...

2022-10-07 18:55 UTC, antiagainst commented on compiler/src/iree/compiler/Codegen/SPIRV/Verifiers.cpp
> +  if ((workgroupSize[0] != 1 && workgroupSize[0] % 2 != 0) ||
We can use `llvm::isPowerOf2_64` directly.

2022-10-07 18:55 UTC, antiagainst commented on compiler/src/iree/compiler/Codegen/SPIRV/Verifiers.cpp
> +    return op->emitOpError("expected workgroup size to be power of two");
expected each workgroup size dimension to be ...

2022-10-07 18:55 UTC, antiagainst commented on compiler/src/iree/compiler/Codegen/SPIRV/Verifiers.cpp
> +    return op->emitOpError("expected each dim of workgroup size not exceed ")
expected workgroup size dimensions not exceeding ...

2022-10-07 18:55 UTC, antiagainst commented on compiler/src/iree/compiler/Codegen/SPIRV/Verifiers.cpp
> +    return op->emitOpError("expected total workgroup size to be <= ")
expected total invocation count in workgroup to be ...

2022-10-07 18:55 UTC, antiagainst commented on compiler/src/iree/compiler/Codegen/SPIRV/Verifiers.cpp
> +                 "lhsShape doesn't factor into first level tile size");
LHS shape is indivisible by first level tile size

2022-10-07 18:55 UTC, antiagainst commented on compiler/src/iree/compiler/Codegen/SPIRV/Verifiers.cpp
> +                 "rhsShape doesn't factor into first level tile size");
same here

2022-10-07 18:55 UTC, antiagainst commented on compiler/src/iree/compiler/Codegen/SPIRV/Verifiers.cpp
> +
Use an early `return success()` here?

2022-10-07 23:09 UTC, yzhang93 commented
Thanks for your review and comments! I've modified codes accordingly.

2022-10-08 00:22 UTC, antiagainst approved these changes
Awesome. Just two final nits. :)

2022-10-08 05:28 UTC, yzhang93 commented
I just realized many tests in https://github.com/iree-org/iree/tree/main/compiler/src/iree/compiler/Codegen/SPIRV/test and tests/e2e/models/check_vulkan-spirv_vulkan_mobilenetv3_fake_weights.mlir_module.vmfb were failed because of the verifier constraints. Many of them were failed because of "error: expected total workgroup size to be multiple of xx". Shall I modify the configs in these files? Or shall we relax some constraints? For example, if our input matmul dimensions are odd numbers, with the current constraints, it's hard to make the workgroup size multiple of 16/32/64.

2022-10-11 02:19 UTC, antiagainst commented
Looking into this I think it's hard to verify `SPIRVVectorize` directly, which is used by many things. So I sent out two patches #10735 & #10736 to clean up pass pipelines. After that we will have separate identifiable pipelines for matmul and convolution. After landing them this patch should be adjusted to verify `SPIRVMatmulPromoteVectorize` for matmul and `SPIRVConvDirectVectorize` for convolution respectively.

(BTW I also pushed a commit 1890f1b to this pull request to address a few issues when I was touching it. Please make sure you `git pull` to get them.)

2022-10-11 17:39 UTC, MaheshRavishankar approved these changes

2022-11-10 17:19 UTC, yzhang93 commented
@antiagainst I've modified the codes accordingly. Could you please review this again when possible?

2022-11-10 19:22 UTC, antiagainst approved these changes
LGTM! Could you fix the formatting?

2022-11-10 21:26 UTC, yzhang93 commented
> LGTM! Could you fix the formatting?

Oh, what is the correct format? I already did git clang-format HEAD~1 and force pushed to my branch.

2022-11-10 22:21 UTC, antiagainst commented
Lint tests is still failing here: https://github.com/iree-org/iree/actions/runs/3434414360/jobs/5736372447. Nvm, I'll fix that and land it. :)

2022-11-10 22:35 UTC, yzhang93 commented
> Lint tests is still failing here: https://github.com/iree-org/iree/actions/runs/3434414360/jobs/5736372447. Nvm, I'll fix that and land it. :)

Awesome! Thank you!

2022-11-10 23:05 UTC, merged