[spirv] Add initial I64 emulation pass
iree-org/iree pull request #10682
Opened 2022-10-06 21:26 UTC by kuhar

The pass is conditionally enabled when the SPIR-V target does not declare I64 capabilities. The `demote-i64-to-i32' needs to be disabled for Wide Integer Emulation (WIE) to have any i64 ops to emulate. These default will be changed once the WIE implementation is robust enough.

Locally, I tested this by changing the `demote-i64-to-i32` default to false and all tests passed.

This PR relies on an llvm-project branch with some cherry-picked changes.

2022-10-07 16:27 UTC, antiagainst requested changes
Thanks! We'd need to have lit tests for the patterns. Another thing is that cherry-picking upstream commits should happen in its own pull request (so it's easier for integration folks to know and easier to revert if there are issues)

2022-10-07 16:27 UTC, antiagainst commented on compiler/src/iree/compiler/Codegen/SPIRV/SPIRVEmulateI64.cpp
> +  return llvm::is_contained(targetEnv.getCapabilities(),
We should create a `spirv::TargetEnv` out of the `spirv::TargetEnvAttr` to use the `allows` API there. The difference is, `spirv::TargetEnvAttr` only gives us the exact same set of capabilities specified by the environment, but certain capabilities are _implied_ (e.g., `Matrix` is always implied with `Shader`). `spirv::TargetEnv` handles the implication relationship under the hood.

2022-10-07 16:27 UTC, antiagainst commented on compiler/src/iree/compiler/Codegen/SPIRV/SPIRVEmulateI64.cpp
> +struct ConvertHalInterfaceBindingSubspan final
We need to add IR lit tests for the new patterns added here. It allows to guard against breakages and identify issues quicker. (End-to-end correctness runtime tests would involve more steps than working on IR lit tests.)

2022-10-08 00:26 UTC, antiagainst commented
>  Another thing is that cherry-picking upstream commits should happen in its own pull request (so it's easier for integration folks to know and easier to revert if there are issues)

Not hard requirement though. And there are cases we need to fix iree to make it compile/pass. So use your judgement. :)

2022-10-11 20:08 UTC, kuhar commented
Thanks for the feedback, @antiagainst! Addressed comments and added new LIT test. PTAL.

> > Another thing is that cherry-picking upstream commits should happen in its own pull request (so it's easier for integration folks to know and easier to revert if there are issues)
> 
> Not hard requirement though. And there are cases we need to fix iree to make it compile/pass. So use your judgement. :)

I was hoping these cherry-picked commits will propagate to the submodule by the time this PR is ready to land. If the next integrate does not pick them, I'll follow your suggestion.

2022-10-13 03:47 UTC, kuhar commented
Ping

2022-10-14 00:50 UTC, antiagainst approved these changes

2022-10-14 00:50 UTC, antiagainst commented on compiler/src/iree/compiler/Codegen/SPIRV/SPIRVEmulateI64.cpp
> +// This file implements a pass to emualte 64-bit integer operations with 32-bit
typo: emualte

2022-10-14 00:50 UTC, antiagainst commented on tests/e2e/vulkan_specific/BUILD
> +        "vulkan_uses_vk_khr_shader_int64",
Just `vulkan_uses_shader_int64`? This is not behind an `VK_KHR` extension.

2022-10-17 15:23 UTC, merged