Rename iree-llvmcpu-lower-executable-target -> iree-llvmcpu-lower-exe…
iree-org/iree pull request #11150
Opened 2022-11-13 19:53 UTC by nicolasvasilache

…cutable-target-pass to be consistent across CPU and GPU

2022-11-14 17:28 UTC, MaheshRavishankar requested changes, later dismissed
I would rather drop the `-pass` from GPU side. Seems like a redundant suffix.

2022-11-14 19:50 UTC, dcaballe commented
> I would rather drop the -pass from GPU side. Seems like a redundant suffix.
+1

2022-11-16 22:02 UTC, MaheshRavishankar approved these changes

2022-11-16 22:28 UTC, hanhanW approved these changes

2022-11-16 22:31 UTC, merged