Fix implementations of allocators' query_compatibility
iree-org/iree pull request #11463
Opened 2022-12-07 22:03 UTC by sogartar

Buffers should have compatibility IREE_HAL_BUFFER_COMPATIBILITY_QUEUE_TRANSFER if their usage is either
IREE_HAL_BUFFER_USAGE_TRANSFER_SOURCE or
IREE_HAL_BUFFER_USAGE_TRANSFER_TARGET.

Buffers should have compatibility IREE_HAL_BUFFER_COMPATIBILITY_QUEUE_DISPATCH if their usage is either
IREE_HAL_BUFFER_USAGE_DISPATCH_STORAGE_READ or
IREE_HAL_BUFFER_USAGE_DISPATCH_STORAGE_WRITE.

2022-12-09 17:30 UTC, ScottTodd commented
Thanks. This looks correct to me, but I'd like @benvanik to confirm.

2022-12-09 18:16 UTC, benvanik requested changes

2022-12-09 18:16 UTC, benvanik commented on runtime/src/iree/hal/allocator_heap.c
> -    if (iree_all_bits_set(params->usage, IREE_HAL_BUFFER_USAGE_TRANSFER)) {
ah this should be `if (iree_any_bits_set(params->usage, IREE_HAL_BUFFER_USAGE_TRANSFER)) {`
(and same for the others) - then no need for the expanded comparisons and in the future if we add more transfer/storage/etc types we don't need to update all these locations.

2022-12-16 16:47 UTC, benvanik approved these changes

2022-12-19 17:33 UTC, benvanik commented
I couldn't modify the branch since it originates in another repo - fix will land here: https://github.com/iree-org/iree/pull/11599

2022-12-19 17:33 UTC, closed without merging