Flip iree-opt-const-expr-hoisting and iree-opt-const-eval on by default.
iree-org/iree pull request #11524
Opened 2022-12-12 20:52 UTC by stellaraccident

2022-12-12 20:53 UTC, stellaraccident commented
Need to get a peek at the new benchmark size metrics...

2022-12-19 18:07 UTC, benvanik approved these changes

2023-04-03 19:56 UTC, ScottTodd requested changes
I rebased this (https://github.com/openxla/iree/pull/12900) and there are some errors to fix (bit rot in the flags?) before we can land it.

2023-08-17 16:08 UTC, ScottTodd commented
This looks stale, given recent changes to const eval etc.
Going to close this PR and delete the branch.

2023-08-17 16:08 UTC, closed without merging