Report outstanding `scope->permanent_status` at destruction time
iree-org/iree pull request #11861
Opened 2023-01-17 16:22 UTC by bjacob

The code was silentely eating outstanding statuses with this comment:

```c
// In most cases the status will have been consumed by the scope owner.
```

But as I'm debugging why ukernel statuses aren't reported in e2e matmul tests, after having fixed Issue #11843, I still don't see error statuses. Debugging, I found that I was landing exactly in this case (actually this had been hinted by @benvanik [on Discord the last time I had brought up the topic](https://discord.com/channels/689900678990135345/689900680009482386/1014203985911087104).

I have not succeeded finding the more proper place, closer to the root cause, where to catch and report the `scope->permanent_status`. In `iree_vm_invoke`, the main thread goes through the `vmvx` module call for the ukernel, then it goes into a `hal` module call to `fence.await` where it waits for worker threads to finish work. Somewhere around this might be the place to see if the scope has an error status?

Anyway, the present PR might be good to have anyway: it seems generally worth echoing un-consumed error statuses to `stderr`?

2023-01-17 16:33 UTC, benvanik requested changes
We can't print like this inside of core code - we're a library and designed to run without any stdio facilities.

You can use a trace message (`IREE_TRACE_MESSAGE_DYNAMIC`) or something similar but no printing.

It'd be better to actually propagate the error. We should be calling `iree_task_scope_consume_status` to get the failing status back but I'd have to dig in to figure out the best place to plumb it. You can file an issue (there may already be one?) and I can take a look.

2023-01-17 16:58 UTC, bjacob commented
Filed #11862.

> You can use a trace message (IREE_TRACE_MESSAGE_DYNAMIC) or something similar but no printing.

That wouldn't really help normal users who haven't scratched their heads for long enough to be at the point where they have trace messages enabled :-)

> It'd be better to actually propagate the error.

+1

2023-01-17 16:58 UTC, closed without merging

2023-01-17 17:00 UTC, benvanik commented
Agreed, but we really should not be ever producing code from the compiler that can fail - that you're using error messages here is only for your eyes, not users :)

2023-01-17 17:43 UTC, bjacob commented
> Agreed, but we really should not be ever producing code from the compiler that can fail

And indeed, ukernel errors are essentially like assertions: we only enable in asserts-enabled builds, and they can only occur as a result of an internal bug (possibly straddling the compiler/runtime divide).

I was trying to let ukernels still return statuses and have that propagated to the e2e tests. But maybe I should stop trying to do that and instead just make ukernel error literally assertions, i.e. abort?

Oh - now i remember - that was actually my first intuition but since ukernels can't call the standard library I thought it was not so trivial to have them abort (and I don't want to resort to UB in a make-believe local implementation of abort). WDYT @benvanik  ?

2023-01-17 17:45 UTC, bjacob commented
One way is to have the ukernel caller, i.e. the vmvx module entry point function (eg `iree_vmvx_mmt4d`) abort on error ?

2023-01-18 15:52 UTC, bjacob commented
Thought a bit more - it wasn't actually correct when I said above that these errors are like assertions so we could just abort. There are various error cases that are not so clearly attributable to a programming error and shouldn't crash users on.

2023-01-18 16:25 UTC, bjacob commented
OK, i guess you're right. I was thinking maybe `iree_uk_status_unsupported_huge_or_negative_dimension` but... the user would have to have a dimension >= 2^31 to get that.

OK, so, assertion it is? In the vmvx/module entry points?

2023-01-18 16:26 UTC, bjacob commented
Note: one way to get ukernel errors would be to run a new vmvx bytecode module against an old IREE runtime. Do we need ukernel versioning? And what do we do on version mismatch?