Add pattern to fold tensor.empty used by extract in transform dialect
iree-org/iree pull request #11961
Opened 2023-01-25 21:07 UTC by ThomasRaoux

This allows generating smaller allocations for reduction code generation. Without that we may generate allocation based on the original size rather than the tiled size.

2023-01-25 21:08 UTC, MaheshRavishankar requested changes
I think this already exists upstream.

2023-01-25 21:09 UTC, ThomasRaoux commented
> I think this already exists upstream.

ah ok, I looked for it and couldn't find it. Do you have a pointer?

2023-01-25 21:17 UTC, ThomasRaoux commented
> > I think this already exists upstream.
> 
> ah ok, I looked for it and couldn't find it. Do you have a pointer?

never mind, I found it. Replaced.

2023-01-25 23:07 UTC, MaheshRavishankar approved these changes
I am stamping, but probably better to wait for Nicolas.

2023-01-26 07:51 UTC, nicolasvasilache commented
I asked in offline chat if we really want a blanket application vs more targeted control as it can have non trivial effects on bufferization in general and could be a footgun. @matthias-springer  is the most up-to-date on patterns interference with bufferization and what foldings have "fusion-like" effects.

2023-01-26 11:16 UTC, matthias-springer commented on compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.h
> +  bool FoldTensorEmpty = false;
spelling: lower case

2023-01-26 14:20 UTC, nicolasvasilache approved these changes

2023-01-26 15:02 UTC, merged