Remove assert for number of results in FuseElementwiseOpsWithMultipleUses
iree-org/iree pull request #11983
Opened 2023-01-27 15:49 UTC by sogartar

mlir::linalg::fuseElementwiseOps has logic to drop results that are not used outside of the consumer.
This causes a discrepancy between the number of results in the fused op and the number of results of the producer + consumer.

2023-01-27 15:54 UTC, MaheshRavishankar commented
Thanks. I actually hit this myself. But there is a fix I have that requires upstream changes. Would it be possible to wait for that.

2023-01-27 16:27 UTC, sogartar commented
What kind of fix is this. Is it related to the below error?
```
iree-compile: repo/compiler/src/iree/compiler/Dialect/Flow/Transforms/RegionOpUtils.cpp:251: FailureOr<Flow::DispatchRegionOp> mlir::iree_compiler::IREE::Flow::movePrecedingOpIntoDispatchRegion(mlir::RewriterBase &, mlir::Operation *, Flow::DispatchRegionOp): Assertion `domInfo.properlyDominates(regionOp, use.getOwner()) && "found use that does not post-dominate target"' failed.
```

This is what I hit after removing the assert.

2023-01-27 17:28 UTC, MaheshRavishankar commented
> What kind of fix is this? Is it related to the below error?
> 
> ```
> iree-compile: repo/compiler/src/iree/compiler/Dialect/Flow/Transforms/RegionOpUtils.cpp:251: FailureOr<Flow::DispatchRegionOp> mlir::iree_compiler::IREE::Flow::movePrecedingOpIntoDispatchRegion(mlir::RewriterBase &, mlir::Operation *, Flow::DispatchRegionOp): Assertion `domInfo.properlyDominates(regionOp, use.getOwner()) && "found use that does not post-dominate target"' failed.
> ```
> 
> This is what I hit after removing the assert.

It is part of this PR for now https://github.com/iree-org/iree/pull/11980 . I need to separate it out and send it.
Could you share a repro for this error. I can take a look at it too.

2023-01-27 17:36 UTC, sogartar commented
> Could you share a repro for this error. I can take a look at it too.

You can use the instructions in this PR https://github.com/iree-org/iree/issues/11978.

2023-09-05 20:40 UTC, sogartar commented
@MaheshRavishankar, do you know if this PR make sense anymore?

2023-09-06 20:01 UTC, MaheshRavishankar requested changes
This assertion need not hold anymore. Upstream drops some producer results in the final operation when the producer result value has no other uses.

2023-09-11 13:18 UTC, sogartar commented
The assert was removed in another commit so I am closing this.

2023-09-11 13:18 UTC, closed without merging