Adapt Tile+Fuse to handle multi-result dispatches.
iree-org/iree pull request #12020
Opened 2023-02-01 07:00 UTC by MaheshRavishankar

The tile and fuse transformation upstream has been split into its individual steps allowing caller more control in terms of which producers to fuse and which values to yield from within the tiled loop nest. This moves IREEs tile+fuse to use these components, allowing for handling of multi-result dispatches.

Currently multi-result dispatches do seem to cause bufferization issues. IREE currently doesnt form such dispatches by default, but will do so with PR #11980. The bufferization issue is tracked in

Also fixes #11505.

2023-02-01 09:10 UTC, hanhanW requested changes
nice work!

2023-02-01 09:10 UTC, hanhanW commented on llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Transforms/Transforms.cpp
> +  // 1. Tile the consumer.
ditto: are we able to refactor logics out from TestTileConsumerFuseAndYieldProducerUsingSCFForOp and reuse it here?

2023-02-01 17:34 UTC, MaheshRavishankar commented on llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Transforms/Transforms.cpp
> +}
Thats a bit hard. The constraints are a bit involved to spell out, by IREE satisfies those by construction. Basically you need to be doing tile+fuse without redundancy in the producer tiles computed within the consumer tile loop. We have that requirement anyway. This is why the test is basically capturing and testing in MLIR this requirement, and we use that directly here in IREE. I think over time we will get a better idea of how to write those constraints upstream, in which case we can then move to use the upstream methods.

2023-02-01 19:31 UTC, dcaballe approved these changes
Really excited to see this!

2023-02-02 02:43 UTC, hanhanW approved these changes

2023-02-02 02:44 UTC, hanhanW commented on llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Transforms/Transforms.cpp
> +}
thanks for the details, SGTM!

2023-02-02 02:48 UTC, merged