Remove dead subspan ops after FlattenMemRefSubspanPass
iree-org/iree pull request #12109
Opened 2023-02-08 23:08 UTC by antiagainst

Subspan ops are not automatically removed by canonicalization given they are not marked as no side effect. Leaving dead subspan ops there after transformations can be confusing.

2023-02-08 23:43 UTC, MaheshRavishankar commented
AFK, but I think there is another pass that does this. I think it is called CleanupBuffer*. I'll post link when I am back online.

2023-02-08 23:46 UTC, benvanik commented
It'd be nice to remove them once they aren't needed anymore (I think what this is doing?) - having the dead ones survive the pass always confuses me when looking at IR. We could also make subspan ops erase themselves when there are no users (I think there are already a default pattern like EraseUnusedOp in StreamOps.cpp that we could use). They could probably also be marked pure - they're equivalent to function arguments and should be fine to CSE.

2023-02-09 00:32 UTC, MaheshRavishankar commented
Agreed. They were marked side effecting for some reason, I don't remember why. If we can make them pure, then we can delete some code

2023-02-09 00:34 UTC, benvanik commented
Looks like it was changed from pure way back in the day (https://github.com/iree-org/iree/pull/4563) - maybe was some issue in bufferization at the time that may not exist now 🤞

2023-02-09 01:12 UTC, MaheshRavishankar commented
> Looks like it was changed from pure way back in the day (#4563) - maybe was some issue in bufferization at the time that may not exist now 🤞

So it was :P . Yeah, I dont remember why I did it. It would be nice to just try making it a pure op and see what happens.

2023-02-09 01:32 UTC, ThomasRaoux approved these changes
Unless there are objections in the discussion I think this is a nice improvement. Note that this is done mostly to make IR more readable and has actually no functional impact

2023-02-09 01:43 UTC, MaheshRavishankar commented
https://github.com/iree-org/iree/blob/main/compiler/src/iree/compiler/Codegen/Common/CleanupBufferAllocViewPass.cpp is the pass I was talking about. Seems to be very similar. Can we refactor to reuse..

2023-02-09 01:43 UTC, MaheshRavishankar requested changes
This is duplicate of existing functionality maybe?

2023-03-04 01:32 UTC, antiagainst commented
Yeah. It's kinda historical that the subspan op is not a pure op. IIRC it was due to the initial dependency analysis dated back to the Linalg buffer days. Now Quinn has https://github.com/openxla/iree/pull/12494; this is not necessary anymore. :)

2023-03-04 01:32 UTC, closed without merging