Perform GPU address space lowering during LLVM lowering
iree-org/iree pull request #12213
Opened 2023-02-15 03:16 UTC by spaceotter

This patch removes the standalone GPU address space lowering pass and performs that conversion from the address space enum during the respective LLVM conversion passes. That matches upstream LLVM. This allows the removal of a hard-coded address space constant from the conversion of shared memory AllocOps to global variables. The correct address space has to be provided as an option for the pattern.

2023-02-15 17:56 UTC, ThomasRaoux requested changes
We need to move away from the separate patterns converting memory space and do it during conversion to LLVM

2023-02-15 17:56 UTC, ThomasRaoux commented on compiler/src/iree/compiler/Codegen/Utils/GPUUtils.cpp
> +  gpu::populateLowerMemorySpaceOpLegality(target);
Those patterns have been removed upstream, we need to do the memory space conversion during conversion to LLVM

2023-02-15 20:04 UTC, spaceotter commented on compiler/src/iree/compiler/Codegen/Utils/GPUUtils.cpp
> +  gpu::populateLowerMemorySpaceOpLegality(target);
I looked at what they do upstream, not sure it's possible here. Moving these type conversion to the LLVMTypeConverter doesn't work. I'll do a bit more poking around.

2023-02-21 02:37 UTC, spaceotter commented
It looks like the upstream integration should resolve the issue I had encountered in ConvertSharedMemAllocOp. Closing this PR.

2023-02-21 02:37 UTC, closed without merging