Explicitly initialize entire VM variant union and fix storage size
iree-org/iree pull request #12428
Opened 2023-02-28 23:46 UTC by GMNGeoffrey

The former addresses test failures when building with
`-ftrivial-auto-var-init=pattern`.

The latter fixes `IREE_VM_VALUE_STORAGE_SIZE` to correspond to the size
of `iree_vm_ref_t`, which is `sizeof(void *) + 3`, but due to
padding/alignment rounds up to 16.

2023-02-28 23:50 UTC, benvanik requested changes

2023-02-28 23:50 UTC, benvanik commented on runtime/src/iree/vm/value.h
> +#define IREE_VM_VALUE_STORAGE_SIZE 16
this is used for iree_vm_value_t, which cannot store refs and only needs 8 bytes
if this is also used for variant then that will need to be changed - we don't want values to be 16 bytes

2023-02-28 23:50 UTC, GMNGeoffrey commented
Note: this is being upstreamed from an internal contribution. I'm just the messenger here :-) http://cl/512881975 is the internal change.

2023-02-28 23:51 UTC, GMNGeoffrey commented on runtime/src/iree/vm/value.h
> +#define IREE_VM_VALUE_STORAGE_SIZE 16
I suspected you would want to change this in a different way :-) See note below. You're a reviewer on the internal change as well

2023-02-28 23:59 UTC, benvanik commented on runtime/src/iree/vm/value.h
> +#define IREE_VM_VALUE_STORAGE_SIZE 16
It's invalid, so it's less a change in a different way and more this is not a working PR that can land :)

2023-03-01 17:43 UTC, GMNGeoffrey commented on runtime/src/iree/vm/value.h
> +#define IREE_VM_VALUE_STORAGE_SIZE 16
IIUC there is a bug here and it's that `IREE_VM_VALUE_STORAGE_SIZE` is being used for `iree_vm_ref_t` here: https://cs.github.com/openxla/iree/blob/564ede9946acd621abed6d7f04da36c37cd04b90/runtime/src/iree/vm/type_def.h?q=IREE_VM_VALUE_STORAGE_SIZE#L76. That was added in https://github.com/openxla/iree/commit/84dce47606d5940e1089dcb1cda42c1ddf277636. It looks like iree_vm_ref_t contained more than just the `void *` pointer even on its introduction in https://github.com/openxla/iree/commit/4e4f587b254c7e12aa3ceddb121a7cd54d4d1f83. So the fix here is to use a different value for the storage size of `iree_vm_variant_t`, yes?

@Maximus- are these two changes actually connected or should we split the initialization from the storage size?

2023-03-01 17:52 UTC, GMNGeoffrey commented
Also appears that this breaks the Windows build:

> 2023-02-28T23:53:15.3430089Z C:\ProgramData\Chocolatey\bin\ccache C:\PROGRA\~1\MICROS\~2\2022\ENTERP\~1\VC\Tools\MSVC\1434\~1.319\bin\Hostx64\x64\cl.exe  /nologo /TP  -external:IC:\a\iree\iree -external:IC:\a\iree\iree\build-runtime-windows -external:IC:\a\iree\iree\runtime\src -external:IC:\a\iree\iree\build-runtime-windows\runtime\src -external:IC:\a\iree\iree\build-runtime-windows\runtime\src\iree\base\internal\flatcc -external:IC:\a\iree\iree\third_party\flatcc\include -external:IC:\a\iree\iree\build-runtime-windows\runtime\src\iree\schemas -external:W0 /DWIN32 /D_WINDOWS /EHsc /Z7 /O2 /Ob1  -MD /DWIN32_LEAN_AND_MEAN /DNOMINMAX /D_USE_MATH_DEFINES /D_CRT_SECURE_NO_WARNINGS /D_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES /GR- /bigobj /Zc:preprocessor /W3 /wd4200 /wd4018 /wd4146 /wd4244 /wd4267 /wd4005 /wd4065 /wd4141 /wd4624 /wd5105 -IC:/a/iree/iree/third_party/flatcc/include/ -IC:/a/iree/iree/third_party/flatcc/include/flatcc/reflection/ -std:c++17 /showIncludes /Foruntime\src\iree\tooling\CMakeFiles\iree_tooling_comparison.objects.dir\comparison.cc.obj /Fdruntime\src\iree\tooling\CMakeFiles\iree_tooling_comparison.objects.dir\ /FS -c C:\a\iree\iree\runtime\src\iree\tooling\comparison.cc
2023-02-28T23:53:15.3449448Z C:\a\iree\iree\runtime\src\iree\tooling\comparison.cc(245): error C7555: use of designated initializers requires at least '/std:c++20'

2023-03-01 18:13 UTC, benvanik commented on runtime/src/iree/vm/value.h
> +#define IREE_VM_VALUE_STORAGE_SIZE 16
I'm not sure - the value_storage is as noted just for values, not including ref - value_storage should never be used to access the ref, which is not a value, so it shouldn't match in size.

2023-03-01 18:14 UTC, benvanik commented on runtime/src/iree/vm/value.h
> +#define IREE_VM_VALUE_STORAGE_SIZE 16
(motivation for changes like this is useful - I'm not seeing why this is an issue)

also note that iree_vm_ref_t is smaller on 32-bit systems - so it only needs 8 bytes - so setting 16 would just pad out an extra 8 bytes on 32-bit targets

2023-03-01 19:36 UTC, Maximus- commented on runtime/src/iree/vm/value.h
> +#define IREE_VM_VALUE_STORAGE_SIZE 16
These changes may not be related. My thought process went like this:

The underlying problem I was seeing was that the reference count was uninitialized in many tests, so I figured value_storage would be a large enough type to initialize any member of the union. 

I then noticed that value_storage wasn't as large as the ref_t type, so it wouldn't fully initialize it (on 64bit platforms).

I was trying to understand why just using `{ 0 }` wasn't initializing the entire union, but I have no conclusion on that.

[Godbolt test](https://godbolt.org/z/h95nPGWcz). The function loads `170` into several different places, which is the clang pattern fill (`0xAA`). This means the union is not being initialized fully, so clang believes it needs to initialize them.

2023-03-01 19:39 UTC, Maximus- commented
> Also appears that this breaks the Windows build:
> 
> > 2023-02-28T23:53:15.3430089Z C:\ProgramData\Chocolatey\bin\ccache C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\cl.exe  /nologo /TP  -external:IC:\a\iree\iree -external:IC:\a\iree\iree\build-runtime-windows -external:IC:\a\iree\iree\runtime\src -external:IC:\a\iree\iree\build-runtime-windows\runtime\src -external:IC:\a\iree\iree\build-runtime-windows\runtime\src\iree\base\internal\flatcc -external:IC:\a\iree\iree\third_party\flatcc\include -external:IC:\a\iree\iree\build-runtime-windows\runtime\src\iree\schemas -external:W0 /DWIN32 /D_WINDOWS /EHsc /Z7 /O2 /Ob1  -MD /DWIN32_LEAN_AND_MEAN /DNOMINMAX /D_USE_MATH_DEFINES /D_CRT_SECURE_NO_WARNINGS /D_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES /GR- /bigobj /Zc:preprocessor /W3 /wd4200 /wd4018 /wd4146 /wd4244 /wd4267 /wd4005 /wd4065 /wd4141 /wd4624 /wd5105 -IC:/a/iree/iree/third_party/flatcc/include/ -IC:/a/iree/iree/third_party/flatcc/include/flatcc/reflection/ -std:c++17 /showIncludes /Foruntime\src\iree\tooling\CMakeFiles\iree_tooling_comparison.objects.dir\comparison.cc.obj /Fdruntime\src\iree\tooling\CMakeFiles\iree_tooling_comparison.objects.dir\ /FS -c C:\a\iree\iree\runtime\src\iree\tooling\comparison.cc
> > 2023-02-28T23:53:15.3449448Z C:\a\iree\iree\runtime\src\iree\tooling\comparison.cc(245): error C7555: use of designated initializers requires at least '/std:c++20'

Oops! I don't have a good answer for this. Would love some ideas on how we can fully initialize the union without making too much noise :)

I can implement iree_vm_variant_empty() differently depending on whether or not MSVC Is used, but that seems unfortunate. :(

2023-03-01 23:09 UTC, GMNGeoffrey commented on runtime/src/iree/vm/value.h
> +#define IREE_VM_VALUE_STORAGE_SIZE 16
Here are the failures repro'ed in OSS: https://github.com/openxla/iree/actions/runs/4308619652/jobs/7515099139

2023-03-02 00:56 UTC, GMNGeoffrey commented on runtime/src/iree/vm/value.h
> +#define IREE_VM_VALUE_STORAGE_SIZE 16
Ok I figured out why:

> When initializing a [union](https://en.cppreference.com/w/c/language/union), the initializer list must have only one member, which initializes the first member of the union unless a designated initializer is used (since C99).

So the rest of the bits are uninitialized. Related stack overflow: https://stackoverflow.com/q/26793250. So AFAICT there *isn't* any way to initialize the whole thing without designated initializers. But it seems like maybe we shouldn't be dereferencing this pointer anyway? Or if the intent that it be initialized to zero and we check it's zero before dereferencing, for instance, then we can move the unit8 array to be the *first* union member

2023-03-02 01:04 UTC, GMNGeoffrey commented on runtime/src/iree/vm/value.h
> +#define IREE_VM_VALUE_STORAGE_SIZE 16
Yup, we're checking if that's a null pointer before releasing. That matches the stack that asan is giving: https://github.com/openxla/iree/blob/7875b8ebc7c0b58c23fd34e718f9006d27c5eafc/runtime/src/iree/vm/ref.c#L247

2023-03-02 01:27 UTC, GMNGeoffrey commented on runtime/src/iree/vm/value.h
> +#define IREE_VM_VALUE_STORAGE_SIZE 16
I pushed some commits moving the value storage arrays to the front and ensuring that we don't exceed 8 bytes on 32-bit targets.

2023-03-07 19:02 UTC, GMNGeoffrey commented
Ping on this?

2023-03-07 19:10 UTC, benvanik commented
You still have the invalid `#define IREE_VM_VALUE_STORAGE_SIZE 16` - that should be 8.

2023-03-07 19:39 UTC, GMNGeoffrey commented
> You still have the invalid `#define IREE_VM_VALUE_STORAGE_SIZE 16` - that should be 8.

Weird I thought I reverted that. I think I must have been viewing the diff vs the wrong base or something. Fixed

2023-03-07 20:19 UTC, GMNGeoffrey commented
Ok and now it's somehow failing asan even though I ran asan tests before uploading :-/

2023-03-07 23:59 UTC, GMNGeoffrey commented
It looks like you turned `iree_vm_variant_empty` into a function in https://github.com/openxla/iree/commit/78fc0e31031f74bbb919910dc14fadce940e6f71 (discovered via merge conflict). I no longer hit the failures here with `-ftrivial-auto-var-init=pattern`, which I will enable in https://github.com/openxla/iree/pull/12447

2023-03-07 23:59 UTC, closed without merging