Disable masking on Aarch64 without SVE support
iree-org/iree pull request #12487
Opened 2023-03-03 03:41 UTC by dcaballe

Masking is a catch-all transformation that only requires vector sizes to be provided to the vectorizer. This patch makes sure that we don't provide vector sizes to the vectorizer when we don't want to explicitly enable vector masking (e.g., Aarch64 without SVE support, at least for now).

2023-03-03 21:54 UTC, vmurali approved these changes

2023-03-03 22:55 UTC, MaheshRavishankar requested changes
LGTM but maybe there is one small bug here.

2023-03-03 22:55 UTC, MaheshRavishankar commented on compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp
> +    options.enableVectorMasking = true;
THis is set to true unconditionally?

2023-03-04 00:33 UTC, MaheshRavishankar approved these changes

2023-03-07 05:15 UTC, dcaballe commented
Hey @pzread, it looks like the x86 benchmarks were executed successfully but the report wasn't posted. Android ones seem to be failing due to a cancelation signal after a timeout. I run them both multiple times. Anything going on?

2023-03-08 19:09 UTC, hanhanW approved these changes

2023-03-09 23:59 UTC, hanhanW commented on compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp
> +    options.vectorize = enableVectorMasking;
This should be `options.enableVectorMasking = enableVectorMasking;`

2023-03-10 06:47 UTC, dcaballe commented
Masking is a catch-all transformation that only requires vector sizes to be provided to the vectorizer. This patch makes sure that we don't provide vector sizes to the vectorizer when we don't want to explicitly enable vector masking (e.g., Aarch64 without SVE support, at least for now).

2023-03-10 06:48 UTC, merged