Add a pass to correctly represent `hal.interface.binding.subspan` ops with offsets.
iree-org/iree pull request #12510
Opened 2023-03-04 05:43 UTC by MaheshRavishankar

`hal.interface.binding.subspan` ops of the form

```
%subspan = hal.interface.binding.subspan set(0) binding(0) offset(%o0)
    : memref<?x?xf32>{%s0, %s1}
```

are to be interpreted as follows.
- `hal.interface.binding.subspan set(0) binding(0)` is effectively `char *binding`.
- A non-zero offset `offset(%o0)` corresponds to performing `binding + %o0`.
- The bytes of data from `[binding + %o0, binding + %o0 + %s0 * %s1 * <elem-type-byte-width>)` can be viewed as a `memref<?x?xf32>{%s0, %s1}`.

For backends that have a operations which can perform pointer arithmetic (like `gep` instructions in LLVM), this interpretation can be directly lowered. Backends like VMVX end up using `hal.buffer.subspan` operations to represent the pointer+offset. This operation does not get lowered to VM dialect directly, but are rather folded away with uses. For cases where we need to get a raw pointer + offset value, these operations dont get folded with uses and fail compilation.

One way to handle this is to convert these operations to represent the entire subspan under `memref` semantics. So the above operation can be represented as

```
%subspan = hal.interface.binding.subspan set(0) binding(0) offset(%o0)
    : memref<?x?xf32, strided<[?, 1], offset : ?>>{%s0, %s1}
```

giving the `subspan` effectively `subview` semantics. This allows use of operations like `memref.extract_strided_metadata` to resolve the offsets, sizes, base pointer usages, etc.

Fixes #12480

2023-03-06 09:09 UTC, qcolombet commented
I don't understand how this patch fixes the problem.
Given we stop to propagate the "correct" `memref` type on certain operations (currently `func::ReturnOp`, and `scf::YieldOp`), we will still have uses with the old value and thus the invalid lowering, wouldn't we?

(BTW, I was surprised that you didn't bail out on function calls as well. How do you propagate the fix across function boundaries?)

I don't know how feasible/involved that is, but could we use the "correct" `memref` type from the get go instead of partially fixing it?

Anyhow, I'll reply in the main thread (https://github.com/openxla/iree/issues/12480#issuecomment-1453918287) to keep the main conversation in one place. The semantic of `memref` upstream is not super practical IMHO.

2023-03-09 01:59 UTC, stellaraccident commented
> I don't understand how this patch fixes the problem. Given we stop to propagate the "correct" `memref` type on certain operations (currently `func::ReturnOp`, and `scf::YieldOp`), we will still have uses with the old value and thus the invalid lowering, wouldn't we?
> 
> (BTW, I was surprised that you didn't bail out on function calls as well. How do you propagate the fix across function boundaries?)
> 
> I don't know how feasible/involved that is, but could we use the "correct" `memref` type from the get go instead of partially fixing it?
> 
> Anyhow, I'll reply in the main thread ([#12480 (comment)](https://github.com/openxla/iree/issues/12480#issuecomment-1453918287)) to keep the main conversation in one place. The semantic of `memref` upstream is not super practical IMHO.

Mahesh and I went back and forth on this for a bit, trying to split out what the actual semantics of hal.interface.binding.subspan are and the relative odd lengths that the memref type goes to in order to avoid a dependence on a raw pointer type (my interpretation of the situation). I think my conclusion was that there are certainly improvements that can be made to the memref side, but how we were reasoning about the binding.subspan op were just incomplete and was missing a step in lowering: This manifests on targets that lack a gep.

This seemed like a way out of the situation where it is hard to change the semantics of that op in one step atomically for all backends (i.e. from gep to pure cast semantics). It would be great to find out that we could actually just fix it in one step because this is obviously not ideal.

2023-03-09 02:01 UTC, stellaraccident commented
> Mahesh and I went back and forth on this for a bit, trying to split out what the actual semantics of hal.interface.binding.subspan are and the relative odd lengths that the memref type goes to in order to avoid a dependence on a raw pointer type (my interpretation of the situation). I think my conclusion was that there are certainly improvements that can be made to the memref side, but how we were reasoning about the binding.subspan op were just incomplete and was missing a step in lowering: This manifests on targets that lack a gep.
> 
> This seemed like a way out of the situation where it is hard to change the semantics of that op in one step atomically for all backends (i.e. from gep to pure cast semantics). It would be great to find out that we could actually just fix it in one step because this is obviously not ideal.

(moving comment to issue)

2023-03-09 20:00 UTC, antiagainst requested changes
Fantastic Mahesh! Thanks for addressing this semantic gap! Overall approach LGTM; though I think we might want to iterate on how we treat uniform/storage static/dynamic types a bit--it's load bearing. Let me know if you'd like to chat, or if you'd like me to land a commit on top of this to fix it, given you have already done a lot here. I'm happy to fix up the rest. :)

2023-03-09 20:00 UTC, antiagainst commented on compiler/src/iree/compiler/Codegen/Common/FixupSubspanWithOffsets.cpp
> +static void replaceUsesTransitively(RewriterBase &rewriter, Location loc,
Ha. This is pretty much doing a minimal rewrite infra like that exists for dialect conversion. I can see why you are doing it like this here. Dialect conversion is a bit painful to use for such cases. Really hope we can have type conversion framework to take into the op into consideration, somehow..

2023-03-09 20:00 UTC, antiagainst commented on compiler/src/iree/compiler/Codegen/Common/FlattenMemRefSubspanPass.cpp
> +        return std::nullopt;
Should just return `nullptr` to fail the type conversion entirely here?

2023-03-09 20:00 UTC, antiagainst commented on compiler/src/iree/compiler/Codegen/Common/FlattenMemRefSubspanPass.cpp
> +          type.hasStaticShape() ? type.getNumElements() : ShapedType::kDynamic;
Hmm, can we keep the existing behavior of treating uniform/storage buffer differently and not solely relying on whether the input type has static shape? It's load-bearing here--1) if we convert all static shaped storage buffers into known sized 1-D array, which pretty much covers the majority of the existing models, we aren't able to unify different subspan ops with the same (set, binding) numbers to the same one, which would break WebGPU / MoltenVK. 2) if we convert uniform buffer to dynamic shaped, it will error out as uniform buffers cannot be dynamic shaped in Vulkan.

2023-03-09 20:00 UTC, antiagainst commented on compiler/src/iree/compiler/Codegen/Common/FlattenMemRefSubspanPass.cpp
> +        makeStridedLinearLayoutMap(strides, 0, builder.getContext());
Are we assuming the `offset` being zero here? If so can we put an assert at least?

2023-03-09 20:00 UTC, antiagainst commented on compiler/src/iree/compiler/Codegen/Common/FlattenMemRefSubspanPass.cpp
> +          transferReadOp,
Accidentally reformatted?

2023-03-09 20:00 UTC, antiagainst commented on compiler/src/iree/compiler/Codegen/Common/FlattenMemRefSubspanPass.cpp
> +      // The current MemRef has rank zero but a non-zero
Accidentally reformatted?

2023-03-09 20:00 UTC, antiagainst commented on compiler/src/iree/compiler/Codegen/Common/FlattenMemRefSubspanPass.cpp
> +          transferWriteOp,
Accidentally reformatted?

2023-03-09 20:00 UTC, antiagainst commented on compiler/src/iree/compiler/Codegen/Common/test/flatten_memref_subspan.mlir
>  // -----
It looks we are missing test cases for n-D (n >= 1) memref with zero offset.

2023-03-09 21:01 UTC, MaheshRavishankar commented on compiler/src/iree/compiler/Codegen/Common/FixupSubspanWithOffsets.cpp
> +static void replaceUsesTransitively(RewriterBase &rewriter, Location loc,
We have something like this in `Codegen/Utils.h` I am going to replace that with this one....

2023-03-09 21:01 UTC, MaheshRavishankar commented on compiler/src/iree/compiler/Codegen/Common/FlattenMemRefSubspanPass.cpp
> +        return std::nullopt;
Is that what the type converter expects? I will change and try.

2023-03-09 21:01 UTC, MaheshRavishankar commented on compiler/src/iree/compiler/Codegen/Common/FlattenMemRefSubspanPass.cpp
> +          type.hasStaticShape() ? type.getNumElements() : ShapedType::kDynamic;
If we need to unify things to the same (set, binding) then that needs to happen separately. It seems like a layering issue to do it here cause we are dropping information for all backends, when we dont need to.... If we have static information that should be preserved unless it is explicitly erased? So what I have here is basically should not affect (2), but should affect (1) that probably needs to be handled separately? Could that issue be fixed as a follow up?

2023-03-09 21:01 UTC, MaheshRavishankar commented on compiler/src/iree/compiler/Codegen/Common/FlattenMemRefSubspanPass.cpp
> +        makeStridedLinearLayoutMap(strides, 0, builder.getContext());
No the offset is not zero, but the offset should not be accounted for every time you linearize. That double counts the offset. Thankfully keeping it as is means that when lowering to spir-v etc the offset gets accounted for. Ill leave a comment.

2023-03-09 21:01 UTC, MaheshRavishankar commented on compiler/src/iree/compiler/Codegen/Common/FlattenMemRefSubspanPass.cpp
> +          transferReadOp,
I just ran clang-format.

2023-03-09 21:01 UTC, MaheshRavishankar commented on compiler/src/iree/compiler/Codegen/Common/FlattenMemRefSubspanPass.cpp
> +          transferWriteOp,
I just ran clang-format.

2023-03-09 21:01 UTC, MaheshRavishankar commented on compiler/src/iree/compiler/Codegen/Common/FlattenMemRefSubspanPass.cpp
> +      // The current MemRef has rank zero but a non-zero
I just ran clang-format.

2023-03-09 21:01 UTC, MaheshRavishankar commented on compiler/src/iree/compiler/Codegen/Common/test/flatten_memref_subspan.mlir
>  // -----
That is true, but is not affected by this change.... Added a test anyway.

2023-03-10 00:38 UTC, antiagainst commented on compiler/src/iree/compiler/Codegen/Common/FlattenMemRefSubspanPass.cpp
> +        makeStridedLinearLayoutMap(strides, 0, builder.getContext());
I see. Thanks for the explanation!

2023-03-10 00:39 UTC, antiagainst commented on compiler/src/iree/compiler/Codegen/Common/FlattenMemRefSubspanPass.cpp
> +          type.hasStaticShape() ? type.getNumElements() : ShapedType::kDynamic;
Chatted offline. I'll prepare an additional patch to handle the above said issues, and we can then land together

2023-03-13 19:26 UTC, antiagainst commented on compiler/src/iree/compiler/Codegen/Common/FlattenMemRefSubspanPass.cpp
> +          type.hasStaticShape() ? type.getNumElements() : ShapedType::kDynamic;
I've created https://github.com/openxla/iree/pull/12617 to handle this. So releasing the lock.

2023-03-13 19:26 UTC, antiagainst approved these changes

2023-03-13 21:48 UTC, merged