Print meaningful error when too much shared memory is allocated on CUDA
iree-org/iree pull request #12597
Opened 2023-03-10 21:57 UTC by KoolJBlack

Queries  the driver for the max amount of shared memory allowed then errors if too much is requested. 

Addresses #12146

2023-03-10 21:58 UTC, benvanik requested changes

2023-03-10 21:58 UTC, benvanik commented on runtime/src/iree/hal/drivers/cuda/native_executable.c
> +      int32_t max_shared_mem;
always zero initialize (`= 0;`) - locals are undefined by default

2023-03-10 21:58 UTC, benvanik commented on runtime/src/iree/hal/drivers/cuda/native_executable.c
> +      if (shared_memory_sizes[i] > max_shared_mem) {
this leaks/ignores status - you need to do an `if (!iree_status_is_ok(status)) break;` after each `status =`

2023-03-13 23:37 UTC, powderluv commented
Do we need the same for SPIR-V like in https://github.com/openxla/iree/issues/12523 ?

2023-03-13 23:48 UTC, benvanik approved these changes

2023-03-13 23:49 UTC, benvanik commented
We should be able to get some more detailed diagnostics on both CUDA/SPIR-V - I'll look at plumbing that through (we can ask the driver compilers for full logs and attach those to our errors). This is still nice as a concise error message but the general one will work to avoid needing a bunch of these kind of things.

2023-03-14 14:53 UTC, merged