Use iree_string_view_atoi_int32 in CUDA driver module flag parsing.
iree-org/iree pull request #12616
Opened 2023-03-13 18:20 UTC by okkwon

use iree_string_view_atoi_int32() to parse strings into int32_t.

2023-03-13 18:25 UTC, benvanik requested changes
We have this already under iree_string_view_atoi_int32 - you can use that instead

2023-03-16 00:54 UTC, benvanik requested changes

2023-03-16 00:54 UTC, benvanik commented on runtime/src/iree/hal/drivers/cuda/registration/driver_module.c
> +  parsed = iree_string_view_atoi_int32(nprocs_sv, &nprocs);
```suggestion
  int32_t nprocs = -1;
  bool parsed = iree_string_view_atoi_int32(iree_make_cstring_view(nprocs_str), &nprocs);
```

(always default initialize values)

2023-03-16 00:54 UTC, benvanik commented on runtime/src/iree/hal/drivers/cuda/registration/driver_module.c
> +  if (!parsed || procid < 0 || procid >= nprocs) {
```suggestion
  int32_t procid = -1;
  parsed = iree_string_view_atoi_int32(iree_make_cstring_view(procid_str), &procid);
  if (!parsed || procid < 0 || procid >= nprocs) {
```

2023-03-16 00:55 UTC, benvanik reviewed
(I also changed the issue title - please try to use titles that are descriptive of what the change does)

2023-03-16 03:47 UTC, okkwon commented
Thanks for the suggestion @benvanik!

2023-03-16 03:51 UTC, benvanik approved these changes

2023-03-16 16:48 UTC, merged