Updating architecture diagram with "plugins" in a few places.
iree-org/iree pull request #12615
Opened 2023-03-13 18:16 UTC by benvanik

2023-03-14 19:52 UTC, jpienaar reviewed
I don't know if this actually shows where plugin enables generalization all. It makes it feel like something imported, but it feels closer to PGO feedback, that also feeds into the device codegen. (I feel like runtime has the VM already shown here).

2023-03-27 22:27 UTC, ScottTodd requested changes

2023-03-27 22:27 UTC, ScottTodd commented on docs/website/docs/assets/images/iree_architecture_dark.svg
Plugin in the top left of this file looks hard to read - maybe change the colors to match the other items?

2023-03-27 22:31 UTC, ScottTodd commented on docs/website/docs/assets/images/iree_architecture_dark.svg
Preview here: https://github.com/openxla/iree/tree/benvanik-arch-svg#architecture-overview

(GitHub diff makes it look hard to read, when it's actually a little _too_ easy to read with the higher contrast than the other items)

![image](https://user-images.githubusercontent.com/4010439/228081516-0dd05b28-eeaa-46f3-8183-9d934da73fbc.png)

2023-03-30 16:53 UTC, ScottTodd commented on docs/website/docs/assets/images/iree_architecture_dark.svg
Sent https://github.com/openxla/iree/pull/12856 with some tweaks ("Plugin" font color, "IREE Importers" background/stroke color)

2023-04-19 23:06 UTC, ScottTodd approved these changes

2023-04-19 23:08 UTC, merged