Remove flag from bazelrc being removed from Bazel
iree-org/iree pull request #12671
Opened 2023-03-17 16:09 UTC by jpienaar

--distinct_host_configuration is being switched to NOP and removed from bazel.

2023-03-17 16:27 UTC, GMNGeoffrey requested changes
We're still using Bazel 5.1, so I'm not sure this applies. @stellaraccident added this after observing that Bazel was rebuilding the entire project on Windows. Let's check if that's fixed before removing this

2023-03-17 16:55 UTC, stellaraccident approved these changes
I've given up on getting bazel to not build everything three times with bazel. Fine to remove.

2023-03-27 22:51 UTC, ScottTodd approved these changes
Well, I gave up on getting Bazel to work at all on Windows >_>

(every time I tried to use Bazel after a few weeks of regular CMake use, Bazel found some new way to break)

2023-03-27 22:52 UTC, jpienaar commented
OK with you @GMNGeoffrey ?

2023-03-27 23:52 UTC, GMNGeoffrey approved these changes
![image](https://user-images.githubusercontent.com/5732088/228092166-f2af307a-6ee1-47ab-b4eb-3b9f2045b8be.png)

2023-04-12 02:24 UTC, merged