Introduce LLVMCPUTile to get rid of CodegenStrategy.
iree-org/iree pull request #12798
Opened 2023-03-28 18:33 UTC by hanhanW

Is is a walk-based transformation. It calls scf::tileUsingSCFForOp method to tile all TileInterface operations. The functionality is tested upstream. The LLVMCPU integration tests are covered by pipeline_tests.

2023-03-28 18:35 UTC, hanhanW commented on compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPUTile.cpp
> +    if (isa<tensor::PadOp>(computeOp)) continue;
@MaheshRavishankar this should cover your changes in pad_fusion branch. And yes, we don't tile pad ops that are created by DoubleTilingPadExpert.

2023-03-28 19:01 UTC, MaheshRavishankar requested changes
Nice! This replaces single tiling expert right? It would be good to also merge the PR that remvoes it (I assume you already have it) with this PR. It gives an idea of what is being removed and what is it being replaced with.

2023-03-28 19:01 UTC, MaheshRavishankar commented on compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPUTile.cpp
> +static SmallVector<Value> buildTileSizesForOp(OpBuilder &b, Operation *op,
Is this method copied from somewhere?

2023-03-28 20:12 UTC, hanhanW commented on compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPUTile.cpp
> +static SmallVector<Value> buildTileSizesForOp(OpBuilder &b, Operation *op,
it is copied from LinalgTensorCodegenDriver.cpp The method in the CodegenDriver file is removed in the following commit.

https://github.com/openxla/iree/blob/d136a6d33c51a5688728a166f835af2d5b3bf92b/compiler/src/iree/compiler/Codegen/Sandbox/LinalgTensorCodegenDriver.cpp#L86-L101

2023-03-28 21:31 UTC, MaheshRavishankar approved these changes

2023-03-28 22:32 UTC, dcaballe approved these changes
Awesome!

2023-03-29 01:06 UTC, hanhanW commented
I feel that the regression is as same as https://github.com/openxla/iree/issues/12808

I'll land the PR after confirming it, i.e., there are no regressions.

2023-03-29 05:04 UTC, dcaballe commented
It could be related to this canonicalization pattern: https://reviews.llvm.org/D147099

I didn't see i1 transposes while profiling the models but now it looks like some canonicalizations are not happening in the same order as before and that is exposing some issues. For example, it looks like https://reviews.llvm.org/D147099 is now needed because `vector.create_mask` is turned into `vector.constant_mask` before the transposed is removed.

2023-03-29 18:39 UTC, hanhanW commented
most of regressions are gone after re-triggering the benchmarks. Looks like it's a false alarm

2023-03-29 20:15 UTC, merged