[Transform] Add op to apply im2col patterns and update the workgroup count region
iree-org/iree pull request #12804
Opened 2023-03-28 21:13 UTC by qedawkins

Required for implementing a pipeline for implicit gemm on GPU backends. Im2col converts a convolution to a gather on the input and a gemm. This collapses the image dimensions of the output for 2D convolutions and thus the workgroup count compute region needs to be updated to match the new iteration ranges for the main compute op.

Depends on https://reviews.llvm.org/D144678

2023-03-30 21:22 UTC, MaheshRavishankar requested changes
I am not really sure whats going on here. These seems to breaking layering to make this work..... I dont think you need this

2023-03-30 21:37 UTC, qedawkins commented
> I am not really sure whats going on here. These seems to breaking layering to make this work..... I dont think you need this

Essentially when applying im2col inside a dispatch, this introduces a collapse on the image (H & W) dimensions of the output of the convolution. Those reshapes are expected to be bubbled to the edges of the kernel and merged with the `hal.interface.binding.subspan` ops, however tiling to workgroups happens based on the collapsed shape, not the original convolution shape and thus the workgroup count compute region needs to be updated accordingly. This might not be the right place for this op then and am open to suggestions.

2023-03-30 21:57 UTC, MaheshRavishankar commented
> > I am not really sure whats going on here. These seems to breaking layering to make this work..... I dont think you need this
> 
> Essentially when applying im2col inside a dispatch, this introduces a collapse on the image (H & W) dimensions of the output of the convolution. Those reshapes are expected to be bubbled to the edges of the kernel and merged with the `hal.interface.binding.subspan` ops, however tiling to workgroups happens based on the collapsed shape, not the original convolution shape and thus the workgroup count compute region needs to be updated accordingly. This might not be the right place for this op then and am open to suggestions.
> 

I would expect for implicit gemm you would tile and distribute on convolution first and then apply im2col on a tiled convolution. Doing im2col first seems like an unnecessary complication.

2023-03-30 22:05 UTC, qedawkins commented
> > Essentially when applying im2col inside a dispatch, this introduces a collapse on the image (H & W) dimensions of the output of the convolution. Those reshapes are expected to be bubbled to the edges of the kernel and merged with the `hal.interface.binding.subspan` ops, however tiling to workgroups happens based on the collapsed shape, not the original convolution shape and thus the workgroup count compute region needs to be updated accordingly. This might not be the right place for this op then and am open to suggestions.
> 
> I would expect for implicit gemm you would tile and distribute on convolution first and then apply im2col on a tiled convolution. Doing im2col first seems like an unnecessary complication.

There was a discussion about this before: https://discord.com/channels/689900678990135345/689932666505920596/1080196907797860373

Essentially we end up with those reshapes inside the scf.forall for implicit gemm and it causes problems for bufferization.

2023-03-30 22:22 UTC, MaheshRavishankar commented
> > > Essentially when applying im2col inside a dispatch, this introduces a collapse on the image (H & W) dimensions of the output of the convolution. Those reshapes are expected to be bubbled to the edges of the kernel and merged with the `hal.interface.binding.subspan` ops, however tiling to workgroups happens based on the collapsed shape, not the original convolution shape and thus the workgroup count compute region needs to be updated accordingly. This might not be the right place for this op then and am open to suggestions.
> > 
> > 
> > I would expect for implicit gemm you would tile and distribute on convolution first and then apply im2col on a tiled convolution. Doing im2col first seems like an unnecessary complication.
> 
> There was a discussion about this before: [discord.com/channels/689900678990135345/689932666505920596/1080196907797860373](https://discord.com/channels/689900678990135345/689932666505920596/1080196907797860373)
> 
> Essentially we end up with those reshapes inside the scf.forall for implicit gemm and it causes problems for bufferization.

I remember now... It would probably be good to look into that more... In any case you do need the extra buffer here to do the im2col... what is being tried here seems extremely fragile and I am not sure this can be supported long term (I have a long standing TODO to fix the workgroup count region generation)

2023-03-30 22:38 UTC, qedawkins commented
> > There was a discussion about this before: [discord.com/channels/689900678990135345/689932666505920596/1080196907797860373](https://discord.com/channels/689900678990135345/689932666505920596/1080196907797860373)
> > Essentially we end up with those reshapes inside the scf.forall for implicit gemm and it causes problems for bufferization.
> 
> I remember now... It would probably be good to look into that more... In any case you do need the extra buffer here to do the im2col... what is being tried here seems extremely fragile and I am not sure this can be supported long term (I have a long standing TODO to fix the workgroup count region generation)

Ok so are you suggesting going back to applying im2col before the first level of distribution then?

2023-03-30 23:16 UTC, MaheshRavishankar commented
> > > There was a discussion about this before: [discord.com/channels/689900678990135345/689932666505920596/1080196907797860373](https://discord.com/channels/689900678990135345/689932666505920596/1080196907797860373)
> > > Essentially we end up with those reshapes inside the scf.forall for implicit gemm and it causes problems for bufferization.
> > 
> > 
> > I remember now... It would probably be good to look into that more... In any case you do need the extra buffer here to do the im2col... what is being tried here seems extremely fragile and I am not sure this can be supported long term (I have a long standing TODO to fix the workgroup count region generation)
> 
> Ok so are you suggesting going back to applying im2col before the first level of distribution then?

Ill review this, but this seems very fragile... I am more suggesting not going down this path.

2023-03-30 23:28 UTC, ThomasRaoux commented
> > > > There was a discussion about this before: [discord.com/channels/689900678990135345/689932666505920596/1080196907797860373](https://discord.com/channels/689900678990135345/689932666505920596/1080196907797860373)
> > > > Essentially we end up with those reshapes inside the scf.forall for implicit gemm and it causes problems for bufferization.
> > > 
> > > 
> > > I remember now... It would probably be good to look into that more... In any case you do need the extra buffer here to do the im2col... what is being tried here seems extremely fragile and I am not sure this can be supported long term (I have a long standing TODO to fix the workgroup count region generation)
> > 
> > 
> > Ok so are you suggesting going back to applying im2col before the first level of distribution then?
> 
> Ill review this, but this seems very fragile... I am more suggesting not going down this path.

Is this something we need to discuss more in depth. Doing the conversion after tile and distribute is going to bring more challenges.

2023-03-30 23:36 UTC, MaheshRavishankar commented
> > > > > There was a discussion about this before: [discord.com/channels/689900678990135345/689932666505920596/1080196907797860373](https://discord.com/channels/689900678990135345/689932666505920596/1080196907797860373)
> > > > > Essentially we end up with those reshapes inside the scf.forall for implicit gemm and it causes problems for bufferization.
> > > > 
> > > > 
> > > > I remember now... It would probably be good to look into that more... In any case you do need the extra buffer here to do the im2col... what is being tried here seems extremely fragile and I am not sure this can be supported long term (I have a long standing TODO to fix the workgroup count region generation)
> > > 
> > > 
> > > Ok so are you suggesting going back to applying im2col before the first level of distribution then?
> > 
> > 
> > Ill review this, but this seems very fragile... I am more suggesting not going down this path.
> 
> Is this something we need to discuss more in depth. Doing the conversion after tile and distribute is going to bring more challenges.

Happy to discuss. I am not sure I can say more than doing im2col before distribution (and therefore having to change the number of workgroups) goes against what implicit gemm is (which is im2col at tile level). It seems strictly more involved to do im2col and then do tile + fuse + distribute. This seems like a fragile WAR to the bufferization issue (which I understand reshapes mess things up).

2023-03-30 23:46 UTC, ThomasRaoux commented
> Happy to discuss. I am not sure I can say more than doing im2col before distribution (and therefore having to change the number of workgroups) goes against what implicit gemm is (which is im2col at tile level). It seems strictly more involved to do im2col and then do tile + fuse + distribute. This seems like a fragile WAR to the bufferization issue (which I understand reshapes mess things up).

There are more reasons why it is simpler to do im2col before as it allows us to get back to the matmul code generation earlier and it makes it allows us to have a more unified code gen flow. 

> It seems strictly more involved to do im2col and then do tile + fuse + distribute

I think besides the problem with number of groups it is strictly simpler to do the im2col before. 

The assumption in the calculation of the number of workgroups is something we want to solve right? Wouldn't that make this problem go away?

Obviously it could be done in a different order but this will make the work more difficult and we get less sharing with the matmul codegen which is a big downside to me.

2023-03-31 00:09 UTC, qedawkins commented
> Happy to discuss. I am not sure I can say more than doing im2col before distribution (and therefore having to change the number of workgroups) goes against what implicit gemm is (which is im2col at tile level). It seems strictly more involved to do im2col and then do tile + fuse + distribute.

Setting up a discussion offline to decide on a way forward sounds like a good idea. I don't want to be pushing for fragility, although this group count adjustment is the only difference from distributing before im2col and in my experience it made the later codegen steps much simpler and closer to the matmul "happy path."

2023-03-31 00:24 UTC, MaheshRavishankar commented
> > Happy to discuss. I am not sure I can say more than doing im2col before distribution (and therefore having to change the number of workgroups) goes against what implicit gemm is (which is im2col at tile level). It seems strictly more involved to do im2col and then do tile + fuse + distribute. This seems like a fragile WAR to the bufferization issue (which I understand reshapes mess things up).
> 
> There are more reasons why it is simpler to do im2col before as it allows us to get back to the matmul code generation earlier and it makes it allows us to have a more unified code gen flow.
> 
> > It seems strictly more involved to do im2col and then do tile + fuse + distribute
> 
> I think besides the problem with number of groups it is strictly simpler to do the im2col before.

I am not sure why that is the case... it might be simpler with the current codegeneration stack, but implicit gemm is tile conv + im2col on tile. Here this is being reversed... irrespective of details, that seems inverted to me.

> 
> The assumption in the calculation of the number of workgroups is something we want to solve right? Wouldn't that make this problem go away?

There is no assumption here. When the dispatch was created there was some representation of the number of workgroups computed based on the operation that is tiled and distributed. For implicit gemm that still doesnt change... Doing im2col and using fusion so that you do im2col of the tile to get to implicit gemm is strictly harder (and inverted). Irrespective of the fragility of the number of workgroups, doing im2col on the whole tensor and then doing tile + fuse does not seem like the right approach....

> 
> Obviously it could be done in a different order but this will make the work more difficult and we get less sharing with the matmul codegen which is a big downside to me.

Dont see how the sharing is reduced? After tile and distribute of the conv. you can do im2col and get a matmul. So then its matmul codegen.....

2023-04-03 07:32 UTC, nicolasvasilache commented
Given what I am reading here, should this be a graph-level transform instead ?

2023-04-03 14:03 UTC, qedawkins commented
> Given what I am reading here, should this be a graph-level transform instead ?

If we do that then we rely on fusion to get to implicit gemm. Also the graph-level transform of this already exists as `transform.structured.convert_conv2d_to_img2col` where this is strictly for applying the pattern within a dispatch and needing to update the workgroup counts based on the new shape of the computation. There was a discussion offline and the conclusion was that this is fine as a workaround until some work to improve workgroup count computation comes in.

2023-04-03 16:50 UTC, MaheshRavishankar commented
> > Given what I am reading here, should this be a graph-level transform instead ?
> 
> If we do that then we rely on fusion to get to implicit gemm. 

Still wont address the issue. You will basically end up with the gemm + im2col in a dispatch like you have here.

2023-04-03 16:51 UTC, MaheshRavishankar approved these changes
I am unblocking this, but will probably be deprecated soon.

2023-04-03 16:51 UTC, MaheshRavishankar commented on compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.cpp
> +static LogicalResult adjustWorkgroupCountComputeRegionForImg2Col(
Could you please add a TODO to say this is to be deprecated after workgroup count is computed using slices....

2023-04-03 22:03 UTC, ThomasRaoux approved these changes
LGTM

2023-04-03 22:03 UTC, ThomasRaoux commented on compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.cpp
> +  auto im2col = maybeTransformed->first;
nit: spell out type here and in other places following this:
https://llvm.org/docs/CodingStandards.html#use-auto-type-deduction-to-make-code-more-readable

2023-04-03 23:12 UTC, qedawkins commented
Does squash and merge let me edit the commit message before pushing it? I haven't done this on GitHub before.

2023-04-03 23:47 UTC, MaheshRavishankar commented
Yes it does

2023-04-03 23:52 UTC, merged