[LLVMCPU] Add a flag to disable distribution.
iree-org/iree pull request #12942
Opened 2023-04-05 23:36 UTC by hanhanW

2023-04-05 23:50 UTC, MaheshRavishankar requested changes
I am not sure its great to add such an option.... This is for experimentation, and transform dialect path seems like the best way. This creates too many branch points that will be hard to maintain.

2023-04-05 23:59 UTC, dcaballe commented
Thanks for uploading this so quickly, Hanhan! 

Mahesh, I was discussing with Hanhan that I tried the code below and seemed to be enough. I think having this kind of flag would be useful in general, even we mark is as a debug/experimental flag.

```
@@ -358,7 +364,14 @@ static SmallVector<int64_t> getDefaultDistributedLoopTileSizes(
   assert(lbs.size() == ubs.size() && lbs.size() == minTileSizes.size() &&
          lbs.size() == maxTileSizes.size() &&
          "expected all vectors to be of equal size");
+
   size_t numDims = lbs.size();
+  // Set all the distribution tile sizes to zero if thread distribution is
+  // disabled.
+  if (!clEnableThreadDistribution) {
+    return SmallVector<int64_t>(numDims, 0);
+  }
+
   SmallVector<int64_t> distributedTileSizes(numDims, 1);
   SmallVector<int64_t> numWorkgroupsPerDim(numDims, 1);
   SmallVector<int64_t> workload(numDims, 1);
```

2023-04-06 00:03 UTC, MaheshRavishankar approved these changes
Alright, Ill defer to you guys.

2023-04-06 19:56 UTC, MaheshRavishankar commented on compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
> +    "iree-codegen-llvm-enable-distribution",
Nit: I'd rather make this `disable-distribution`. We do distribution by default. So if you want to disable it you need to do something.

2023-04-06 20:33 UTC, dcaballe approved these changes

2023-04-06 20:46 UTC, merged