Add util.reinterpret and use it to preserve unsigned integer inputs/outputs
iree-org/iree pull request #13090
Opened 2023-04-14 00:15 UTC by trevor-m

Thanks so much to @rsuderman for the guidance and help !

This PR solves a bug where the signedness of inputs and outputs is lost, because lowering to linalg dialect throws the signedness away. To fix it, we added a new op, `util.reinterpret`, which casts the inputs/outputs of the function from an unsigned type to the signless type in the body.

I am completely new to IREE, so this PR is still a little rough. Any critique and suggestions for improvement is highly welcome. I'm particularly interested in ways to make this more robust.

Fixes #9282
Fixes #12665

2023-04-14 00:19 UTC, MaheshRavishankar commented
Skimmed through this (I can review more if it doesnt get reviewed). This seems fine to me. Thanks!

2023-04-14 00:27 UTC, benvanik requested changes
This has a layering violation (we can't be making the generic util dialect depend on the stream dialect). I'll need to parse through this. I feel like a tensor.bitcast would be a much better way of accomplishing this and usable from many other frontend dialects for various purposes (specifically, this has been requested for custom imports that may take tensors of various types).

2023-04-14 00:28 UTC, benvanik commented on compiler/src/iree/compiler/Dialect/Util/IR/UtilOps.cpp
> +  // TODO(trevor-m): Improve this.
this is a really dangerous op and we will need more checks on this - I'm not comfortable with the amount of errors this could lead to lower in the stack if we allow any -> any.

2023-04-14 00:48 UTC, benvanik requested changes
Yeah, I don't think we can take this as-is :/

The util dialect is a general purpose dialect used throughout all IREE transformation stages and adding ops to it implies that they are expected to function at those layers of the stack (not all do, but it's at least the goal). This op when misused will break nearly all of the analysis and optimizations we have in flow/stream. For example, copy-on-write, scheduling, and allocation won't know how to handle these. There are some cases where a reinterpret cast is useful but they should almost always be footguns that are reached for when nothing else will suffice, and in this case there are other choices we should explore first. I understand that unrealized_conversion_cast is _also_ a major footgun but I think this is just renaming the footgun instead of making it better - I'd rather have unrealized_conversion_cast than a new op we have to handle.

I think scoping the problem more to what you actually want to do (bitcast between two tensor element types) would make it safer and allow us to verify that it is properly eliminated prior to lowering further down in the stack from the ABI level. I feel like upstreaming a tensor.bitcast (effectively tensor.cast but without the requirement that the element types match, which is silly to me and maybe could be relaxed with upstream discussion) would be the best solution and if upstream doesn't want that then I'd say we should delete the entire tensor dialect as what is even the point :)

Is the primary motivation here not to have the unrealized_conversion_cast spelled like that? WrapEntryPoints should kick in far before the stream dialect and capture the type as defined on the func.func, like here where we take the type directly from the function signature: https://github.com/openxla/iree/blob/186cdd4b7abf9be5de0cd6a5e2dde273edc226d1/compiler/src/iree/compiler/Bindings/Native/Transforms/WrapEntryPoints.cpp#L418-L420

If there's a bug/that is pulling from the wrong source we should be able to fix that. I'd much prefer us find a way to make that level of the stack happy where we emit the hal.tensor.import/hal.tensor.export ops than trying to preserve this through several of the layers where it's dangerous.

2023-04-14 01:03 UTC, MaheshRavishankar commented
> This has a layering violation (we can't be making the generic util dialect depend on the stream dialect). I'll need to parse through this. I feel like a tensor.bitcast would be a much better way of accomplishing this and usable from many other frontend dialects for various purposes (specifically, this has been requested for custom imports that may take tensors of various types).

Ah missed that. Thanks for catching that.

2023-04-14 01:20 UTC, trevor-m commented
Thanks @benvanik for taking a look!

> Yeah, I don't think we can take this as-is :/
> 
> The util dialect is a general purpose dialect used throughout all IREE transformation stages and adding ops to it implies that they are expected to function at those layers of the stack (not all do, but it's at least the goal). This op when misused will break nearly all of the analysis and optimizations we have in flow/stream. For example, copy-on-write, scheduling, and allocation won't know how to handle these. There are some cases where a reinterpret cast is useful but they should almost always be footguns that are reached for when nothing else will suffice, and in this case there are other choices we should explore first. I understand that unrealized_conversion_cast is _also_ a major footgun but I think this is just renaming the footgun instead of making it better - I'd rather have unrealized_conversion_cast than a new op we have to handle.
> 
> I think scoping the problem more to what you actually want to do (bitcast between two tensor element types) would make it safer and allow us to verify that it is properly eliminated prior to lowering further down in the stack from the ABI level. I feel like upstreaming a tensor.bitcast (effectively tensor.cast but without the requirement that the element types match, which is silly to me and maybe could be relaxed with upstream discussion) would be the best solution and if upstream doesn't want that then I'd say we should delete the entire tensor dialect as what is even the point :)

Yes, `tensor.bitcast` would be perfect. The intention of `util.reinterpret` was to basically be a proxy for that since it doesn't exist yet. I didn't mean for the op to actually be Any -> Any, and I was hoping for feedback on how to properly restrict it.


> Is the primary motivation here not to have the unrealized_conversion_cast spelled like that? WrapEntryPoints should kick in far before the stream dialect and capture the type as defined on the func.func, like here where we take the type directly from the function signature:
> 
> https://github.com/openxla/iree/blob/186cdd4b7abf9be5de0cd6a5e2dde273edc226d1/compiler/src/iree/compiler/Bindings/Native/Transforms/WrapEntryPoints.cpp#L418-L420
> 
> If there's a bug/that is pulling from the wrong source we should be able to fix that. I'd much prefer us find a way to make that level of the stack happy where we emit the hal.tensor.import/hal.tensor.export ops than trying to preserve this through several of the layers where it's dangerous.

The `ConvertMHLOToLinalgOnTensors` pass converts all integers to signless, and that runs before `WrapEntryPoints`. Could we just move `WrapEntryPoints` before converting to linalg?

2023-04-14 14:15 UTC, rsuderman commented
@benvanik `tensor.bitcast` feels like exactly what the intention of `util.reinterpret` is, so if upstreaming to the `tensor` dialect seems feasible, we should do that. Validation should be that the byte behavior would be the same. E.g. `complex<f32>` would be equivalent `2xf32`, etc. Most of the issue just stems from `mlir` having no way to cast between `i32`, `si32` and `ui32`.

Lets look into upstreaming the components relate to `tensor.bitcast` and then we can merge on top of this one.

2023-05-01 19:25 UTC, trevor-m commented
Submitted LLVM patch for `tensor.bitcast`: https://reviews.llvm.org/D149608

2023-05-10 18:43 UTC, trevor-m commented
@benvanik @rsuderman @MaheshRavishankar Thanks again for all of the suggestions! `tensor.bitcast` is in and this PR is ready for re-review.

I am wondering if there is an easier/cleaner way to remove the bitcast ops as we are lowering to stream dialect, rather than having to make the RemoveBitcast matchAndRewrite.

2023-05-10 19:16 UTC, benvanik commented
I think we need to handle them like we do the other flow ops like flow.tensor.reshape - that means we'll want a flow.tensor.bitcast and then a pattern like https://github.com/iree-org/iree/blob/8f387c65f556495a4b3537161dea018f82e7ae81/compiler/src/iree/compiler/Dialect/Stream/Conversion/FlowToStream/Patterns.cpp#L48-L68 matching it.

This is because by the end of the flow dialect (before we lower into stream) we want to have all tensor shapes fully captured and no tensor dialect ops remaining (this is why there are no existing tensor->stream conversions - it's expected they've all been done already). 

If you'd like I can hack that together real quick now that tensor.bitcast is upstream and then your PR here can just add the mhlo portion. WDYT?

2023-05-10 20:58 UTC, benvanik commented
(since I have some time between meetings I'm going to plow ahead with flow.tensor.bitcast and send that out!)

2023-05-10 21:03 UTC, trevor-m commented
> (since I have some time between meetings I'm going to plow ahead ~with flow.tensor.bitcast~ and send that out)
> 
> update: forgot that flow.tensor.reshape can do what bitcast does already (and cast) - I'll just convert to that and the rest should happen automatically

Thanks Ben, that would be awesome!

2023-05-10 21:24 UTC, benvanik commented
Added in #13538 - there may still be issues hiding lower down but with your changes we can hopefully get some inputs that highlight them!

2023-05-11 18:30 UTC, trevor-m commented
> Added in #13538 - there may still be issues hiding lower down but with your changes we can hopefully get some inputs that highlight them!

Thanks Ben for helping with that!
I've fixed the remaining tests that were failing.  Could you take another pass at my changes?

2023-05-11 18:31 UTC, benvanik approved these changes
looks great!

2023-05-11 18:31 UTC, merged