Fix exportTargetAttr construction in InlineExecutablesPass.
iree-org/iree pull request #13144
Opened 2023-04-18 21:24 UTC by ScottTodd

Missed in https://github.com/openxla/iree/pull/12483, fixes https://github.com/openxla/iree/issues/12586

2023-04-18 21:24 UTC, ScottTodd commented on tests/compiler_driver/inline_static_hal_executable.mlir
> -// CHECK-NOT: hal.executable
Note: I removed `// CHECK-NOT: hal.executable` here because of attributes that remain (should they be stripped?):

```mlir
7: // -----// IR Dump After mlir::iree_compiler::`anonymous-namespace'::TraceFrameMarkEndPass () //----- //
7: #executable_target_vmvx_ir = #hal.executable.target<"vmvx-inline", "vmvx-ir", {ukernels = false}>
7: #device_target_vmvx_inline = #hal.device.target<"vmvx-inline", {executable_targets = [#executable_target_vmvx_ir]}>
7: module attributes {hal.device.targets = [#device_target_vmvx_inline]} {
7:   func.func private @simple_mul_dispatch_0_generic_4_f32(%arg0: !util.buffer, %arg1: index, %arg2: index, %arg3: index, %arg4: !util.buffer, %arg5: index, %arg6: index, %arg7: index, %arg8: !util.buffer, %arg9: index, %arg10: index, %arg11: index, %arg12: !util.buffer, %arg13: index, %arg14: index, %arg15: index, %arg16: index, %arg17: index, %arg18: index, %arg19: index, %arg20: index, %arg21: index, %arg22: index, %arg23: index, %arg24: index) {
7:     %c0 = arith.constant 0 : index
7:     %c4 = arith.constant 4 : index
7:     %c1 = arith.constant 1 : index
7:     scf.for %arg25 = %c0 to %c4 step %c1 {
7:       %0 = arith.muli %arg25, %c4 : index
7:       %1 = arith.addi %arg6, %0 : index
7:       %2 = util.buffer.load %arg4[%1 for %c4] : !util.buffer{%arg5} -> f32
7:       %3 = arith.addi %arg10, %0 : index
7:       %4 = util.buffer.load %arg8[%3 for %c4] : !util.buffer{%arg9} -> f32
7:       %5 = arith.mulf %2, %4 : f32
7:       %6 = arith.addi %arg14, %0 : index
7:       util.buffer.store %5, %arg12[%6 for %c4] : f32 -> !util.buffer{%arg13}
7:     }
7:     return
7:   }
7:   func.func private @__dispatch_simple_mul_dispatch_0_simple_mul_dispatch_0_generic_4_f32(%arg0: index, %arg1: !util.buffer, %arg2: index, %arg3: index, %arg4: index, %arg5: !util.buffer, %arg6: index, %arg7: index, %arg8: index, %arg9: !util.buffer, %arg10: index, %arg11: index, %arg12: index, %arg13: index, %arg14: index, %arg15: index, %arg16: index, %arg17: index, %arg18: index) {
7:     %c1 = arith.constant 1 : index
7:     %c0 = arith.constant 0 : index
7:     %0 = util.null : !util.buffer
7:     %1 = arith.addi %arg3, %arg13 : index
7:     %2 = arith.addi %arg7, %arg14 : index
7:     %3 = arith.addi %arg11, %arg15 : index
7:     %buffer_size = util.buffer.size %0 : !util.buffer
7:     call @simple_mul_dispatch_0_generic_4_f32(%0, %buffer_size, %c0, %buffer_size, %arg1, %arg2, %1, %arg16, %arg5, %arg6, %2, %arg17, %arg9, %arg10, %3, %arg18, %c0, %c0, %c0, %c1, %c1, %c1, %c1, %c1, %c1) : (!util.buffer, index, index, index, !util.buffer, index, index, index, !util.buffer, index, index, index, !util.buffer, index, index, index, index, index, index, index, index, index, index, index, index) -> ()
7:     return
7:   }
7:   func.func @simple_mul(%arg0: !hal.buffer_view, %arg1: !hal.buffer_view) -> (!hal.buffer_view, !hal.buffer_view) attributes {iree.abi.stub} {
7:     %c64 = arith.constant 64 : index
7:     %c0 = arith.constant 0 : index
7:     %c16 = arith.constant 16 : index
7:     %c4 = arith.constant 4 : index
7:     %c553648160_i32 = arith.constant 553648160 : i32
7:     %c1_i32 = arith.constant 1 : i32
7:     hal_inline.buffer_view.assert<%arg0 : !hal.buffer_view> message("input 0") shape([%c4]) type(%c553648160_i32) encoding(%c1_i32)
7:     %buffer = hal_inline.buffer_view.buffer<%arg0 : !hal.buffer_view> : !hal.buffer
7:     hal_inline.buffer_view.assert<%arg1 : !hal.buffer_view> message("input 1") shape([%c4]) type(%c553648160_i32) encoding(%c1_i32)
7:     %buffer_0 = hal_inline.buffer_view.buffer<%arg1 : !hal.buffer_view> : !hal.buffer
7:     %buffer_1, %storage = hal_inline.buffer.allocate alignment(%c64) : !hal.buffer{%c16} in !util.buffer
7:     %storage_2 = hal_inline.buffer.storage<%buffer : !hal.buffer> : !util.buffer
7:     %storage_3 = hal_inline.buffer.storage<%buffer_0 : !hal.buffer> : !util.buffer
7:     %buffer_size = util.buffer.size %storage_2 : !util.buffer
7:     %buffer_size_4 = util.buffer.size %storage_3 : !util.buffer
7:     call @__dispatch_simple_mul_dispatch_0_simple_mul_dispatch_0_generic_4_f32(%c4, %storage_2, %buffer_size, %c0, %buffer_size, %storage_3, %buffer_size_4, %c0, %buffer_size_4, %storage, %c16, %c0, %c16, %c0, %c0, %c0, %c16, %c16, %c16) : (index, !util.buffer, index, index, index, !util.buffer, index, index, index, !util.buffer, index, index, index, index, index, index, index, index, index) -> ()
7:     %view = hal_inline.buffer_view.create buffer(%buffer_1 : !hal.buffer)[%c0, %c16] shape([%c4]) type(%c553648160_i32) encoding(%c1_i32) : !hal.buffer_view
7:     return %view, %arg0 : !hal.buffer_view, !hal.buffer_view
7:   }
7: }
```

2023-04-19 21:37 UTC, benvanik commented on tests/compiler_driver/inline_static_hal_executable.mlir
> -// CHECK-NOT: hal.executable
we want to ensure no hal.executable op is present, so we could at least check not `hal.executable private` to skip the attribute, but yeah we should really be stripping them as they shouldn't be used after this point

2023-04-19 22:12 UTC, benvanik requested changes
see comment - we should add back the check-not and maybe file an issue (or just do the fix) for dropping those attributes once they are no longer required to avoid confusion

2023-04-19 23:08 UTC, ScottTodd commented on tests/compiler_driver/inline_static_hal_executable.mlir
> -// CHECK-NOT: hal.executable
Added those checks. Where should they be stripped? `iree-hal-inline-executables`? Here's the full IR from the test: https://gist.github.com/ScottTodd/b484fe042c53a8d216154561c0763ac7

2023-04-19 23:08 UTC, benvanik approved these changes

2023-04-20 01:28 UTC, merged