Add missing canonicalization to LLVMCPUVectorLowering
iree-org/iree pull request #13169
Opened 2023-04-19 19:00 UTC by dcaballe

I found that some canonicalization between the three stages of LLVMCPUVectorLowering are not happening. This patch adds the canonicalization stages that we have between them.

(This is another indicator that we have to split this pass into multiple ones :))

2023-04-19 19:23 UTC, MaheshRavishankar requested changes
Do we know which canonicalizations we want here? We can be more targeted then.

2023-04-19 20:35 UTC, hanhanW reviewed
Thanks for fixing it! I did not spot the regression when landing the PR. Maybe some patterns were shuffled.

2023-04-19 20:35 UTC, hanhanW commented on compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPUVectorLowering.cpp
> +  }
Do we need all the canonicalization patterns? Are canonicalization patterns of vector dialect and memref dialect enough?

2023-04-19 22:30 UTC, dcaballe commented
It's difficult to know which canonicalization pattern is missing. I added them all to see if that fixed https://github.com/openxla/iree/issues/13004 but that doesn't seem to be the case :(

At the very least, there are some canonicalization patterns from vector.transpose that are not happening between the concat and the transpose lowering and that is regressing masking.

2023-04-21 21:04 UTC, hanhanW approved these changes
LG, thanks!

2023-04-21 21:16 UTC, MaheshRavishankar approved these changes

2023-04-21 21:27 UTC, merged