Add default IREE ABI pass.
iree-org/iree pull request #13393
Opened 2023-05-03 21:51 UTC by jpienaar

Add reflection info by default if not set along *HLO and TOSA import paths. This retains the previous import path behavior that is getting deleted.

2023-05-03 22:48 UTC, benvanik requested changes
Can you drop it from tosa for now? It's only required if you're going to use the python bindings and is more of an output/runtime option than one that should be determined by the input dialect. Making it default on all paths will make it really hard to make optional in the future as tests/etc will start relying on it - today having tosa not use it keeps us honest.

It'd still be nice if we didn't require it at all - would be good at some point to confirm that it's as load bearing as assumed on the python bindings path. Ideally this would be an option we expose for hosting runtimes/users to set when they need it and if we do default it on we have a flag to strip it that is tested to work.

2023-05-03 22:48 UTC, benvanik commented on compiler/src/iree/compiler/InputConversion/MHLO/Passes.cpp
> +  passManager.addNestedPass<func::FuncOp>(createEmitDefaultIREEABIPass());
shouldn't you only need the one below?

2023-05-04 00:53 UTC, stellaraccident commented
> It'd still be nice if we didn't require it at all - would be good at some point to confirm that it's as load bearing as assumed on the python bindings path. Ideally this would be an option we expose for hosting runtimes/users to set when they need it and if we do default it on we have a flag to strip it that is tested to work.

It's useful for tooling generally as it captures enough information to form a structurally valid call. Fuzzing, testing, etc. The need was independently discovered and I saw it/mentioned that we had something like that.

2023-05-04 01:57 UTC, jpienaar commented
Updated to remove from TOSA path for now - good idea to have it be an option.

2023-10-31 17:15 UTC, ScottTodd commented
What's the status of this PR? I see it in my review queue, but it is pretty old.

2024-05-14 16:19 UTC, closed without merging

2024-05-14 16:19 UTC, benvanik commented
Closing stale PR.