Do not error on NCCL library load failure during CUDA driver creation
iree-org/iree pull request #13403
Opened 2023-05-04 01:38 UTC by sogartar

If a library symbol is not found or the NCCL library version does not match the requirements do not fail during CUDA driver creation.

2023-05-04 01:40 UTC, sogartar commented
I started a discussion here https://github.com/openxla/iree/discussions/13400

2023-05-04 16:04 UTC, benvanik requested changes

2023-05-04 16:04 UTC, benvanik commented on runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c
> +          IREE_STATUS_NOT_FOUND,
let's return UNAVAILABLE here instead so that we have a consistent status code to look for

2023-05-05 05:58 UTC, stellaraccident commented
I think this needs more of a re-organization. See my notes here: https://github.com/openxla/iree/issues/13422

2023-05-05 16:48 UTC, okkwon commented
I agree. I thought about making the nccl loading more compatible with the old version, which does not have `ncclCommInitRankConfig`, but I remembered that there were some perf improvement by tweaking the config. So let's keep the version as is.

@sogartar Do you want to make a stab? Let me know.

Note that 2.17 is not backward compatible to 2.15 because it extended the config structure, and also has a bug that makes the program hang. @trevor-m reported the issue to the NCCL team.

2023-05-05 16:52 UTC, trevor-m commented
> I agree. I thought about making the nccl loading more compatible with the old version, which does not have `ncclCommInitRankConfig`, but I remembered that there were some perf improvement by tweaking the config. So let's keep the version as is.
> 
> @sogartar Do you want to make a stab? Let me know.
> 
> Note that 2.17 is not backward compatible to 2.15 because it extended the config structure, and also has a bug that makes the program hang. @trevor-m reported the issue to the NCCL team.

I realized the config structure change is safe since nccl checks the [version](https://github.com/NVIDIA/nccl/blob/d97a32fac84f69cbd022ffdc57d5687c760742c7/src/nccl.h.in#L57) field before trying to read those new fields.
The hang issue is still remaining.

2023-05-19 17:25 UTC, okkwon commented
This is done at https://github.com/openxla/iree/issues/13422. Closing.

2023-05-19 17:25 UTC, closed without merging