Cast GPU Workgroup Address Space to generic for ukernel op
iree-org/iree pull request #13482
Opened 2023-05-09 15:59 UTC by grypp

This PR addresses an issue with the workgroup address space of inputs and outputs in the ukernel operation. By casting the Workgroup Address Space to generic address space, we can avoid an ABI mismatch that can prevent optimizations such as inlining. Microkernels are expected to be inlined, so this change should allow for inlining.

To demonstrate the problem with passing address space to ukernel function, I've included an example on Godbolt. This example shows how inlining does not work when address space is passed to ukernel. 
https://godbolt.org/z/zGTqMobcj

I've also included an example of the issue with compiling CUDA and passing `__shared__` to a function. In this case, clang simply removes `__shared__` (aka address space). 
https://godbolt.org/z/Edfhve7fb

2023-05-09 17:32 UTC, MaheshRavishankar requested changes
I think you would need to do that for any function call within the CUDA code right? Maybe have a generic cleanup of those?

2023-05-09 18:48 UTC, grypp commented
Yes you're right it is general issue. But I'm not seeing any function calls anywhere else besides the microkernel. 

Would you prefer to pass to cast address spaces instead of this fix? I thought a pass would be overkill, but I'm happy to change.

2023-05-09 18:54 UTC, MaheshRavishankar commented
> Yes you're right it is general issue. But I'm not seeing any function calls anywhere else besides the microkernel.
> 
> Would you prefer to pass to cast address spaces instead of this fix? I thought a pass would be overkill, but I'm happy to change.

Any function call within device code will have to drop the address space information... I am concerned about the GPU details leaking into non-GPU related code.

2023-05-10 13:00 UTC, grypp commented
I implemented a generic clean up pass for every CUDA function. It lives in LLVMGPU, so it does not get mixed up with generic codegen. 
See, #13518

2023-05-10 16:09 UTC, MaheshRavishankar commented
IIUC #13518 makes this PR unnecessary.

2023-05-11 14:04 UTC, closed without merging