NFC: Move two LLVMGPU passes to Common/ for sharing with SPIR-V
iree-org/iree pull request #13620
Opened 2023-05-14 21:18 UTC by antiagainst

This commit moves two LLVMGPU passes for tensor-based CodeGen pipelines, aiming to be reused for SPIR-V pieplines.

2023-05-15 00:05 UTC, ThomasRaoux approved these changes

2023-05-15 19:54 UTC, MaheshRavishankar requested changes, later dismissed
Could you wait till #13591 lands?

2023-05-15 19:59 UTC, antiagainst commented
> Could you wait till #13591 lands?

SG!

2023-05-17 15:10 UTC, antiagainst commented
@MaheshRavishankar: This is now rebased after the landed #13591.

2023-05-17 18:23 UTC, merged