Support cross_replica and cross_partition for all-to-all collective.
iree-org/iree pull request #13719
Opened 2023-05-22 17:28 UTC by trevor-m

Adds support for cross_partition which is used by all to all.
I also added helper functions to make the collective group modes selection and usage more clear.

https://github.com/openxla/iree/issues/13628

2023-05-22 17:28 UTC, trevor-m commented
cc @okkwon @benvanik

2023-05-22 23:12 UTC, okkwon requested changes
Overall looks great. I left a couple of comments.

2023-05-22 23:12 UTC, okkwon commented on compiler/src/iree/compiler/InputConversion/MHLO/ConvertCollectiveOps.cpp
> +static CollectiveOpGroupMode getCollectiveOpGroupMode(
Since we are putting all the modes here, it would be nice to have a table as documentation that shows the support modes for each collective op.

2023-05-22 23:12 UTC, okkwon commented on compiler/src/iree/compiler/InputConversion/StableHLO/ConvertCollectives.cpp
> +  if (numReplicas < 1) {
I think I made the mistake, but we should use `<=` instead of `<`. Would you mind fixing all the places?

2023-05-23 14:34 UTC, trevor-m commented
@okkwon Thank you for the review! I've just pushed an update with fixes for your comments.

2023-05-23 17:11 UTC, okkwon approved these changes
Awesome! Looks great!

2023-05-23 17:11 UTC, merged