Philox mlir-hlo to stablehlo port
iree-org/iree pull request #13844
Opened 2023-05-30 18:18 UTC by jvstokes

This ports the philox rng implementation from mhlo to StableHLO, along with tests.

2023-06-01 14:57 UTC, kuhar approved these changes
LGTM

2023-06-01 14:57 UTC, kuhar commented on compiler/src/iree/compiler/InputConversion/StableHLO/StableHLOToLinalgRandom.cpp
> +  static const int kNumRounds = 10;
nit: use constexpr

2023-06-01 15:01 UTC, kuhar commented
(I retitled the PR to match the conventions used in the other StableHLO porting work)

2023-06-01 22:53 UTC, rsuderman requested changes

2023-06-01 22:53 UTC, rsuderman commented on compiler/src/iree/compiler/InputConversion/StableHLO/StableHLOToLinalgRandom.cpp
> +    if (op.getRngAlgorithm() == mlir::stablehlo::RngAlgorithm::PHILOX) {
Include for `mlir::stablehlo::RngAlgorithm::PHILOX` case

2023-06-05 15:49 UTC, jvstokes commented
Reopening (accidentally closed due to a bad sync.)

2023-06-05 21:28 UTC, rsuderman approved these changes

2023-06-05 22:56 UTC, merged