Disable Bit-width change for modules with external functions.
iree-org/iree pull request #14114
Opened 2023-06-14 18:46 UTC by bviyer

This patch will disable bit-width changes for modules that have external functions. Since the body of the function is compiled elsewhere and just linked, any modification will cause linker issues.

2023-06-14 18:51 UTC, benvanik requested changes
This is too broad - the only thing that shouldn't be changed is the external function declarations and calls to those external functions. Disabling the entire pass should only be done with the command line flags for toggling the passes.

To do it at the appropriate scope you can gather all extern function declarations into a set and then in the FuncOp/CallOp patterns test if the target is in the set before bailing on that one particular pattern.

But really, if disabling the pass entirely works for you the best thing to do is just pass the compiler flags to disable the pass.

2023-06-16 20:08 UTC, ezhulenev reviewed
Updating `markUnknownOpDynamicallyLegal` should do it, just don't touch funcs that are external because it's unsafe.

2023-06-16 20:08 UTC, ezhulenev commented on compiler/src/iree/compiler/Dialect/Util/Transforms/ConvertPrimitiveType.cpp
> +      foundExternalFunc |= (callOp->getRegions().empty());
callOp always have no regions, you need to find referenced FuncOp. Or just walk `func::FuncOp` ops.

2024-05-14 17:22 UTC, benvanik commented
Closing stale PR.

2024-05-14 17:22 UTC, closed without merging