Add a transform to hoist unrolled vector ops out of scf.for ops.
iree-org/iree pull request #14281
Opened 2023-06-30 20:27 UTC by hanhanW

2023-06-30 21:49 UTC, dcaballe approved these changes

2023-07-03 13:37 UTC, nicolasvasilache requested changes, later dismissed
This looks like a useful extension to the existing hoisting upstream and was discussed in the past , e.g. with @ThomasRaoux .

This needs to be sliced up properly and included upstream rather than forked in IREE.

2023-07-10 18:29 UTC, hanhanW commented
> This looks like a useful extension to the existing hoisting upstream and was discussed in the past , e.g. with @ThomasRaoux .
> 
> This needs to be sliced up properly and included upstream rather than forked in IREE.

The upstream version has some [warnings](https://github.com/llvm/llvm-project/blob/1e7101a3d95884c791d566b7b6192fbac55f55e0/mlir/include/mlir/Dialect/Linalg/Transforms/Hoisting.h#L36-L37) when things happen on memrefs. I don't have enough context to structure all these transforms, and I have few patches that based on this PR. Is it okay to land it in IREE and we can upstream it later?

2023-07-10 18:36 UTC, MaheshRavishankar commented
I was going to say the same thing as Hanhan... I think it'd be great to fix all of this upstream, but we dont have the bandwidth to do that... If it helps we can file an issue (in IREE or MLIR) and tag this pass with it and a repro. I can help deprecate the pass in IREE, but we probably need to unblock this work for now.

2023-07-12 18:45 UTC, hanhanW commented
@nicolasvasilache I'd like to check in if I'm okay to land the PR to IREE?

2023-07-13 14:08 UTC, nicolasvasilache commented
> The upstream version has some [warnings](https://github.com/llvm/llvm-project/blob/1e7101a3d95884c791d566b7b6192fbac55f55e0/mlir/include/mlir/Dialect/Linalg/Transforms/Hoisting.h#L36-L37) when things happen on memrefs. I don't have enough context to structure all these transforms, and I have few patches that based on this PR. Is it okay to land it in IREE and we can upstream it later?

The message is pretty explicit that this should not be relied upon in its current form .. if you are adding load-bearing behavior on top, this feels like it is cutting through too many bad corners for my taste.

2023-07-13 16:08 UTC, stellaraccident commented
Is this tied to the issue of not using for to model actually parallel loops? (Just reading comments and pattern matching)

2023-07-13 16:15 UTC, MaheshRavishankar commented
> Is this tied to the issue of not using for to model actually parallel loops? (Just reading comments and pattern matching)

AFAICS this is all sequential loop code generation. Its a matter of hoisting some loads outside the loop.

2023-07-13 16:20 UTC, stellaraccident commented
> > Is this tied to the issue of not using for to model actually parallel loops? (Just reading comments and pattern matching)
> 
> AFAICS this is all sequential loop code generation. Its a matter of hoisting some loads outside the loop.

Ok - was trying to parse the mentioned warnings, which were about applying this to parallel.

2023-07-13 17:20 UTC, MaheshRavishankar commented
> > > Is this tied to the issue of not using for to model actually parallel loops? (Just reading comments and pattern matching)
> > 
> > 
> > AFAICS this is all sequential loop code generation. Its a matter of hoisting some loads outside the loop.
> 
> Ok - was trying to parse the mentioned warnings, which were about applying this to parallel.

If I look at the PR, its mostly about  hoisting `vector.extract_strided_slice` and `vector.insert_strided_slice`. This came up when we were trying to move the existing CUDA pipeline for targeting tensor cores to use tensor based codegen instead of memref based codegen (which is what it does currently).

2023-08-29 22:28 UTC, hanhanW commented
I have an upstream patch: https://reviews.llvm.org/D159144

2023-10-13 18:17 UTC, hanhanW commented
> I have an upstream patch: https://reviews.llvm.org/D159144

It's not reviewed yet, and we are moving review process to Github PR. I prefer landing this PR firstly to unblock other work, and I will work on upstreaming later.

2023-10-13 21:31 UTC, merged