Sample: custom riscv32 bitcode for the mmt4d ukernel
iree-org/iree pull request #14496
Opened 2023-07-26 21:20 UTC by bjacob

This shows how to develop out-of-tree custom bitcode for the standard mmt4d ukernel, here for the riscv32 architecture.

I haven't been able to test locally, so there might be a bug. At least, it builds, and the disassembly seems sane.

@lundong @hcindyl

2023-07-26 21:32 UTC, benvanik requested changes
nice!

2023-07-26 21:32 UTC, benvanik commented on samples/ukernel_mmt4d_riscv_32/CMakeLists.txt
> +iree_add_all_subdirs()
not sure if you plan to land this or just treat it as an example PR, but if landing you'll want to predicate all this on whether the cpu backend is enabled and probably some other things - something like

```
iree_compiler_targeting_iree_arch(_IREE_COMPILER_TARGETING_RISCV_32 "riscv_32")
if(NOT IREE_TARGET_BACKEND_LLVM_CPU OR
   NOT _IREE_COMPILER_TARGETING_RISCV_32 OR
   NOT IREE_HAL_DRIVER_LOCAL_TASK OR
   NOT IREE_HAL_EXECUTABLE_LOADER_EMBEDDED_ELF)
  return()
endif()
```

2023-07-26 21:32 UTC, benvanik commented on samples/ukernel_mmt4d_riscv_32/CMakeLists.txt
> +iree_add_all_subdirs()
let's throw this under `samples/custom_dispatch/cpu/ukernel/mmt4d/` so we have one place for these (I'd like to rework the other samples to show ukernels mixed in as well, and it'll give us a place to put other examples as well)

2023-07-27 01:18 UTC, bjacob commented on samples/ukernel_mmt4d_riscv_32/CMakeLists.txt
> +iree_add_all_subdirs()
yeah this was not meant for landing -- stripped this kind of boilerplate to make this minimal.  agree we readd it if landing.

2023-11-28 20:17 UTC, closed without merging