Turn off GCC warning for llvm/include/ADT/DenseMap.h
iree-org/iree pull request #14672
Opened 2023-08-15 01:19 UTC by hcindyl

GCC can't detect the union casting properly and report incorrect warnings.

Turn off the warning when build with non-Windows GNU GCC

ci_extra: build_test_all_windows

2023-08-15 01:19 UTC, benvanik requested changes
I still don't want this in the codebase - please disable your use of this warning or fix it upstream.

2023-08-15 01:23 UTC, hcindyl commented
> I still don't want this in the codebase - please disable your use of this warning or fix it upstream.

I tried several ways to "fix" this upstream but GCC was just happy.

If we disable the warning upstream it will be with the same `#if !defined(_MSC_VER) #pragma GCC ...` syntax.

2023-08-15 01:24 UTC, benvanik commented
I'd rather have that in the code that has the issue than in a downstream project - or don't use that warning. We really can't be guarding all upstream headers with all compilers entire suite of warnings - every compiler plugin including these files would also need this, etc.

2023-08-15 01:27 UTC, hcindyl commented
We can update https://github.com/openxla/iree/blob/72995e1bc2b34755dbcddc49ebbd81c8ce7736ea/build_tools/cmake/iree_copts.cmake#L209 to turn off the erroneous `-Wmaybe-uninitialized` warning (see https://github.com/openxla/iree/issues/14507#issuecomment-1677929421). However, @ScottTodd wanted to limit the scope of the flag setting

2023-08-15 01:29 UTC, benvanik commented
If the flag is buggy and triggering on things that are unfixable then we should disable it - we've got other compilers we can get that coverage on.

2023-08-15 16:02 UTC, ScottTodd approved these changes

2023-08-16 17:42 UTC, benvanik approved these changes

2023-08-16 17:43 UTC, merged