Support scalable tile sizes in #iree_codegen.lowering_config
iree-org/iree pull request #15033
Opened 2023-09-25 16:10 UTC by MacDue

This extends the lowering config so that at each level tiles can be marked as scalable using an optional array of bools. The parser/printer has been updated to display this in the canonical MLIR syntax (i.e. the size wrapped in square brackets).

So for example, this lowering config:

```
  #iree_codegen.lowering_config<tiling_levels
	= [[128, 128, 0], [1, [32], 0], [0, 0, 1], [0, 0, 0]]>
```

Means that the middle tile size (32) of the second tiling level is scalable.

These are not yet used, but will be in subsequent patches.

Depends on #15032 (which is the first commit in this PR)

2023-09-25 16:10 UTC, MacDue commented
cc @banach-space, @dcaballe

2023-09-25 16:53 UTC, MacDue commented
An alternate syntax could be something like:
```
  #iree_codegen.lowering_config<tiling_levels
	= [[128, 128, 0], [1, 32 x vscale, 0], [0, 0, 1], [0, 0, 0]]>
```
Which _is_ less consistent with MLIR in general, but I personally find easier to read.

2023-09-26 18:54 UTC, dcaballe commented
Thanks. It looks good to me in general. I would be consistent with the MLIR representation for scalable vectors (i.e., `[4]`). I would keep the `tile_sizes` keyword, though, to minimize the impact of the change.

2023-09-26 19:38 UTC, banach-space commented
LGTM, very non-intrusive and consistent with what we have in MLIR, thanks for working on this!

> I would keep the tile_sizes keyword, though, to minimize the impact of the change.

+1

2023-09-27 09:18 UTC, MacDue commented
> Thanks. It looks good to me in general. I would be consistent with the MLIR representation for scalable vectors (i.e., `[4]`). I would keep the `tile_sizes` keyword, though, to minimize the impact of the change.

The `tiling_levels` change is from #15032 (the parent PR), and I think makes sense in context. TLDR is the `lowering_config` has been restructured, so it takes a list of `LoweringConfigLevelAttrs`s, rather than multiple nested arrays. The lowing config level contains both the sizes and interchange (and with the PR, the scalable size flags). It is just a custom assembly format that makes the "no tile interchange" case look like the previous syntax.

2023-09-29 08:37 UTC, MacDue commented
Rebased following merge of https://github.com/openxla/iree/pull/15032.

2023-09-29 18:52 UTC, MaheshRavishankar requested changes
Just a few clarifying questions. Is the intent here to just represent a tiling level as scalable, or does the value within `[ ..]` matter? If it is the former, wouldnt it be better if it is a boolean (or a list of boolean) that indicates whether the vector is scalable or not.
Also I am missing reasoning as to why the tile sizes at a particular level (that have to do with things like distribution, cache locality etc.) need to be mapped to which vector dimension is scalable on the hardware... Those dont seem to be coupled.

2023-09-29 21:59 UTC, dcaballe approved these changes
Thanks

2023-09-29 22:12 UTC, dcaballe commented
> Just a few clarifying questions. Is the intent here to just represent a tiling level as scalable, or does the value within `[ ..]` matter? If it is the former, wouldnt it be better if it is a boolean (or a list of boolean) that indicates whether the vector is scalable or not. Also I am missing reasoning as to why the tile sizes at a particular level (that have to do with things like distribution, cache locality etc.) need to be mapped to which vector dimension is scalable on the hardware... Those dont seem to be coupled.

(Replying to try to expedite the review while Europe is going over the weekend.)

Scalable vectors need a base vector size, which is the value between the brackets. That means that the vector size will be a multiple of that base and not any other random value.

Scalable vectors at distribution or cache levels don't make sense but given the current open definition of lowering config, it would be up to the consumer to validate that, I guess. On the CPU side, we can use `TilingConfig` to verify so. At the vector level, we only use a scalable size for the dimension that we know will *actually* be vectorize (i.e., mapped to a scalable vector in hw) when we lower the vector from n-D to 1D. It wouldn't make sense to use a scalable vectors for the unrolled dimensions although I guess it could be supported by just unrolling to the base size (?).

Hopefully that help!

2023-09-29 22:43 UTC, MaheshRavishankar approved these changes
Thanks for the clarification

2023-09-30 00:58 UTC, merged