Enable data tiling for llvm-cpu and vmvx by default.
iree-org/iree pull request #15215
Opened 2023-10-17 15:37 UTC by hanhanW

2023-10-17 17:03 UTC, bjacob commented on compiler/src/iree/compiler/Codegen/Common/CPU/CPUMaterializeEncodingPass.cpp
> +  // supported?
In itself, that would be a fair thing to do.  But doing so would effectively require duplicating this logic in SetEncoding. So I think what you have in the current state of this PR --- just default to some vaguely sane tile size --- is the sane thing to do.  Even an imperfect data-tiling size is likely to allow data-tiling to improve performance thanks to memory locality.

2023-10-17 17:03 UTC, bjacob commented on compiler/src/iree/compiler/Codegen/Common/CPU/CPUMaterializeEncodingPass.cpp
> +  return MatmulTileParams{8, 4, 8};
Same comment as above; probably should do 8, 1, 8 rather than 8, 4, 8 though.

Probably a good time now to also switch the tile size in chooseMatmulTileParamsGeneric (above in this file) to 8, 1, 8.

2023-10-17 17:03 UTC, bjacob commented on compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPULowerToUKernels.cpp
> +  if ((lhs.isF32() && rhs.isF32() && out.isF32()) ||
I'm sorry to ask you to do more work to maintain this little-used path, but could we avoid conflating I32 into F32 here? It just seems accidental that we have tests that exercise the rather academic i32i32i32 case.  Just switch them to either i8i8i32 or f32f32f32 ?

2023-10-17 18:05 UTC, dcaballe requested changes
I don't think data tiling is ready for a default enablement yet. We are hitting compilation and runtime issues mostly on every new model we try and we are also observing performance degradations in some cases (17% slowdown in one internal model, for example). Also targets like RISC-V will have significant regressions. I think a more incremental approach would work better but, in any case, this is something that needs an RFC and further discussion.

2023-10-17 18:27 UTC, hanhanW commented
> I don't think data tiling is ready for a default enablement yet. We are hitting compilation and runtime issues mostly on every new model we try

We will need an RFC for sure! This is mostly creating for prefetching issues and rolling out discussion. Thanks for raising the issues. So far the functionality is well for all the external models. Do you mind share the issues and models you've tried with me? I can help look into some if there are needs.

> we are also observing performance degradations in some cases (17% slowdown in one internal model, for example). 

Just for note, data tiling is for getting a reasonable baseline, but not peak performance for all the models. We definitely want to address 17% slowdown if they are reasonable. It is good if we can have a perf breakdown and learn more about where the regression come from.

> Also targets like RISC-V will have significant regressions. I think a more incremental approach would work better but, in any case, this is something that needs an RFC and further discussion.

RE RISC-V: is there a plan or timeline about enabling data tiling on RISC-V? Will it be a blocker for turning data tiling on by default for CPU backends?

2023-10-17 18:55 UTC, banach-space commented
I would also like to better understand the impact before this lands -  an RFC would be much appreciated :)

IIRC, data tiling is directly related to u-kernels? However, that's unlikely to become the default lowering path for us.  So changing the default would be taking IREE in the opposite direction compared to how we intend to use it. But perhaps I am missing something?

Also, we are in the process of ramping up support for scalable vectors and from my experience there's always quite a lot of code that assumes fixed-width vectors. So, changing the default will potentially have a huge impact on us. An incremental approach (or opt-in) would be much easier to adapt to 🙏🏻 .

Again, I might be misinterpreting things. An RFC would help :)

2023-10-17 18:59 UTC, hanhanW commented
Thanks for the input, I will prepare the RFC and send it out!

2023-10-17 19:01 UTC, bjacob commented
> IIRC, data tiling is directly related to u-kernels?

Data-tiling can be used without ukernels. In some cases, data-tiling alone can enable default codegen to find the better vectorization, thanks to the hand-picked tile sizes.  So "data-tiling but not ukernels" is a very realistic path.

On the other hand, ukernels are not currently used without data-tiling. There's nothing in itself with the general ukernels-rewrite pass that requires data-tiling, it's just that the ops currently matched and rewritten in that pass are ops that are typically created by data-tiling. Concretely, that means we have a ukernel for a data-tiled matmul, but not for a row-major matmul.

2023-10-17 20:15 UTC, MaheshRavishankar commented
Thanks @hanhanW for the RFC. Let me give a bit of my thinking as to why we should turn this on by default (ill duplicate this on the RFC as well)
1) We've long had issues with performance (and compilation time issues) on the non-data tiling path. It has been stuck in a really bad place, where it is hard to improve, is not working as well across the breadth of benchmarks. The data tiling path was explored to get out of this rut. It would be really unfortunate for people trying out IREE to get really poor performance out of the box, and having to use a "soup of flags" to bump up performance. From my view point, the data tiling path is less susceptible to lowering config changes, has better out of box performance on ARM and x86 in general, and has more leg room for improvement. 
2) The flags that are flipped here are still around. If things cause regressions, then those can be locally flipped to get back the original state... we still have CI running both the data tiling path and the non-data tiling path. Those will make sure these paths are lit up and tested. If there are any concerns here, happy to discuss further.
3) Any crashes currently will have to be fixed before the flip, but crashes on the data tiling path after the flip will effectively be P0 bugs.
4) It is unreasonable to expect any code path will be the "best performant everywhere". We need to look at average performance across various use cases, and there it is pretty clear that the data tiling path is much better. Any regressions will need to be addressed, but no regressions cannot be a metric for flipping the flag.
5) I think it puts the CPU backend in overall a better state. We have been long wanting to deprecate the "pad + hoist" path for matmul codegen. Previous attempts to this and replace it with masked vectorization + multi-level tiling has not worked out cause of regressions (though I had previously said that I would be fine with regressions there too just for the pure win in terms of removing an extremely complicated and fragile path). With this flip, data tiling will be taking over as being load-bearing and can enable the multi-level tiling + masked vectorization path to land (I tried this out previously was pretty happy the way it worked. we should use it for data-tiling path as well).

2023-10-18 00:57 UTC, mariecwhite commented
Do you mind adding `pull_request` as a trigger in `benchmark_large.yml` so that those benchmarks run with this change.

2023-10-18 17:35 UTC, hanhanW commented
> Do you mind adding `pull_request` as a trigger in `benchmark_large.yml` so that those benchmarks run with this change.

I'm not familiar with benchmark setting, can you guide me with a concrete action, like adding something to where? Thank you!

2023-10-19 01:18 UTC, mariecwhite commented
> > Do you mind adding `pull_request` as a trigger in `benchmark_large.yml` so that those benchmarks run with this change.
> 
> I'm not familiar with benchmark setting, can you guide me with a concrete action, like adding something to where? Thank you!

Add the line `pull_request:` under https://github.com/openxla/iree/blob/main/.github/workflows/benchmark_large.yml#L12 and include it in the PR. This should automatically run these benchmarks with your PR.

2023-10-19 19:47 UTC, bjacob commented
https://github.com/openxla/iree/issues/15241 might be seen as blocking this.

2023-11-07 18:59 UTC, hanhanW commented
Moving to https://github.com/openxla/iree/pull/15256

2023-11-07 18:59 UTC, closed without merging