Add support of vecmat/matvec in SetEncoding and MaterializeEncoding
iree-org/iree pull request #15257
Opened 2023-10-20 23:45 UTC by NatashaKnk

This PR is currently broken as it relies on [68945](https://github.com/llvm/llvm-project/pull/68945).

This implementation is by no means elegant. The vectors being passed into `MaterializeEncoding` without being expanded first require several plugs in multiple operations, since most of them try to pack the tensors directly (or at least infer the shape after packing). Thus, the shapes post-expansion need to be inferred outside the `vecmat`/`matvec` op lowering itself. This also requires a surprising amount of utility ops to calculate.
In addition, this approach creates the issue that since we are first padding, then expanding, and then packing -- the pad+pack ops don't get folded into pack.

Expanding the tensors in `SetEncoding` would elliminate most of the lack of elegance (but add some of it back in there, so this is not a perfect soultion by any means), but it does introduce unneccesary expansions earlier in the stack as discussed in [15053](https://github.com/openxla/iree/issues/15053). There might be a different approach to this that I haven't considered, so feedback is appreciated.

2023-10-21 00:53 UTC, hanhanW requested changes
The PR is quite large. Can we break it down? E.g., I think at least we could have one PR adding materialization patterns, and the other for set_encoding.

2023-10-21 00:53 UTC, hanhanW commented on llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/MaterializeEncoding.cpp
> +    return chooseEncodingInfoForMatmul(user, role, /*tileParams=*/{8, 4, 1});
This part is mostly for testing. To enable it on CPU backend, you need to add configurations to CPUMaterializeEncodingPass

https://github.com/openxla/iree/blob/3323519bad0f2b91532a8272234034920101709b/compiler/src/iree/compiler/Codegen/Common/CPU/CPUMaterializeEncodingPass.cpp#L47-L148

(I'm sorry about the structure and I will centralize the code)

2023-10-21 00:53 UTC, hanhanW commented on compiler/src/iree/compiler/GlobalOptimization/SetEncoding.cpp
> +    }
We can do the trick like this:

https://github.com/tensorflow/mlir-hlo/blob/b3eeedc11c3f5a708a4847d211bf1f4fc738683e/mhlo/transforms/legalize_to_linalg/legalize_to_linalg.cc#L3825-L3841

2023-10-21 00:53 UTC, hanhanW commented on llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/MaterializeEncoding.cpp
> +  return resultOp;
Can we use switch-case here? It's cleaner and easier for maintenance.

2023-10-21 00:53 UTC, hanhanW commented on llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Utils/EncodingUtils.cpp
> +int64_t getExpandedDimIndex(EncodingAttr encoding) {
please add a doc. What happen if it returns `-1`?

2023-10-23 11:00 UTC, bjacob commented
Sorry that I failed to mention this possibility earlier, but:

One simple approach would be to rewrite `linalg.matvec` by expanding the shape (`tensor.expand_shape`) of the vector operand, into a `linalg.matmul`.  And likewise for `linalg.vecmat`. I think the mental barrier that prevented me from suggesting that earlier was I wondered if the inserted `tensor.expand_shape` ops would be unwanted for some reason, but now seeing that the current approach is resulting in a substantial amount of code, I wonder if it's time to give a closer look to the `expand_shape` approach instead?  Sorry again for not bringing this up earlier.  OK to carry on with the current approach if there's a significant problem with the `expand_shape` approach.

2023-10-23 17:07 UTC, NatashaKnk commented
@bjacob I think this is on me for not advocating for it a bit harder once I saw the amount of work it took, since I considered it. Where do you think this would fit best, while setting the encoding or elsewhere?

2023-10-23 19:13 UTC, bjacob commented
> @bjacob I think this is on me for not advocating for it a bit harder once I saw the amount of work it took, since I considered it. Where do you think this would fit best, while setting the encoding or elsewhere?

I think it definitely is nice to have it be its own separate pattern+pass -- this is quite generally useful to have, and reviewers tend to like reusable composable patterns that do one thing each. You could initially create it as its own new pattern/pass in GlobalOptimization/ side by side with SetEncoding. Then if a reviewer thinks it belongs elsewhere, that should be easy to move.

2023-10-24 16:24 UTC, closed without merging