Package tools directory in CI
iree-org/iree pull request #15561
Opened 2023-11-12 22:38 UTC by mariecwhite

We plan to download builds in IREE post-submit CI runs from `openxla-benchmark`. We only require the `tools` directory so archive this and upload instead of using the full build archive which is ~8GB.

2023-11-13 00:03 UTC, pzread commented
I think we have PkgCI to build and upload installable python packages for each commit on the main branch: https://github.com/openxla/iree/blob/main/.github/workflows/pkgci_build_packages.yml

You can find the Github artifact of the package here: https://github.com/openxla/iree/actions/runs/6834338004, and Github also provides API to get the artifact link: https://docs.github.com/en/rest/actions/artifacts?apiVersion=2022-11-28#about-artifacts-in-github-actions

2023-11-13 00:33 UTC, mariecwhite commented
Thanks for the pointers. These are the python versions which are useful for running `iree-compile` but I also need to get the cross-compiled versions of `iree-benchmark-module` as native binaries. Here is what I was planning to do in `openxla-benchmark`:

1. Retrieve the latest CI artifact dir by querying `gs://iree-github-actions-postsubmit-artifacts`.
2. From that GCS directory, download the tools dir archive (generated from this CL) and the benchmark-tools archives that have been cross-compiled for Android and x86_64.

With this method, we can ensure that the tools are from the same CI run and no version skew occurs.

2023-11-13 16:00 UTC, ScottTodd requested changes
CI outputs are an implementation detail of this project. Downstream should either build from source itself or use the package releases.

2023-11-13 19:21 UTC, mariecwhite commented
Can we add the tools in native binary form (instead of Python bindings) and the cross-compiled variants to the releases?

2023-11-13 19:26 UTC, ScottTodd commented
> Can we add the tools in native binary form (instead of Python bindings) and the cross-compiled variants to the releases?

Some binary tools are available in the "iree-dist" (e.g. `iree-dist-20231113.707-linux-x86_64.tar.xz`) release assets. Cross-compiling tools like `iree-benchmark-module` is trickier, since we can't really enumerate all possible configurations that downstream users may be interested in. The runtime binaries should be quite fast to build though, so the main reason to use prebuilt binaries is infrastructure complexity.

2023-11-14 16:52 UTC, ScottTodd commented
Thinking about this some more...

* https://github.com/iree-org/iree-template-runtime-cmake/blob/main/.github/workflows/build-and-test.yml is a good reference for building the runtime tools from source in another repository using GitHub Actions. Some extra steps for setting up cross compilation (e.g. configure Android SDK/NDK) would be needed. 
* For benchmarking specifically, you may want to precisely define the compilation flags on various tools, e.g. `-DCMAKE_BUILD_TYPE=RelWithDebInfo` -> `-DCMAKE_BUILD_TYPE=Release`, enable/disable tracing, enable/disable assertions. We can pick reasonable defaults upstream, but I wouldn't want to couple the build flags across different projects too closely.
* We could build something upstream in this repository for downstream benchmark runners to use, but I'd want it to be separate from the standard CI workflows. It _could_ be part of the ci.yml _benchmark_ workflows like `build_benchmark_tools`, perhaps.
  * I'd still rather have downstream workflows use releases in some form, rather than incidental uploads from CI workflows. All sorts of events can trigger CI runs and upload/download from cloud storage, and packages are the official way to interact with the project.

2023-11-14 19:40 UTC, mariecwhite commented
That makes sense. I'll rebuild IREE in `openxla-benchmark`.

2024-05-14 16:07 UTC, ScottTodd commented
Closing some old PRs. Consensus was to rebuild from source or use releases.

2024-05-14 16:07 UTC, closed without merging