Fix accidental data-tiling of unsupported mixed integer/float matmuls
iree-org/iree pull request #15766
Opened 2023-12-01 15:36 UTC by bjacob

Fixes #15760

2023-12-01 18:15 UTC, hanhanW requested changes

2023-12-01 18:15 UTC, hanhanW commented on compiler/src/iree/compiler/Codegen/Common/CPU/CPUMaterializeEncodingPass.cpp
> -            TileMxNxK{1, 128, 1}, // Use half the number of accumulators.
The logic about ukernel and non-ukernel tile size selection is gone, should we add them back?

2023-12-01 18:24 UTC, bjacob commented on compiler/src/iree/compiler/Codegen/Common/CPU/CPUMaterializeEncodingPass.cpp
> -            TileMxNxK{1, 128, 1}, // Use half the number of accumulators.
oops! bad rebase, sorry.

2023-12-04 14:41 UTC, dcaballe approved these changes
LGMT! Could we fix the rebase and land, please? Waiting for this to run benchmarks

2023-12-04 16:10 UTC, bjacob commented on compiler/src/iree/compiler/Codegen/Common/CPU/CPUMaterializeEncodingPass.cpp
> -            TileMxNxK{1, 128, 1}, // Use half the number of accumulators.
Fixed, thanks again for the good catch. PTAL.

2023-12-04 18:06 UTC, hanhanW approved these changes
LGTM, thanks!

2023-12-04 18:27 UTC, merged