[Flow] Relax dynamic shape restrictions on slice -> Flow patterns
iree-org/iree pull request #15861
Opened 2023-12-08 20:13 UTC by qedawkins

Dynamic offsets/strides/sizes can come from values expected to later live either on the host or the device. If it is a dynamic value known at command buffer setup time (e.g. a loop iterator) we should not block on converting dynamic slices to flow ops.

2023-12-08 20:15 UTC, qedawkins commented on compiler/src/iree/compiler/Dialect/Flow/Conversion/TensorToFlow/Utils.cpp
> +    if (isa<tensor::ExtractOp, TensorLoadOp>(op)) {
I'm not sure what a good way to determine that something will require a host-device roundtrip for a single index value is. This makes some sense to me? But also feels very special case-y.

2023-12-12 18:47 UTC, benvanik requested changes

2023-12-12 18:47 UTC, benvanik commented on compiler/src/iree/compiler/Dialect/Flow/Conversion/TensorToFlow/test/insert_slice.mlir
> +// CHECK-LABEL: func.func @insert_slice_convert
use full name on match

2023-12-12 18:47 UTC, benvanik commented on compiler/src/iree/compiler/Dialect/Flow/Conversion/TensorToFlow/test/insert_slice.mlir
> +//  CHECK-SAME:   %[[ARG0:[a-zA-Z0-9_]+]]
if capturing named things it's a good idea to name them - so %arg0 should be %target_tensor / %[[TARGET_TENSOR]], etc

2023-12-12 18:47 UTC, benvanik commented on compiler/src/iree/compiler/Dialect/Flow/Conversion/TensorToFlow/test/insert_slice.mlir
> +    (%arg0 : tensor<?x24x48xf32>, %arg1 : tensor<1x?x48xf32>, %offset : index, %size : index) ->
function style is (%arg0: tensor<..>, %arg1: tensor<...>) (no spaces between arg name and type)

2023-12-12 18:47 UTC, benvanik commented on compiler/src/iree/compiler/Dialect/Flow/Conversion/TensorToFlow/test/insert_slice.mlir
> +  %c0 = arith.constant 0 : index
c0 not used?

2023-12-12 18:47 UTC, benvanik commented on compiler/src/iree/compiler/Dialect/Flow/Conversion/TensorToFlow/test/insert_slice.mlir
> +  // CHECK-NOT: flow.tensor.update
what is it supposed to be? it's a good idea to CHECK-NOT what you don't want and CHECK what you do in cases where something else is produced instead. is it assumed to be tensor.insert_slice still?

2023-12-20 22:15 UTC, benvanik approved these changes

2023-12-20 23:25 UTC, merged