[HIP] Adds support for creating devices
iree-org/iree pull request #15887
Opened 2023-12-12 00:29 UTC by nithinsubbiah

Progress towards #15790

2023-12-12 04:32 UTC, antiagainst requested changes

2023-12-12 04:32 UTC, antiagainst commented on experimental/hip/hip_device.c
> +#include <iree/hal/device.h>
This include is not needed.

2023-12-12 04:32 UTC, antiagainst commented on experimental/hip/hip_device.c
> +  memset(device, 0, total_size);
This is not needed actually--if you look at `iree_allocator_malloc`, it calls into the `CALLOC` variant, which will zero the allocation along the way. Feel free to fix the cuda2 side too.

2023-12-12 04:32 UTC, antiagainst commented on experimental/hip/hip_device.c
> +        symbols, hipSetDevice(IREE_HIPDEVICE_TO_DEVICE_ID(device)));
From the [API](https://docs.amd.com/projects/HIP/en/latest/.doxygen/docBin/html/group___device.html#ga43c1e7f15925eeb762195ccb5e063eae), `hipSetDevice` expects an `int` device index right? `hipDevice_t` is queried from `hipGetDevice` with a device index. Doc doesn't say `hipDevice_t` is just device index under the hood; so we cannot assume so. (Better to ask internally regarding this.) Therefore we may additionally need to keep track of the given device's index in its struct. Also, `IREE_HIPDEVICE_TO_DEVICE_ID` is not necessary here given that converts the `device` to an ID used in IREE.

2023-12-12 04:32 UTC, antiagainst commented on experimental/hip/hip_device.c
> +    // WARNING: This function return hipSuccess though doesn't release the
Change WARNING to Note would be fine.

2023-12-12 04:32 UTC, antiagainst commented on experimental/hip/hip_device.c
> +  // WARNING: This function return hipSuccess though doesn't release the
Similarly here.

2023-12-12 04:37 UTC, antiagainst commented
The lastest API doc marks the majority of the context management APIs as [deprecated](https://rocm.docs.amd.com/projects/HIP/en/latest/.doxygen/docBin/html/group___context_d.html#ga8aa32cf64272da929f23ecbafefefcee), with some exceptions like `hipDevicePrimaryCtxRetain`. Not sure that's intentional or just a bug in the doc. Could you ask internally to clarify regarding this aspect? And also regarding primary context management (is it really needed with `hipDevicePrimaryCtxRelease` doing nothing?) And what is the expected way to manage context in general, with a bunch of APIs deprecated without telling what to use instead?

2023-12-12 19:39 UTC, nithinsubbiah commented
> The lastest API doc marks the majority of the context management APIs as [deprecated](https://rocm.docs.amd.com/projects/HIP/en/latest/.doxygen/docBin/html/group___context_d.html#ga8aa32cf64272da929f23ecbafefefcee), with some exceptions like `hipDevicePrimaryCtxRetain`. Not sure that's intentional or just a bug in the doc. Could you ask internally to clarify regarding this aspect? And also regarding primary context management (is it really needed with `hipDevicePrimaryCtxRelease` doing nothing?) And what is the expected way to manage context in general, with a bunch of APIs deprecated without telling what to use instead?

You're right that most context API's are deprecated except a handful like `hipDevicePrimaryCtxRetain`, `hipDevicePrimaryCtxRelease` (https://docs.amd.com/projects/HIP/en/latest/.doxygen/docBin/html/group___context.html)

As for the reasoning and ways to manage context going forward, the documentation recommends using stream and device APIs. 

<img width="931" alt="Screenshot 2023-12-12 at 11 33 49 AM" src="https://github.com/openxla/iree/assets/18070964/e4aad030-d555-43d9-9e7a-95d384823d10">

2023-12-12 19:43 UTC, benvanik commented
yeah we don't want the runtime API - it adds extra baggage - sounds like they just want people to use that in HIP land vs actually having deprecated things?

2023-12-12 20:11 UTC, nithinsubbiah commented
Yeah, that's my understanding. I had to use `hipSetDevice` (https://docs.amd.com/projects/HIP/en/latest/.doxygen/docBin/html/group___device.html#ga43c1e7f15925eeb762195ccb5e063eae) from the runtime API to steer clear of the deprecated Ctx API

2023-12-12 20:15 UTC, benvanik commented
yeah we don't want that, so we'll want to go back to the context ones (they can never remove those, so it's not deprecated in the sense of "don't use these because they won't work/will be removed)

2023-12-13 00:12 UTC, nithinsubbiah commented
I've replaced the device call with context. I'll follow up internally on these "deprecated" context API calls to make sure they're supported in future releases

2023-12-13 03:01 UTC, antiagainst commented
> yeah we don't want the runtime API - it adds extra baggage - sounds like they just want people to use that in HIP land vs actually having deprecated things?

[Per the doc](https://rocm.docs.amd.com/projects/HIP/en/docs-5.6.0/user_guide/hip_porting_driver_api.html#hip-module-and-ctx-apis), in HIP there is no clear separation of driver vs runtime APIs. So I suspect we might be seeing the runtime API (in CUDA's sense) overhead in HIP anyway. From the doc it seems `Ctx` APIs are just sugar over other APIs, but there are always suprises. :) Worth digging into the details and pick folks' brains internally to understand in depth. @nithinsubbiah please make sure this is tracked and investigated.

2023-12-13 03:02 UTC, antiagainst approved these changes

2023-12-13 03:02 UTC, antiagainst commented on experimental/hip/dynamic_symbol_tables.h
> +IREE_HIP_PFN_DECL(hipSetDevice, int)
This is not used and can be removed now?

2023-12-13 03:02 UTC, merged