[GlobalOpt][CPU] Move to using indexing maps for data tiling encodings instead of named op enums
iree-org/iree pull request #15984
Opened 2023-12-20 17:24 UTC by Max191

This PR adds an `indexing_maps` attribute to `linalg_ext.encoding`, and uses this attribute in MaterializeEncoding in place of the case-by-case enums for matmul and batch_matmul. This will enable data tiling on transposed matmul cases like `linalg.matmul_transpose_a`, and is a step towards data-tiling of `linalg.generic` contraction ops.

In SetEncoding, the `indexing_maps` attribute is set, containing the indexing maps of the LHS, RHS, and RESULT of the op to be data-tiled. The case-by-case checks are removed by this PR, and transposed `linalg::ContractionOpInterface` ops are allowed to get encodings. The `MATMUL` and `BATCH_MATMUL` user encodings are kept for now, but can eventually be removed.

In MaterializeEncoding, the `indexing_maps` are used to infer the contraction dimensions (M, N, K, Batch) of the inputs, and a `tensor.pack` op is created with appropriate `inner_dims_pos` and `outer_dims_perm` to transpose and pack the input into the canonical `linalg.mmt4d` input shapes.

2023-12-20 17:28 UTC, Max191 commented
This PR needs https://github.com/llvm/llvm-project/pull/76081

2023-12-20 17:30 UTC, Max191 commented
I still need to add tests for the transposed flavors of linalg.matmul and linalg.batch_matmul, but the existing cases are working.

2024-01-02 23:47 UTC, hanhanW requested changes
Really nice work! I think we will need a few cleanups after landing the change:

1. Remove EncodingUser.
2. Remove ContractionOpType enum struct.

2024-01-02 23:47 UTC, hanhanW commented on compiler/src/iree/compiler/Codegen/Common/EncodingUtils.h
> +///
please add a doc

2024-01-02 23:47 UTC, hanhanW commented on compiler/src/iree/compiler/Codegen/Common/EncodingUtils.cpp
> +AffineMap getMapForRole(EncodingAttr encoding) {
nit: we should add `static` keyword to the method.

2024-01-02 23:47 UTC, hanhanW commented on compiler/src/iree/compiler/Codegen/Common/EncodingUtils.cpp
> +getEncodingContractionDims(EncodingAttr encoding) {
nit: we should add `static` keyword to the method.

2024-01-02 23:47 UTC, hanhanW commented on compiler/src/iree/compiler/Codegen/Common/EncodingUtils.cpp
> +unsigned getResultIndex(AffineMap m, int64_t idx) {
nit: we should add `static` keyword to the method.

2024-01-02 23:47 UTC, hanhanW commented on compiler/src/iree/compiler/Codegen/Common/EncodingUtils.cpp
> +  }
This comment can be a follow-up.

One of the goals is to remove `EncodingUser` from encodings. Are we able to just check if `cDims->batch[0]` is not empty?

Also, do we still need the check for vecmat and matvec? Ideally, we can get the information from indexing_maps?

2024-01-02 23:47 UTC, hanhanW commented on compiler/src/iree/compiler/GlobalOptimization/SetEncoding.cpp
> +  //   return ContractionOpType::kBatchMatvec;
please delete the comments. :)

2024-01-04 21:56 UTC, hanhanW approved these changes
Overall looks good to me

2024-01-04 21:56 UTC, hanhanW commented on compiler/src/iree/compiler/Codegen/Common/EncodingUtils.cpp
>    }
shouldn't we set outerDimsPerm based on indexing_maps? Why only these two cases are considered? What happens to `else`? If we only want to support cases less than or equal to 4D, can you add a comment?

2024-01-04 22:16 UTC, MaheshRavishankar commented on compiler/src/iree/compiler/GlobalOptimization/test/materialize_homogeneous_encodings.mlir
> +    %3 = iree_linalg_ext.set_encoding %padded : tensor<?x?xf32> -> tensor<?x?xf32, #iree_linalg_ext.encoding<user = MATMUL, role = LHS, element_types = [f32, f32, f32], indexing_maps = [#map1, #map2,
Nit: Can we change `indexing_maps` to `user_indexing_maps`. And AFAIU this means we can drop the `user` field?

2024-01-04 22:16 UTC, MaheshRavishankar reviewed
Nicely done @Max191 !

2024-01-08 20:47 UTC, MaheshRavishankar commented
> Really nice work! I think we will need a few cleanups after landing the change:
> 
> 1. Remove EncodingUser.
> 2. Remove ContractionOpType enum struct.

I second these. Did we decide to do that in a follow up?

2024-01-08 21:48 UTC, Max191 commented
> > Really nice work! I think we will need a few cleanups after landing the change:
> > 
> > 1. Remove EncodingUser.
> > 2. Remove ContractionOpType enum struct.
> 
> I second these. Did we decide to do that in a follow up?

Yes, I was planning to do this as a separate PR

2024-01-10 08:14 UTC, hanhanW commented
The dispatch regression about GPT2 should be fixed by https://github.com/llvm/llvm-project/pull/77409

The regression about total artifacts sizes is mostly because of const-eval. We've seen this before, and this is a known issue https://github.com/openxla/iree/issues/14558 We do have 5% improvements in the model and it is treated a noise. After looking into the graph, I believe that the improvement is real:

<img width="892" alt="image" src="https://github.com/openxla/iree/assets/6949191/bd4cf548-af92-4440-a557-515b7f5ccaeb">

The smallest perf number is 76xx ms, while we are at 72xx ms in the report.

<img width="664" alt="image" src="https://github.com/openxla/iree/assets/6949191/e04646ee-2412-476e-a16b-c37fe5001831">

2024-01-11 22:47 UTC, merged