Add vm.buffer.hash and util.buffer.hash ops
iree-org/iree pull request #16003
Opened 2023-12-26 20:52 UTC by qedawkins

This adds support for computing the SipHash24 of a byte range of a buffer, with the goal of using this as a primitive for building a hash table out of VM IR.

2024-01-08 21:53 UTC, benvanik requested changes
Minor style nits and such,

It'd be nice to know how we could make this incremental (an optional state buffer, etc) but that can come with some larger crypto module that does more stuff than what this is intended for (basic hashing of simple bytes spans). Keeping it simple here means we can optimize it pretty tightly/port it pretty easily!

2024-01-08 21:53 UTC, benvanik commented on compiler/src/iree/compiler/Dialect/Util/IR/test/buffer_ops.mlir
> +}
missing newline at end of file in this and other .mlir files (bad editor setting?)

2024-01-08 21:53 UTC, benvanik commented on runtime/src/iree/vm/BUILD.bazel
> +        "//runtime/src/iree/base:core_headers",
base pulls in what's needed - you can remove the #include of alignment.h and this dep

2024-01-08 21:53 UTC, benvanik commented on runtime/src/iree/vm/buffer.c
> +  iree_unaligned_store_le_u64(result, hash);
no need for the unaligned store as the result pointer is always aligned

2024-01-08 21:53 UTC, benvanik commented on runtime/src/iree/vm/buffer.c
> +  // Get the byte span for the source data.
```suggestion

  // Get the byte span for the source data.
```

2024-01-08 21:53 UTC, benvanik commented on runtime/src/iree/vm/buffer.h
> +    iree_host_size_t length, int64_t* result);
if this is output only then prefix with `out_` - if it's I/O then just `result` is fine but we'd want to document the expectations (see comment about incremental hashing).

```suggestion
    iree_host_size_t length, int64_t* out_result);
```

2024-01-08 21:53 UTC, benvanik commented on runtime/src/iree/vm/buffer.c
> +// By Jean-Philippe Aumasson and Daniel J. Bernstein.
worth noting here that it's CC0-licensed (effectively public domain)

2024-01-09 02:46 UTC, qedawkins commented
> Minor style nits and such,
> 
> It'd be nice to know how we could make this incremental (an optional state buffer, etc) but that can come with some larger crypto module that does more stuff than what this is intended for (basic hashing of simple bytes spans). Keeping it simple here means we can optimize it pretty tightly/port it pretty easily!

I found this investigation of a few different choices for incremental hash functions so maybe we can import learnings from there: https://github.com/rust-lang/rust/issues/41215

2024-01-09 22:33 UTC, benvanik approved these changes

2024-01-09 22:42 UTC, merged