Copy source file path when allocating status
iree-org/iree pull request #16066
Opened 2024-01-07 22:40 UTC by qedawkins

When unloading a dynamic module we might inadvertently destroy any
status annotations it added, causing pitfalls/segfaults around status
usage. When allocating the formatted string we already do a copy that
changes ownership of the status annotation, so this does the same for
file paths.

I'm not sure this is the way we want to do this, we could instead force
the clone to happen only for dynamic modules as the deallocation of
source file strings seems unique to that use case.

Fixes https://github.com/openxla/iree/issues/16046

Depends on https://github.com/openxla/iree/pull/16065

2024-01-08 16:43 UTC, benvanik commented
(still waking up)

yeah this is something we want to avoid as we don't want to make 100% of all status emission perform this duplication when nearly 0% require it. we try not to use errors as control flow but it does happen and putting an extra malloc/memcpy there is rough.

we could make this an iree/base/config.h setting and then have dynamic modules set it - that way they get the copy but the hosting binary (where 99% of statuses come from) doesn't. a user could still opt to compile the whole runtime with the setting (for some reason) but wouldn't be required to do so.

once my coffee kicks in I'll take a look at the code - if we can make it easy to #ifdef then that may just be a few line change to preserve the old behavior while opting into the new.

2024-01-08 17:01 UTC, qedawkins commented
> (still waking up)
> 
> yeah this is something we want to avoid as we don't want to make 100% of all status emission perform this duplication when nearly 0% require it. we try not to use errors as control flow but it does happen and putting an extra malloc/memcpy there is rough.
> 
> we could make this an iree/base/config.h setting and then have dynamic modules set it - that way they get the copy but the hosting binary (where 99% of statuses come from) doesn't. a user could still opt to compile the whole runtime with the setting (for some reason) but wouldn't be required to do so.
> 
> once my coffee kicks in I'll take a look at the code - if we can make it easy to #ifdef then that may just be a few line change to preserve the old behavior while opting into the new.

For sure, I was hoping there was a better solution here. I'm not sure about `iree/base/config.h` as this clone needs to happen in the hosting binary. The dynamic module has no (direct) control over when it is going to be uninitialized and so the hosting application needs to be able to do this clone to preserve any status returned by the dynamic module. Maybe the better solution here is to just add an `iree_status_deep_clone` (or change only `iree_status_clone`) that also does this copy.

2024-01-08 17:15 UTC, benvanik commented
status.c should be statically linked into the dynamic modules but I guess changing the config would be tricky as we generally build with the same cmake config for both (thus the same .a).

having a version of iree_status_allocate that copies and that is selected in the header on some config IREE_STATUS_ALWAYS_COPY_METADATA (or whatever) would get around that so any iree_status_allocate made from dynamic modules calls the iree_status_allocate_copy (or whatever) instead of the non-copying iree_status_allocate.

I'm a bit confused here why the clone in run_module.c is needed if you are copying the strings where they are emitted? if we're going to be cloning there then we don't need to copy the strings when we emit the errors, but I don't think that really solves the problem - it'd be better if status just worked without needing the clone (as python and other non-iree-run-module tools don't do that clone and would need the same workaround).

2024-01-08 17:23 UTC, qedawkins commented
> having a version of iree_status_allocate that copies and that is selected in the header on some config IREE_STATUS_ALWAYS_COPY_METADATA (or whatever) would get around that so any iree_status_allocate made from dynamic modules calls the iree_status_allocate_copy (or whatever) instead of the non-copying iree_status_allocate.

This makes sense to me, but I'm still a little fuzzy on where this allocation needs to happen. I can try this and see what happens.

> I'm a bit confused here why the clone in run_module.c is needed if you are copying the strings where they are emitted? if we're going to be cloning there then we don't need to copy the strings when we emit the errors, but I don't think that really solves the problem - it'd be better if status just worked without needing the clone (as python and other non-iree-run-module tools don't do that clone and would need the same workaround).

I couldn't get it to work without the clone but I can give it another try. There might be some other places that need similar handling w/ an `IREE_STATUS_ALWAYS_COPY_METADATA` or something.

2024-01-08 17:30 UTC, benvanik commented
if the contract we want is that a status can be emitted containing pointers to library .text and immediately afterward while the status is still live the library can be unloaded then we must copy at the time the status is emitted. I think that's what we want - less footguns than requiring a clone at the right place - with layering a particular layer may not know if another part of the codebase loaded/unloaded a dynamic module at any given time.

2024-01-08 17:33 UTC, qedawkins commented
> if the contract we want is that a status can be emitted containing pointers to library .text and immediately afterward while the status is still live the library can be unloaded then we must copy at the time the status is emitted. I think that's what we want - less footguns than requiring a clone at the right place - with layering a particular layer may not know if another part of the codebase loaded/unloaded a dynamic module at any given time.

Makes sense, and dynamic modules aren't the recommended flow for absolute maximum performance anyway. I'll try to make that work then.

2024-01-09 22:44 UTC, benvanik requested changes
minor cleanup and otherwise LGTM! nice fix!

2024-01-09 22:44 UTC, benvanik commented on runtime/src/iree/base/status.c
> +    iree_status_free(status);
no need to free if ok (keeps this common path in IREE_RETURN_IF_ERROR cheap)
```suggestion
```

2024-01-09 22:44 UTC, benvanik commented on runtime/src/iree/base/status.c
> +    new_storage->message.data += file_storage_size;
it'd be good to combine the offsetting together up above in one block - only setting ->message.data once, ->file once, etc - right now it's set a few different times (message_data gets offset, then it's calculated again in new_storage->message.data, then it's reset here, etc)

to make it simpler you can also put the file after the message as the file is optional and the message isn't - then you always put the message at the same place (after storage) and tack on the file only if the feature is enabled and the file is non-NULL (would be less #ifs) - no need to reset the message ptr

2024-01-09 22:44 UTC, benvanik commented on runtime/src/iree/base/status.c
> +#endif
```suggestion
#endif  // has any IREE_STATUS_FEATURES
```

for readability it's also sometimes nicer when the function being #ifdefed out is beyond a page to instead just define the function twice - one in the #if as a no-op and the other in the #else - then no need for a reader to track what parts of a function are enabled and instead can easily see the function is just a return _or_ actual work

2024-01-23 20:23 UTC, benvanik approved these changes

2024-01-23 20:48 UTC, ScottTodd approved these changes
(Was waiting for Ben's comments to be addressed) LGTM

2024-01-23 20:48 UTC, ScottTodd commented on samples/custom_module/dynamic/test/example.mlir
Nice new test case! Thanks.

2024-01-23 22:27 UTC, merged