Disable const-eval for parameters unit test
iree-org/iree pull request #16089
Opened 2024-01-09 23:35 UTC by Max191

Const eval is not possible for parameters, so it should be disabled here. The test fails when using const eval with data tiling after transposed cases are supported in https://github.com/openxla/iree/pull/15984

2024-01-10 17:39 UTC, benvanik requested changes
when making temporary changes like this it's good to note the issue tracking reverting it

2024-01-10 17:39 UTC, benvanik commented on runtime/bindings/python/tests/io_test.py
> +            extra_args=["--iree-opt-const-eval=false"],
```suggestion
            # TODO(#15984): re-enable const eval once parameters are supported.
            extra_args=["--iree-opt-const-eval=false"],
```

2024-01-10 17:47 UTC, benvanik commented on runtime/bindings/python/tests/io_test.py
> +            extra_args=["--iree-opt-const-eval=false"],
(or whatever issue is tracking it - I just picked your issue, but looks like that's what breaks it)

2024-01-10 22:54 UTC, Max191 commented
Reminder to turn back on const-eval later: https://github.com/openxla/iree/issues/16098

2024-01-11 15:00 UTC, hanhanW approved these changes

2024-01-11 18:02 UTC, benvanik approved these changes

2024-01-11 18:02 UTC, merged