[HIP] Add inline execution mode
iree-org/iree pull request #16951
Opened 2024-04-02 21:50 UTC by nithinsubbiah

2024-04-03 23:27 UTC, antiagainst requested changes

2024-04-03 23:27 UTC, antiagainst commented on runtime/src/iree/hal/drivers/hip/registration/driver_module.c
> +            "Option 'hip_allowkey_hip_allow_inline_execution' expected to be "
Typo here for `hip_allowkey_hip_allow_inline_execution`.

2024-04-03 23:27 UTC, antiagainst commented on runtime/src/iree/hal/drivers/hip/registration/driver_module.c
> +IREE_FLAG(bool, hip_allow_inline_execution, true,
Make this as `false` by default.

2024-04-11 01:37 UTC, nithinsubbiah commented
Turning this feature ON reduces the SDXL fp16 runtime on MI300X by 1ms. Validated the accuracy of results as well

2024-04-12 04:41 UTC, antiagainst approved these changes

2024-04-12 04:41 UTC, merged