[LinalgExt][Winograd] Add winograd.filter_transform decomposition
iree-org/iree pull request #17103
Opened 2024-04-19 14:42 UTC by Max191

This PR implements the decomposition of the tiled `winograd.filter_transform` op.

2024-04-19 14:51 UTC, Max191 commented
This PR is based on https://github.com/openxla/iree/pull/17102. Please only review the last commit.

2024-04-23 21:14 UTC, harsh-nod approved these changes
Looks good to me! Thanks for putting this together. One thing I don't see from all the PRs yet and maybe this is not relevant for now, but how are these ops going to get constant folded?

2024-04-23 21:32 UTC, MaheshRavishankar approved these changes
This looks good! Thanks!

2024-04-23 22:23 UTC, Max191 commented
> Looks good to me! Thanks for putting this together. One thing I don't see from all the PRs yet and maybe this is not relevant for now, but how are these ops going to get constant folded?

The reason for creating the op for filter transform is to allow constant folding through const-eval. The const eval analysis will see that the op contains only constant inputs and it will evaluate and fold (or alternatively const-expr-hoist for parameters). This all happens automatically through const-eval once the op is in place and can compile.

2024-04-24 00:54 UTC, hanhanW requested changes

2024-04-24 00:54 UTC, hanhanW commented on compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/DecomposeWinogradPass.cpp
> +    rewriter.setInsertionPointToStart(&funcOp.getFunctionBody().front());
Are these needed? I think we can create all operations in-place, so we don't need to move insertion point?

2024-04-24 00:54 UTC, hanhanW commented on compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/DecomposeWinogradPass.cpp
> +        G, inputTileSize, kernelSize, loc, rewriter);
Can we pass `IREE::LinalgExt::Winograd::G.*_6x6_3x3` to `createValueFrom2DConstant` directly?

2024-04-24 00:54 UTC, hanhanW commented on compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/DecomposeWinogradPass.cpp
> +    Value outputSlice = transformOp.output();
nit: they are not used until l.157. Maybe just move them to l.157..

2024-04-24 00:54 UTC, hanhanW commented on compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/DecomposeWinogradPass.cpp
> +    auto tensorType = cast<ShapedType>(outputSlice.getType()).clone(initShape);
nit: this can be `transformOp.getOutputType().clone(initShape)`. then you don't need to cast it here.

2024-04-24 00:54 UTC, hanhanW commented on compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/DecomposeWinogradPass.cpp
> +    transformOp.getResult()[0].replaceAllUsesWith(matmulOp.getResult(0));
Why not use `rewriter.replaceOp()` method? It is much more common in pattern-rewriting way.

2024-04-24 00:54 UTC, hanhanW commented on compiler/src/iree/compiler/Dialect/LinalgExt/Transforms/DecomposeWinogradPass.cpp
> +    rewriter.setInsertionPointToStart(&funcOp.getFunctionBody().front());
The funcOp check looks redundant to me

2024-04-24 16:52 UTC, hanhanW approved these changes

2024-04-24 17:12 UTC, merged