[runtime][cts] add test where a batch is waiting on a smaller value than signaled
iree-org/iree pull request #17141
Opened 2024-04-23 19:03 UTC by sogartar

2024-04-23 23:19 UTC, antiagainst requested changes

2024-04-23 23:19 UTC, antiagainst commented on runtime/src/iree/hal/cts/semaphore_submission_test.h
> +  // Case where we signal after executing the command buffer.
Any reason not having two tests for this?

2024-04-24 13:49 UTC, sogartar commented on runtime/src/iree/hal/cts/semaphore_submission_test.h
> +  // Case where we signal after executing the command buffer.
I split it in 2.

2024-04-24 16:02 UTC, antiagainst approved these changes

2024-04-24 16:10 UTC, merged