Bump torch MLIR to April 23 hash a8ba865fcab6475ff58c2beb14a1823fc25314c2
iree-org/iree pull request #17153
Opened 2024-04-24 02:17 UTC by kumardeepakamd

2024-04-24 16:35 UTC, ScottTodd commented
This runtime error is interesting: https://github.com/iree-org/iree/actions/runs/8810025790/job/24182749076?pr=17153#step:9:90
```
iree/runtime/src/iree/io/stdio_stream.c:312: OUT_OF_RANGE; end-of-file encountered during read; failed to read npy contents of 12 bytes; parsing input `@input_0.npy`; parsing function inputs
```
That looks unrelated to the test case and is likely a runtime / infrastructure issue. Switching from npy to bin might help (that may also help with https://github.com/iree-org/iree/issues/16674 too)

2024-04-24 21:15 UTC, ScottTodd reviewed
I triggered the CI. @kumardeepakamd you may want to join iree-org and the `iree-triage` (or `iree-write` team to be treated as a repository collaborator and have checks run automatically on your PRs

2024-04-24 21:15 UTC, ScottTodd commented on third_party/torch-mlir
gcc build found an error:
```
/work/third_party/torch-mlir/lib/Conversion/TorchToLinalg/Pooling.cpp:303:3:   required from here
/work/third_party/torch-mlir/lib/Conversion/TorchToLinalg/Pooling.cpp:329:10: error: variable 'elementType' set but not used [-Werror=unused-but-set-variable]
  329 |     Type elementType = self.getType().cast<RankedTensorType>().getElementType();
      |          ^~~~~~~~~~~
cc1plus: all warnings being treated as errors
```
https://github.com/iree-org/iree/actions/runs/8823115919/job/24223069273?pr=17153#step:4:7425

We can either silence torch-mlir warnings in IREE or fix that upstream and pick a new commit to import

2024-04-24 21:39 UTC, kumarxilinx commented on third_party/torch-mlir
I will fix it in torch MLIR and bring it back here. I guess we need to be stricter in torch mlir too

2024-04-24 21:59 UTC, ScottTodd commented on build_tools/pkgci/external_test_suite/onnx_gpu_vulkan.json
<sub>(just commenting here for threading, CUDA =/= Vulkan)</sub>

Looks like there is a runtime test newly hanging on CUDA (along with new failures, XPASS or otherwise): https://github.com/iree-org/iree/actions/runs/8823115918/job/24223414689?pr=17153

We have a few test hangs already: https://github.com/iree-org/iree/blob/4e09c8ecdabc0c9f074f8add44c0d15bef72851d/build_tools/pkgci/external_test_suite/onnx_gpu_cuda.json#L14-L18

I've debugged those by running one test at a time instead of in parallel. Can either do that locally or on CI by removing the `-n 4` from the test command: https://github.com/iree-org/iree/blob/4e09c8ecdabc0c9f074f8add44c0d15bef72851d/.github/workflows/pkgci_regression_test_nvidiagpu_cuda.yml#L67-L73

2024-04-24 23:30 UTC, ScottTodd commented on build_tools/pkgci/external_test_suite/onnx_gpu_vulkan.json
I cancelled the CUDA workflow. It was still running after 2h30m, despite running pytest with `--timeout=30` :(

2024-04-25 01:46 UTC, kumarxilinx commented on third_party/torch-mlir
"if constexpr (Dim == 2)" is optimized away for Dim not equal to 2 at compilation time of the above code causing the issue. On second thought, I will push a fix in iree and torch mlir each separately to expedite the bump of torch mlir for iree.

2024-04-25 01:47 UTC, kumarxilinx commented on build_tools/pkgci/external_test_suite/onnx_gpu_vulkan.json
Could we disable the tests causing hang and file an issue to track it?

2024-04-25 02:17 UTC, ScottTodd commented on build_tools/pkgci/external_test_suite/onnx_gpu_vulkan.json
Yeah, we can add to `skip_run_tests` once we determine which test is hanging. Can't tell from the CI since it ran tests in parallel. I could try pinpointing it tomorrow on my local machine if you don't get to it sooner.

2024-04-25 03:55 UTC, ScottTodd requested changes
requesting changes until we/I fix the CUDA tests that never finish running

2024-04-25 15:53 UTC, ScottTodd commented on build_tools/pkgci/external_test_suite/onnx_gpu_vulkan.json
Hmmmm... I don't see a CUDA test hang locally. I can start by updating the XFAILs at least: `76 failed, 406 passed, 749 xfailed in 1478.94s (0:24:38)`

2024-04-25 16:12 UTC, kumardeepakamd commented on build_tools/pkgci/external_test_suite/onnx_gpu_vulkan.json
Add the ones that caused issue to skip_run_tests and then re-tirgger CI?

2024-04-25 16:13 UTC, ScottTodd commented on build_tools/pkgci/external_test_suite/onnx_gpu_vulkan.json
The problem is I don't know which tests caused issues yet :P

2024-04-25 16:42 UTC, ScottTodd commented on build_tools/pkgci/external_test_suite/onnx_gpu_vulkan.json
Lovely... Pushed a test commit to run tests sequentially on CUDA and I see different totals on https://github.com/iree-org/iree/actions/runs/8835976863/job/24261862939?pr=17153#step:9:5655 (Linux) compared to local (Windows, different GPU)... and that didn't hang.

2024-04-25 18:49 UTC, ScottTodd commented on build_tools/pkgci/external_test_suite/onnx_gpu_vulkan.json
Okay, CUDA fixed. This should be ready to go once the rest of the jobs finish.

2024-04-25 18:53 UTC, ScottTodd approved these changes

2024-04-25 19:40 UTC, merged