[GPU] Add option for no gpu.block_dim in GPUDistributeScfFor
iree-org/iree pull request #17214
Opened 2024-04-29 15:07 UTC by Max191

This PR adds an option to generate `arith.constant` ops with workgroup sizes in place of `gpu.block_dim` ops in `GPUDistributeScfFor`. The `gpu.block_dim` ops are not currently handled properly on ROCM backends, so this option is needed to support `GPUDistributeScfFor` on the LLVMGPU path.

2024-04-29 15:10 UTC, Max191 commented
I will create an issue later about the `gpu.block_dim` on ROCM. It will be easier to create a repro once the LLVMGPU winograd pipeline is landed.

2024-04-30 17:51 UTC, antiagainst requested changes

2024-04-30 17:51 UTC, antiagainst commented on compiler/src/iree/compiler/Codegen/Common/GPU/GPUDistributeScfFor.cpp
> +    auto funcOp = forOp->getParentOfType<FunctionOpInterface>();
These checks are only neccessary and to fail when `useBlockDims` is false?

2024-04-30 17:51 UTC, antiagainst commented on compiler/src/iree/compiler/Codegen/Common/GPU/test/gpu_distribute_scf_for.mlir
> +// NO-BLOCK-DIM-LABEL: func.func @distribute_to_y
These tests are duplicated with the above in the sense they don't check additonal stuff? It's fine to just have one of them and remove the others--saves us efforts to update all of them later.

2024-05-01 19:19 UTC, antiagainst approved these changes

2024-05-01 20:02 UTC, merged