[Codegen] Add pattern for lowering iree_gpu.shuffle_tensor
iree-org/iree pull request #17269
Opened 2024-05-02 14:36 UTC by qedawkins

This is a direct lowering that relies on bufferization to produce the
correct allocation and inserts a barrier between the slices.

Depends on #17257 (or can land together).

2024-05-02 14:42 UTC, Groverkss commented
Non blocking, what would be good in future comment: I personally don't like lowering copy like ops directly since you have to have a sequence like:

write
barrier
read
compute

You cannot do pipelining with ops like this. Ideally, you want two different ops:

```
%out = shuffle_out : tensor<64x64xf16> to tensor<64x64xf16, encoding=#shared>
shuffle_in %out : tensor<64x64xf16, encoding=#shared> to tensor<64x64xf16>
```

and then you can do pipelining with these before lowering them to an actual write-barrier-read.

We can probably just change the lowering of shuffle in future, but just wanted to point out what I had in mind.

2024-05-02 14:43 UTC, qedawkins commented
This is a default lowering for the op to make it lowerable.

2024-05-02 14:47 UTC, Groverkss commented
> This is a default lowering for the op to make it usable.

Yeah, I just wanted to mention something I would find useful in future. This should land. pipelining is for later maybe.

2024-05-03 22:11 UTC, MaheshRavishankar requested changes
This looks good. Thanks! But might need changes based on the previous commit.

2024-05-07 04:42 UTC, MaheshRavishankar commented
> Non blocking, what would be good in future comment:
> 
> I personally don't like lowering copy like ops directly since you have to have a sequence like:
> 
> write barrier read compute
> 
> You cannot do pipelining with ops like this. Ideally, you want two different ops:
> 
> ```
> %out = shuffle_out : tensor<64x64xf16> to tensor<64x64xf16, encoding=#shared>
> shuffle_in %out : tensor<64x64xf16, encoding=#shared> to tensor<64x64xf16>
> ```
> 
> and then you can do pipelining with these before lowering them to an actual write-barrier-read.
> 
> We can probably just change the lowering of shuffle_tensor to these 2 ops in future, but just wanted to point out what I had in mind.

This seems like a good idea. Lets revisit the op when this becomes something we need to do...

2024-05-07 04:44 UTC, MaheshRavishankar reviewed
I am wondering if the lower shuffle is something that we can do only "after" bufferization. I am not sure what a gpu.barrier here would do with SSA semantics. Its legal to move things around and skip the barrier.

So implement the bufferization op interface for the operation and then lower it to this?

2024-05-07 13:18 UTC, qedawkins commented
> I am wondering if the lower shuffle is something that we can do only "after" bufferization. I am not sure what a gpu.barrier here would do with SSA semantics. Its legal to move things around and skip the barrier.
> 
> So implement the bufferization op interface for the operation and then lower it to this?

So if we want to implement the bufferization op interface for this op, we will need to be able to vectorize this op. When I looked into that before, the logic surrounding masking and such makes this op somewhat of a headache to vectorize without adding an `iree_gpu.shuffle_vector` op, at least AFAICT.

The other option is to add an `iree_gpu.tensor_barrier` op that keeps the SSA dependency and implement the bufferization op interface on that. That seems worth doing to me anyway but I didn't want to jump straight to that, so I think it's worth landing this lowering with a warning for experimentation and working out barrier details later.

2024-05-07 23:21 UTC, MaheshRavishankar approved these changes

2024-05-08 02:17 UTC, merged