Add collectives tests to CI
iree-org/iree pull request #17433
Opened 2024-05-17 21:25 UTC by sogartar

* Skip the end-to-end collectives test if the required driver or number of devices are not available.
* Add ErrorUnavailable to Python bindings.

2024-05-18 04:32 UTC, antiagainst approved these changes

2024-05-20 15:16 UTC, ScottTodd commented on tests/e2e/collectives/run_requirements.txt
> +# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
While it doesn't hurt, we typically leave off the copyright header for requirements.txt files.

2024-05-20 15:16 UTC, ScottTodd commented on tests/e2e/collectives/CMakeLists.txt
> +      "requires-4-devices"
Did you want these tests running in the `test_amd_mi250` job? I don't see them there yet: https://github.com/iree-org/iree/actions/runs/9140284637/job/25133555370?pr=17433

May need to plumb labels or other features through the workflow and test script: https://github.com/iree-org/iree/blob/a3b74bcc7bd29958c8188e3b79d7000de3427786/build_tools/cmake/ctest_all.sh#L100-L102 https://github.com/iree-org/iree/blob/a3b74bcc7bd29958c8188e3b79d7000de3427786/.github/workflows/ci.yml#L393-L430

Similar story for `test_amd_w7900`, when it is re-enabled (https://github.com/iree-org/iree/issues/17370)

2024-06-21 17:59 UTC, ScottTodd requested changes
What's the status of this PR?

I see lots of changes unrelated to collectives that should be split into 4-5 smaller PRs.
* nanobind changes
* The new `ErrorUnavailable` exception class in the runtime Python bindings
* installing deps for the collectives tests
* whatever the new `iree_target_cmake_name` function is (that shouldn't be needed, CMake has built-in functions that do similar things)

2025-04-30 00:03 UTC, benvanik commented
(closing as stale)

2025-04-30 00:03 UTC, closed without merging