[Codegen][GPU] Add iree_gpu.vector_barrier op
iree-org/iree pull request #17479
Opened 2024-05-23 14:35 UTC by qedawkins

This is the vector equivalent to `iree_gpu.tensor_barrier`. This is kept
as a separate operation because there are no bufferization semantics,
however otherwise it represents the same concept of a wait on a value
semantic vector. In a typical lowering flow, this will represent the
read equivalent to a tensor barrier, in that a tensor barrier represents
a wait until all writes to a shared allocation has finished, while this
represents a wait until all threads have read the value they need from
that shared allocation.

Depends on #17478

2024-05-23 17:20 UTC, MaheshRavishankar requested changes
Could we just change the other operation to handle both tensors and vectors. And then we just error/ignore when we bufferize based on the operand type?

2024-05-23 17:26 UTC, qedawkins commented
It depends a bit on how we want to use it. I figured having two separate operations would be easier to analyze in pipelining transformations, but I don't mind changing it as long as bufferization doesn't have a problem with it.

2024-05-23 17:31 UTC, qedawkins commented
I'm curious what @Groverkss thinks about 2 vs 1 op

2024-05-23 18:30 UTC, qedawkins commented
> Could we just change the other operation to handle both tensors and vectors. And then we just error/ignore when we bufferize based on the operand type?

Actually this doesn't work because `DestinationStyleOpInterface` requires the init types to be a tensor or a memref, so we need a separate operation.

2024-05-26 22:49 UTC, MaheshRavishankar commented
> > Could we just change the other operation to handle both tensors and vectors. And then we just error/ignore when we bufferize based on the operand type?
> 
> Actually this doesn't work because `DestinationStyleOpInterface` requires the init types to be a tensor or a memref, so we need a separate operation.
> 
> Edit: Actually I just removed DPS from the op. I thought it was needed for bufferization but I guess not.

Having DPS means you can use the implementation for bufferization directly.

2024-05-26 22:51 UTC, MaheshRavishankar approved these changes
Nice!

2024-05-27 21:58 UTC, merged