Revert "[iree][global] Add conv2d op to demote to bf16 pass (#17410)"
iree-org/iree pull request #17499
Opened 2024-05-26 23:06 UTC by daveliddell

This reverts commit f2fcbbf1987807685dd3bbbed5a64200907fd36d.

This reversion is needed to reduce the run time of non-winograd convolutions.

2024-05-28 16:50 UTC, hanhanW requested changes
I think we don't want to completely revert the change. Instead, we should add flags to control the behavior.

2024-05-28 18:10 UTC, hanhanW commented
> I think we don't want to completely revert the change. Instead, we should add flags to control the behavior.

@pashu123 can you help land it like what I suggested?

2024-05-28 19:36 UTC, daveliddell commented
> I think we don't want to completely revert the change. Instead, we should add flags to control the behavior.

It looks like we're not going to need this change in this form.  Will close PR for now.  Team can take up later how to make enabling/disabling bf16 demotion per op more general.

2024-05-28 19:36 UTC, closed without merging

2024-05-29 19:30 UTC, pashu123 commented
@hanhanW Added here: https://github.com/iree-org/iree/pull/17515