Add support for Conv2D in new filter layout (Fhwc) : (NchwFchw => NhwcFhwc)
iree-org/iree pull request #17539
Opened 2024-05-31 20:58 UTC by bangtianliu

One compilation flag is added to enable this feature: --iree-preprocessing-enable-fhwc-filter-layout 

When the flag is added and all strides are 1, the format conversion (NchwFchw => NhwcFhwc) for conv2d is enabled with new filter layout; otherwise, still the default option is performed (NchwFchw => NhwcHwcf).

2024-05-31 21:09 UTC, benvanik requested changes
can't speak to whether this is a good idea (seems sketchy - we really don't want flags like this), but some style comments

2024-05-31 21:09 UTC, benvanik commented on compiler/src/iree/compiler/Preprocessing/Common/ConvertConvToChannelsLast.cpp
> +    if (enableFHWCFilter && hasAllOneStrides)
use {} around multi-line if statements (here and elsewhere)

2024-05-31 21:09 UTC, benvanik commented on compiler/src/iree/compiler/Preprocessing/Common/ConvertConvToChannelsLast.cpp
> +    // enable FHWC Filter Layout
style: avoid comments that are not explaining more than what the code itself does

2024-05-31 22:46 UTC, MaheshRavishankar requested changes

2024-05-31 22:46 UTC, MaheshRavishankar commented on compiler/src/iree/compiler/Preprocessing/Common/ConvertConvToChannelsLast.cpp
> +static llvm::cl::opt<bool>
I dont think you need this. All preprocessing passes are just stitched together just like you would with `mlir-opt --pass-pipeline="..."` . So adding a pass option is enough.

2024-06-01 16:26 UTC, qedawkins requested changes
Thanks! This needs a test here: https://github.com/iree-org/iree/blob/e1b9095f763d381bad80684bc89fc4dc3abbb44e/compiler/src/iree/compiler/Preprocessing/Common/test/conv_to_channels_last.mlir#L4

You can add another `// RUN` line that uses the `{enable-fhwc-filter}` pass option to that file.

2024-06-01 16:26 UTC, qedawkins commented on compiler/src/iree/compiler/Preprocessing/Common/ConvertConvToChannelsLast.cpp
> +                       llvm::cl::init(false));
W.r.t. the flag, it shouldn't be necessary because this is a preprocessing pass and is already available as a pass option.

2024-06-01 16:26 UTC, qedawkins commented on compiler/src/iree/compiler/Preprocessing/Common/Passes.td
> +           "enable new filter layout (FCHW ==> FHWC)">,
```suggestion
           "prefer the output channel of the filter to be outer most (FCHW ==> FHWC)">,
```

2024-06-03 23:47 UTC, bangtianliu commented
Thanks for all the comments and appreciate it very much. I have addressed each one in the new commit:

1. Removed the flag
2. Added the test
3. Formatted the code

Please let me know if anything else is required from my end.

2024-06-04 01:02 UTC, qedawkins approved these changes
nice, LGTM bar a few nits

2024-06-04 01:02 UTC, qedawkins commented on compiler/src/iree/compiler/Preprocessing/Common/ConvertConvToChannelsLast.cpp
> +
nit: trailing whitespace

2024-06-04 01:02 UTC, qedawkins commented on compiler/src/iree/compiler/Preprocessing/Common/ConvertConvToChannelsLast.cpp
> +        isInnerIdentityIndices(outputIndices, outputMap.getNumResults()))
you only need to check `filterIndices` again here because `input` and `output` indices are unchanged. Maybe remember the result of `isInnerIdentityIndices` from above instead of calling it twice.

2024-06-04 01:02 UTC, qedawkins commented on compiler/src/iree/compiler/Preprocessing/Common/test/conv_to_channels_last.mlir
> +// FHWC:         linalg.matmul_transpose_b
nit: no newline at the end of the file

2024-06-05 19:30 UTC, kuhar commented on compiler/src/iree/compiler/Preprocessing/Common/ConvertConvToChannelsLast.cpp
> +    auto strides = convOp.getStrides();
Don't use auto when the type is not obvious based on the RHS only.

2024-06-05 19:30 UTC, kuhar commented on compiler/src/iree/compiler/Preprocessing/Common/ConvertConvToChannelsLast.cpp
> +    } else {
no else after return

2025-04-30 00:06 UTC, benvanik commented
(closing as stale)

2025-04-30 00:06 UTC, closed without merging