Integrate llvm/llvm-project@27ac46e6bea2
iree-org/iree pull request #17662
Opened 2024-06-13 04:09 UTC by antiagainst

Updated to llvm/llvm-project@27ac46e6bea2
* Used LLVM `MathExtras.h` to replace MLIR one
* Updated `applySignatureConversion` usage

Updated to openxla/stablehlo@dd48ec5
* `chlo.minimum_broadcast_shapes` op was removed
  https://github.com/openxla/stablehlo/pull/2287
* `chlo.dynamic_reshape` op was removed
  https://github.com/openxla/stablehlo/pull/2286
* Added batching dims to scatter dims
  https://github.com/openxla/stablehlo/pull/2259

Updated to llvm/torch-mlir@77d7f64

2024-06-13 13:54 UTC, kuhar approved these changes

2024-06-13 21:30 UTC, MaheshRavishankar requested changes
We need to look at the regressions in number of dispatches. I can help (but not today).

2024-06-17 20:39 UTC, qedawkins commented
This seems like a fairly likely candidate for the source of dispatch count changes: https://github.com/iree-org/llvm-project/commit/7ef83f5561b34ca07fdef23ca2b3c01c583dbbf5

Especially because the changes are being observed in data tiling enabled benchmarks. cc @Max191

2024-06-20 18:12 UTC, nirvedhmeshram commented
> We need to look at the regressions in number of dispatches. I can help (but not today).

@MaheshRavishankar are you blocking the integrate for this or would you look at it in a follow up since Quinn has explained the reason for the difference?

2024-06-20 20:27 UTC, MaheshRavishankar commented
> > We need to look at the regressions in number of dispatches. I can help (but not today).
> 
> @MaheshRavishankar are you blocking the integrate for this or would you look at it in a follow up since Quinn has explained the possible reason for the difference?

Could you try reverting that locally to see if that is the issue. Then we can decide what to do next

2024-06-20 22:42 UTC, nirvedhmeshram commented
> > > We need to look at the regressions in number of dispatches. I can help (but not today).
> > 
> > 
> > @MaheshRavishankar are you blocking the integrate for this or would you look at it in a follow up since Quinn has explained the possible reason for the difference?
> 
> Could you try reverting that locally to see if that is the issue. Then we can decide what to do next

@MaheshRavishankar PTAL at the benchmark comment now, the bot has edited it and it seems the dispatch number regression is gone with the revert.

2024-06-20 23:30 UTC, MaheshRavishankar approved these changes
Thanks!

2024-06-21 02:24 UTC, merged

2024-08-19 23:13 UTC, ScottTodd commented on compiler/setup.py
> +        "sympy",
Looks like this new dep is for the `fx_importer` in torch-mlir. That should have at least been documented in the PR description.

This should probably go in `extras_require` for a `iree-compiler[torch]` package, not the general requirements here. The dep seems relatively small, but I want to keep the core project's dependencies minimal.