Add preprocessing TransposeExtractConcat pass
iree-org/iree pull request #17692
Opened 2024-06-18 16:25 UTC by IanWood1

2024-06-24 23:01 UTC, MaheshRavishankar requested changes

2024-06-24 23:01 UTC, MaheshRavishankar commented on compiler/src/iree/compiler/Preprocessing/Common/TransposeExtractConcat.cpp
> +  rewriter.setInsertionPoint(sliceOp);
Please add
 ```
OpBuilder::InsertionGuard g(rewriter);
```
before updating the insertion point so that it gets reset on exit from the scope.

2024-06-24 23:01 UTC, MaheshRavishankar commented on compiler/src/iree/compiler/Preprocessing/Common/TransposeExtractConcat.cpp
> +    auto newGenericOp =
I would have expected that you have to transpose the operands as well? I am actually confused why you even need to do a transpose or anything here... you should be able to just clone the operation as is?

2024-06-24 23:01 UTC, MaheshRavishankar commented on compiler/src/iree/compiler/Preprocessing/Common/TransposeExtractConcat.cpp
> +matchOuterExtract(tensor::ExtractSliceOp sliceOp) {
This doesnt seem to be used anywhere?

2024-06-25 05:07 UTC, IanWood1 commented on compiler/src/iree/compiler/Preprocessing/Common/TransposeExtractConcat.cpp
> +    auto newGenericOp =
I guess the naming for the function `createTransposedInit` wasn't good. Its not transposing anything but rather creating an empty tensor of the same shape as the new. The idea is that there is a long chain of unary elementwise generic ops and when the `tensor.extract_slice` op gets transposed, the corresponding child linalg generic's operand type is updated but not the dps init operand.

2024-06-25 05:08 UTC, IanWood1 commented on compiler/src/iree/compiler/Preprocessing/Common/TransposeExtractConcat.cpp
> +  rewriter.setInsertionPoint(sliceOp);
added!

2024-06-25 16:29 UTC, MaheshRavishankar commented on compiler/src/iree/compiler/Preprocessing/Common/TransposeExtractConcat.cpp
> +    auto newGenericOp =
Lets try to find time today to walk through this a bit.

2024-06-28 15:27 UTC, IanWood1 commented
Talked with Mahesh yesterday about this. Notes:

- Must check that indexing maps are identity (like when there is a affine constant 0)

2024-07-03 20:34 UTC, AmosLewis commented
https://github.com/llvm/torch-mlir/pull/3483

2024-07-08 03:48 UTC, closed without merging