Update PckgCI regression test to use new special_models test suite.
iree-org/iree pull request #17803
Opened 2024-07-03 12:48 UTC by saienduri

This commit updates the SHARK-TestSuite ref and makes the neccessary changes to adhere to the new special models test suite. With this, we move away from using all the specialized json config files and complex workflows.
Instead, we use python scripts which allow us to use custom flags, tolerances, and configurations based on the backend/model.
Related PR in TestSuite: https://github.com/nod-ai/SHARK-TestSuite/pull/271

2024-07-03 17:23 UTC, ScottTodd requested changes
Hmmm... I'm feeling like the best path forward here is keep all the "special model" code in-tree (not relying on anything in SHARK-TestSuite) and just extend the existing `experimental/regression_suite` tests. The ability to just run `pytest` and have files downloaded automatically is really useful.

IDK. Probably need to take a step back and put a plan together for "core" project tests, community tests, etc. We're accumulating quite a bit of tech debt by piling new tests on top of old tests without first updating the old tests.

2024-07-03 17:23 UTC, ScottTodd commented on .github/workflows/pkgci_regression_test.yml
> +          pip uninstall -y iree-regression-suite
This is a code smell - installing a package then uninstalling it.

For an incremental step, we could teach `setup_venv.py` to optionally install `iree-regression-suite` and have this job skip that part: https://github.com/iree-org/iree/blob/5f2ebe99c62e1259ec9e50d1aaed520c3f66b5f6/build_tools/pkgci/setup_venv.py#L121-L129

I think what we should ultimately do (like, within 1-2 weeks) is merge (either direction) the existing `experimental/regression_suite` with `SHARK-TestSuite/iree_special_models`

We should also be aiming to move code out of experimental. The new tests here look similar to the rest of `experimental/regression_suite` but use other packages. That's a confusing state to be in. If the new code is also experimental but shares no code directly then it could go in a sibling directory.

2024-07-03 17:23 UTC, ScottTodd commented on experimental/regression_suite/shark-test-suite-models/sd3/test_clip.py
> +# Copyright 2024 Advanced Micro Devices, Inc.
Use IREE copyright in this repo.

```suggestion
# Copyright 2024 The IREE Authors
```

2024-07-03 17:23 UTC, ScottTodd commented on experimental/regression_suite/shark-test-suite-models/sd3/test_clip.py
> +current_dir = repo_root + "/iree_special_models/sd3/prompt-encoder"
I'm still on the fence about how best to architect this, but my gut says this is still inverted and awkward to use.

The `experimental/regression_suite` code (which is stale / unmaintained) uses code like
```python
llama2_7b_f16qi4_stripped_source = fetch_source_fixture(
    "https://sharktank.blob.core.windows.net/sharktank/llama_regression/09152023/llama2_7b_int4_stripped.mlir",
    group="llama2_7b_f16qi4_stripped",
)
```
that fetches as part of the test and doesn't rely on a git repo existing somewhere on disk.

similarly, some new sharktank tests (https://github.com/nod-ai/sharktank/blob/main/sharktank/integration/models/punet/integration_test.py) do this:
```python
@pytest.fixture(scope="module")
def sdxl_fp16_base_files():
    from huggingface_hub import hf_hub_download

    REPO_ID = "stabilityai/stable-diffusion-xl-base-1.0"
    REVISION = "76d28af79639c28a79fa5c6c6468febd3490a37e"

    def download(filename):
        return hf_hub_download(
            repo_id=REPO_ID, subfolder="unet", filename=filename, revision=REVISION
        )

    return {
        "config.json": download("config.json"),
        "params.safetensors": download("diffusion_pytorch_model.fp16.safetensors"),
    }
```

(Stella wrote both of those tests and it's a style I like but am still getting used to)

I'd prefer that style of test file fetching here over the `download_remote_files.py` script, so developers can run `pytest` directly without any other repo fetching: https://github.com/iree-org/iree/tree/main/experimental/regression_suite#quick-start

The main reasons to put files outside of the core IREE repo are:
* Keeping the core repo focused (lower commit volume, lower complexity, more shared between backends / contributors)
* Sharing files across multiple projects (e.g. out of tree plugins like https://github.com/nod-ai/iree-amd-aie)

2024-07-03 17:23 UTC, ScottTodd commented on .github/workflows/pkgci_regression_test.yml
> +            -k ${{ matrix.backend }} \
The `amdgpu_vulkan` matrix entry doesn't specify `backend`, so this is failing with `pytest: error: argument -k: expected one argument`

https://github.com/iree-org/iree/actions/runs/9779308546/job/27006098126?pr=17803#step:11:28

2024-07-12 03:56 UTC, saienduri commented
Oh no, messed up a rebase. Please ignore 😓

2024-07-12 04:03 UTC, closed without merging