[Stream] Teach allocation of encoding to take bcast map into account
iree-org/iree pull request #18046
Opened 2024-07-30 17:35 UTC by Max191

The bcast_map represents the iteration domain mapping from the source of dispatch to matmul. So it uses bcast_map in getMapForOperandIndex() when it is present.

2024-07-30 17:49 UTC, hanhanW requested changes
I need to check the output of SetEncoding first. The logic could be off because I did not notice that the batch dimension could be inferred as M/N dimension. The concern is that it could pad wrong dimensions. Do you want to send the SetEncoding (at flow level) changes first?

https://github.com/iree-org/iree/blob/2c638f31a413a9d36a2b97a61fa0c179b8a62542/compiler/src/iree/compiler/Utils/ElementPackingUtils.cpp#L92-L100

2024-07-30 17:58 UTC, Max191 commented
> I need to check the output of SetEncoding first. The logic could be off because I did not notice that the batch dimension could be inferred as M/N dimension. The concern is that it could pad wrong dimensions. Do you want to send the SetEncoding (at flow level) changes first?

Sure, I'm sending out the SetEncoding changes now. It's possible I mixed up a couple of changes when rebasing and squashing things, so I will verify once I send out all the patches I have right now.

2024-07-30 21:51 UTC, Max191 commented
> The logic could be off because I did not notice that the batch dimension could be inferred as M/N dimension.

I think it should be okay. The contraction dimensions are inferred from the original `user_indexing_maps`, and then the result position is taken from the composed map when padding, so it should infer the contractions dims properly.

2024-07-31 19:07 UTC, hanhanW commented
After reading IRs and codes in your branch, I think it is correct. And we need to update the comments of the methods.

https://github.com/iree-org/iree/blob/d8d140764c40c328537e374e9143ca6bab8f5a14/compiler/src/iree/compiler/Dialect/Encoding/IR/EncodingBase.td#L102-L108

2024-08-01 17:41 UTC, hanhanW approved these changes
lgtm, just one nit

2024-08-01 17:41 UTC, hanhanW commented on compiler/src/iree/compiler/Codegen/Common/EncodingUtils.cpp
>    assert(cDims->m.size() <= 1 && cDims->n.size() <= 1 && cDims->k.size() <= 1 &&
Perhaps we should assert `k.size() == 1`, but not `<=1`.

2024-08-01 17:43 UTC, hanhanW commented
Could you help update the PR description? Like we should include why the return type of `mapDimToOperandIndex` method becomes `std::optional<int64_t>`.

2024-08-01 18:47 UTC, hanhanW approved these changes

2024-08-01 19:34 UTC, merged