[LLVMCPU] Tile reduction dims and fuse input input operands
iree-org/iree pull request #18114
Opened 2024-08-06 12:58 UTC by pashu123

Previously, we only tilled the reduction tile sizes and did not fuse them with the producers from the input operands. It led to transfer read/write with large vector sizes since the dequant operation materialised its own tensor and wasn't fused inside the reduction loop. This pass tiles the reduction dimension and fuses the operations arising from the input operand of the already tiled operation. Most of the code is borrowed from
https://github.com/iree-org/iree/blob/main/compiler/src/iree/compiler/Codegen/Common/GPU/GPUApplyTilingLevel.cpp

2024-08-06 21:14 UTC, hanhanW commented
Talked to @pashu123 offline and I think that we can simplify the logics. This is fine, but it might be too powerful, which makes the logic more complicated. My understanding is that we will always have a single root op, and we can start all the tiling and fusion from the root op.

The only exception that I can think of now is horizontal fusion. I might be wrong if the plan is making horizontal fusion enable by default. If not, I'd prefer simplified version.

2024-08-07 18:09 UTC, MaheshRavishankar requested changes
Overall this pass itself looks good, but is there a reason this cant be incorporated into `LLVMCPUTileAndFusePass`?

2024-08-08 13:38 UTC, pashu123 commented
> Overall this pass itself looks good, but is there a reason this cant be incorporated into `LLVMCPUTileAndFusePass`?

I think we can do that -- add a bool flag `isReduction` and tileandFusepass can take care of reductionTiling. What do you think @hanhanW .

2024-08-08 17:19 UTC, hanhanW commented
> > Overall this pass itself looks good, but is there a reason this cant be incorporated into `LLVMCPUTileAndFusePass`?
> 
> I think we can do that -- add a bool flag `isReduction` and tileandFusepass can take care of reduction tiling. What do you think @hanhanW .

Good point. I think we don't add such logics to LLVMCPUTileAndFuse pass because the legacy passes all start with the last operation. I.e., the `rootOp` will always be the last operation in the dispatch. I think it is better to reuse the pass that you added recently. We can add a `onlyFuseProducerInputOperands` option to `LLVMCPUTileRootAndFuseProducerConsumer`; the default value of the option is false in this case.

Furthermore, we can add a `createLLVMCPUTileRootAndFuseInputOperands` method and the method creates the pass with `onlyFuseProducerInputOperands=true` config. E.g., add below wrapper to https://github.com/iree-org/iree/blob/main/compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPUTileRootAndFuseProducerConsumer.cpp

```cpp
std::unique_ptr<InterfacePass<mlir::FunctionOpInterface>>
createLLVMCPUTileRootAndFuseInputOperands(int64_t tilingLevel) {
  return std::make_unique<LLVMCPUTileRootAndFuseProducerConsumer>(LLVMCPUTileRootAndFuseProducerConsumerOptions{tilingLevel, /*onlyFuseProducerInputOperands=*/true);
}
```

2024-08-09 18:02 UTC, hanhanW requested changes
LGTM, just few nits.

2024-08-09 18:02 UTC, hanhanW commented on compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPUTileRootAndFuseProducerConsumer.cpp
> +  }
nit: this can be simplified to `tileSizes.resize(numLoops, zero);`.

2024-08-09 18:02 UTC, hanhanW commented on compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPUTileRootAndFuseProducerConsumer.cpp
> +    return failure();
nit: add a debug message, like `LLVM_DEBUG(...)`.

2024-08-09 18:02 UTC, hanhanW commented on compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPUTileRootAndFuseProducerConsumer.cpp
> +static LogicalResult fuseConsumers(RewriterBase &rewriter, Operation *tiledOp) {
When does it fail? Can we just have `void` return type?

2024-08-09 18:02 UTC, hanhanW commented on compiler/src/iree/compiler/Codegen/LLVMCPU/test/tile-root-fuse-consumer-producer.mlir
> +// CHECK-REDUCTION-SAME:                               %[[VAL_0:.*]]: tensor<1x320x65x65xi8>) -> tensor<1x320x1x1xf32> {
nit: here is a trick to capture the variable without types, which is much cleaner.

```suggestion
// CHECK-REDUCTION-SAME:                               %[[VAL_0:[a-zA-Z0-9]+]]
```

2024-08-09 18:02 UTC, hanhanW commented on compiler/src/iree/compiler/Codegen/LLVMCPU/test/tile-root-fuse-consumer-producer.mlir
> +// CHECK-REDUCTION:         }
This is making test maintenance harder, we should check what we want to check. I'd suggest to check few scf.for ops + linalg ops + scf.yield. E.g.,

```
// CHECK:  scf.for
// CHECK:    scf.for
...
// CHECK:      %[[pool:.+]] = linalg.pooling...
// CHECK:      scf.yield %[[pool]]

```

2024-08-12 17:25 UTC, hanhanW approved these changes
LGTM, please update the PR title and description before landing it.

2024-08-12 18:17 UTC, pashu123 commented
@MaheshRavishankar PTAL.

2024-08-12 19:47 UTC, MaheshRavishankar approved these changes
Thanks @pashu123

2024-08-13 01:17 UTC, merged