[Flow] Make CollapseDimensions iterative
iree-org/iree pull request #18203
Opened 2024-08-13 15:32 UTC by IanWood1

Each operation must propagate it's collapse information to every other node in the dispatch to ensure that no `collapse_shape` ops are needed between ops in the dispatch.

If a directed edge is defined as going from
consumer -> producer, information is first propagated by going N steps following the direction of the edge, and then M steps opposite the edge. This is "1 iteration". It will take >1 iteration to propagate this information. The failing IR was similar to:

    Root
   /    \
Child1  Child2

First, each child is updated. Then the root is updated from each child. However, no information can be propageted between Child1 <-> Child2.

2024-08-13 16:23 UTC, IanWood1 commented
Fixes issue mentioned in https://github.com/iree-org/iree/issues/18005#issuecomment-2278885607 (failure mentioned in the comment; not the original error)

2024-08-13 21:16 UTC, MaheshRavishankar requested changes

2024-08-13 21:16 UTC, MaheshRavishankar commented on compiler/src/iree/compiler/Dialect/Flow/Transforms/CollapseDimensions.cpp
> +  bool updateCollapseViaIntersect(const CollapsableLoopsSet &otherCollapsable);
Nit: Add comments describing what it returns

2024-08-13 21:16 UTC, MaheshRavishankar commented on compiler/src/iree/compiler/Dialect/Flow/Transforms/CollapseDimensions.cpp
> +  while (didUpdateProducers || didUpdateConsumers) {
You might also want to add a cut-off of max-num iterations, and bail if you broke out of the loop on hitting max number of iterations (like 5 or 10 iterations is fine cause this is within a dispatch)

2024-08-15 21:17 UTC, MaheshRavishankar approved these changes
Thanks!

2024-08-15 21:17 UTC, MaheshRavishankar commented on compiler/src/iree/compiler/Dialect/Flow/Transforms/CollapseDimensions.cpp
> +    if (iterationCount > 10) {
Nit: Make this a pass option and set the default value there.

2024-08-20 18:12 UTC, merged