Integrate LLVM at llvm/llvm-project@
iree-org/iree pull request #18286
Opened 2024-08-19 16:28 UTC by Groverkss

2024-08-21 19:15 UTC, qedawkins approved these changes

2024-08-22 07:14 UTC, marbre requested changes

2024-08-22 07:14 UTC, marbre commented on compiler/src/iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/control_flow_ops.mlir
> +  // CHECK-NEXT: emitc.assign %arg2 : !emitc.ptr<!emitc.opaque<"iree_vm_ref_t">> to %[[REF_LVAL]] : <!emitc.ptr<!emitc.opaque<"iree_vm_ref_t">>>
```suggestion
```
With https://github.com/iree-org/iree/pull/18286/commits/6cd72cb81cbb3df10db379c14cb4a08a038d06f5, this is no longer emitted. @simon-camp please take a look as well.

2024-08-22 08:36 UTC, marbre commented on compiler/src/iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/control_flow_ops.mlir
> +  // CHECK-NEXT: emitc.assign %arg2 : !emitc.ptr<!emitc.opaque<"iree_vm_ref_t">> to %[[REF_LVAL]] : <!emitc.ptr<!emitc.opaque<"iree_vm_ref_t">>>
There are some more fixes needed. Are you okay if I directly push the commits to your branch @Groverkss?

2024-08-22 12:35 UTC, marbre approved these changes

2024-08-22 12:35 UTC, merged