[hip][cuda] Merge the tracing implementations.
iree-org/iree pull request #18299
Opened 2024-08-20 15:01 UTC by AWoloszyn

These were entirely copy-pasted off one another and it's not likely they will have to diverge in the future.

2024-08-20 15:04 UTC, AWoloszyn commented
I currently have 2 different interfaces into the shared code 
`iree_hal_deferred_work_queue_device_interface_t` and `iree_hal_tracing_device_interface_t`. They are similar, and share some similar methods, but I left them as individual interfaces as they are nominally independent. But it means a bit of duplication of code. I was wondering if anyone else had an opinion on this.,

2024-08-20 15:25 UTC, benvanik requested changes
Let's try to pick another name besides `util/tracing.h` (`iree_hal_tracing_`) as this is only applicable to HIP and CUDA. We need a good name for that kind of thing - maybe just `stream_tracing.h` (`iree_hal_stream_tracing_`)?

It's fine to duplicate the interface as we want to keep the code decoupled and implementations may not use both. At some point I hope we delete the stream implementations entirely (or at least use them only as a debugging feature) in which case we may not even care about tracing there.

(still need to read through the rest of the PR, but wanted to flag naming early)

2024-08-20 16:13 UTC, benvanik requested changes
Besides a naming nit on the macros LGTM once moved from utils/tracing to something else

2024-08-20 16:13 UTC, benvanik commented on runtime/src/iree/hal/drivers/hip/rccl_channel.c
> +    IREE_STREAM_TRACE_ZONE_BEGIN_EXTERNAL(
```suggestion
    IREE_HAL_STREAM_TRACE_ZONE_BEGIN_EXTERNAL(
```
(and `IREE_HAL_GRAPH_TRACE_*` for the others)

2024-08-22 17:59 UTC, benvanik approved these changes

2024-08-22 18:11 UTC, merged