[Codegen] Disable transform dialect jit by default
iree-org/iree pull request #18305
Opened 2024-08-21 01:21 UTC by nithinsubbiah

2024-08-21 01:22 UTC, qedawkins approved these changes

2024-08-21 01:22 UTC, MaheshRavishankar approved these changes
Cool! If it doesn't cause regression, let's do it!

2024-08-21 01:22 UTC, MaheshRavishankar approved these changes

2024-08-21 03:54 UTC, kuhar reviewed
Can you add to the PR description what difference this makes and why we prefer to have it off by default?

2024-08-21 21:57 UTC, nithinsubbiah commented
@MaheshRavishankar thoughts on removing the failing tests?

2024-08-21 22:09 UTC, MaheshRavishankar requested changes
Ah, this is failing LLama3B... I dont think we can afford to remove that test... so will probably need to triage whats failing and fix that before doing this.

2024-08-22 02:08 UTC, MaheshRavishankar requested changes
I think not all the pipeline tests are TD related

2024-08-22 20:22 UTC, MaheshRavishankar approved these changes

2024-08-22 20:26 UTC, merged