[Codegen] Add consumer fusion
iree-org/iree pull request #18427
Opened 2024-09-04 13:05 UTC by pashu123

Adds consumer fusion to tile and distribute using for all pass.

2024-09-05 22:52 UTC, MaheshRavishankar requested changes
Nice! 

Could you also add a test for multiple consumers fused in?

2024-09-06 15:54 UTC, pashu123 commented
@MaheshRavishankar, as discussed, I've added a case of multiple consumers fusing. 
This is failing for consumer fusion with multiple users. I tried this example: https://gist.github.com/pashu123/a0f28b70e393d6841a8d20668400c090. Do you have any suggestions?

2024-09-06 20:58 UTC, MaheshRavishankar commented
Looks good. There is an ASAN error in this code. Could you look into this. Ill take your example for multiple uses and see upstream what to do.

2024-09-08 11:56 UTC, pashu123 commented
> Looks good. There is an ASAN error in this code. Could you look into this. Ill take your example for multiple uses and see upstream what to do.

The consumer fusion has to happen after the scf.forall cleanups. The ASAN error was due to that. I've updated the code.

2024-09-11 15:38 UTC, MaheshRavishankar commented on compiler/src/iree/compiler/Codegen/Common/TileDispatchUsingForall.cpp
> +  Operation *lastTiledProducerForConsumerFusion = nullptr;
The name is misleading. Just call this `rootTiledOp`  or something. `lastTiledProducer..` sounds like the last producer that is fused in.

2024-09-11 15:38 UTC, MaheshRavishankar approved these changes

2024-09-11 16:26 UTC, merged