[Common] Convert unit broadcast to tensor.expand_shape
iree-org/iree pull request #18462
Opened 2024-09-08 15:22 UTC by pashu123

This pass converts broadcasts with unit dims to tensor.expand_shape op.

2024-09-09 18:39 UTC, Max191 requested changes
2 main comments:

1. This seems okay to have, but I would expect unit dims like these to be folded during flow FoldUnitExtentDims. My question would be where are you seeing broadcasts like this?
2. This should consider the possibility that broadcasted dimensions are not outermost. The `isBroadcastingOp` function will consider such ops as broadcasts.

2024-09-09 18:39 UTC, Max191 commented on compiler/src/iree/compiler/Codegen/Common/UnitBroadcastToExpandShape.cpp
> +    }
This assumes that the broadcasted dims are the outermost dims, but the `isBroadcastingOp` util does not make this assumption. You can look at the indexing maps to see which dims are in the results of the output map but not the input map. Then, you can check that those dims are all equal to 1.

2024-09-09 18:39 UTC, Max191 commented on compiler/src/iree/compiler/Codegen/Common/UnitBroadcastToExpandShape.cpp
> +
This will also need to account for different dim mappings once the above comment is addressed.

2024-09-10 04:00 UTC, pashu123 commented
> 2 main comments:
> 
> 1. This seems okay to have, but I would expect unit dims like these to be folded during flow FoldUnitExtentDims. My question would be where are you seeing broadcasts like this?
> 2. This should consider the possibility that broadcasted dimensions are not outermost. The `isBroadcastingOp` function will consider such ops as broadcasts.

I am unaware of the FoldUnitExtentDims; this pattern arises after the tile and fuse pass when the batch dim is tiled to 1. Can we use FoldUnitExtendDims after the tile and fuse pass?

2024-09-10 11:13 UTC, pashu123 commented
> > 2 main comments:
> > 
> > 1. This seems okay to have, but I would expect unit dims like these to be folded during flow FoldUnitExtentDims. My question would be where are you seeing broadcasts like this?
> > 2. This should consider the possibility that broadcasted dimensions are not outermost. The `isBroadcastingOp` function will consider such ops as broadcasts.
> 
> I am unaware of the FoldUnitExtentDims; this pattern arises after the tile and fuse pass (broadcast+mmt4d) when the batch dim is tiled to 1. Can we use FoldUnitExtendDims after the tile and fuse pass?

I will close this ` iree-opt --linalg-fold-unit-extent-dims -cse -canonicalize` exactly to get what we want.

2024-09-10 11:13 UTC, closed without merging