[VectorDistribution]reduction support along LLVMGPUVectorDistribute pipeline
iree-org/iree pull request #18519
Opened 2024-09-13 00:27 UTC by bangtianliu

Adding support for Linalg operations with reduction dimensions using the LLVMGPUVectorDistribute pipeline. Currently, there are known issues when compiling UNet, so this is marked as a draft until the bugs are resolved

2024-09-18 19:22 UTC, bangtianliu commented
Still need to solve long compilation time issue

2024-10-15 14:17 UTC, Groverkss requested changes
This is great work. Thanks! The approach is reasonable. To get started, can we split this into 3 patches:

1. Distribution fixes for splat values
2. Layout analysis fixes
3. KernelConfig additions

The first 2 patches are easy to stamp, the 3rd patch needs some thinking through.

2024-10-15 14:17 UTC, Groverkss commented on compiler/src/iree/compiler/Codegen/Common/GPU/GPUDistributionPatterns.cpp
> +    //@Bangtian: will revisit this part later
remove this comment

2024-10-15 14:17 UTC, Groverkss commented on compiler/src/iree/compiler/Codegen/Common/GPU/GPUDistributionPatterns.cpp
> +    if (!isScalar) {
nit: invert condition to be if (isScalar) and move the else branch

2024-10-15 14:17 UTC, Groverkss commented on compiler/src/iree/compiler/Codegen/Common/GPU/GPUDistributionPatterns.cpp
> +      Operation *distirbutedOp = rewriter.create<arith::ConstantOp>(
nit: distirbuted -> distributed

2024-10-15 14:17 UTC, Groverkss commented on compiler/src/iree/compiler/Codegen/Common/GPU/GPUDistributionPatterns.cpp
> +      Operation *distirbutedOp = rewriter.create<arith::ConstantOp>(
Operation * -> auto

2024-10-15 14:17 UTC, Groverkss commented on compiler/src/iree/compiler/Codegen/Common/GPU/GPUDistributionPatterns.cpp
> +      Operation *distirbutedOp = rewriter.create<arith::ConstantOp>(
Operation * -> auto

2024-10-15 14:17 UTC, Groverkss commented on compiler/src/iree/compiler/Codegen/Common/GPU/GPUDistributionPatterns.cpp
> +    } else {
Are these branches different? They look the same to me

2024-10-15 14:17 UTC, Groverkss commented on compiler/src/iree/compiler/Codegen/Common/GPU/GPUNestedLayoutDistributionPatterns.cpp
> +        (srcVector != nullptr) && (srcVector.getType().getRank() != 0);
nit: you can just check !srcVector

2024-10-15 14:17 UTC, Groverkss commented on compiler/src/iree/compiler/Codegen/Common/GPU/GPUNestedLayoutDistributionPatterns.cpp
> +        (srcVector != nullptr) && (srcVector.getType().getRank() != 0);
I would create a helper function "isScalar" and use that instead of checking rank everywhere.

2024-10-15 14:17 UTC, Groverkss commented on compiler/src/iree/compiler/Codegen/Common/VectorLayoutAnalysis.cpp
> +
Can we move this fix to a seperate patch?

2024-10-15 14:17 UTC, Groverkss commented on compiler/src/iree/compiler/Codegen/Common/VectorLayoutAnalysis.cpp
> +    return;
nit: braces

2024-10-15 14:17 UTC, Groverkss commented on compiler/src/iree/compiler/Codegen/Common/VectorLayoutAnalysis.cpp
> +    return;
nit: braces

2025-04-30 00:16 UTC, closed without merging