Bump llvm/llvm-project@030c6da7af826b641db005be925b20f956c3a6bb
iree-org/iree pull request #18512
Opened 2024-09-12 18:52 UTC by rsuderman

llvm/llvm-project@030c6da7af826b641db005be925b20f956c3a6bb llvm/torch-mlir@edf725ef42b9bc7bc1dada691a3988b3c0038e33

Includes updates for slice changes and analysis changes

2024-09-12 18:59 UTC, MaheshRavishankar approved these changes

2024-09-12 20:50 UTC, kuhar commented on compiler/src/iree/compiler/Codegen/LLVMGPU/test/ROCDL/pipeline_tile_and_fuse.mlir
> +XFAIL: *
this should be a comment, similar to RUN

2024-09-12 20:56 UTC, qedawkins requested changes

2024-09-12 20:56 UTC, qedawkins commented on compiler/src/iree/compiler/Codegen/LLVMGPU/test/ROCDL/pipeline_tile_and_fuse.mlir
> +XFAIL: *
This needs to be fixed before landing

2024-09-13 15:31 UTC, qedawkins approved these changes

2024-09-13 18:06 UTC, merged