[ExternalInterfaces] Make fill non-hoistableLeafOp, hoist linalg init operands
iree-org/iree pull request #18634
Opened 2024-09-30 14:15 UTC by Max191

This PR changes the HoistableOpInterface implementation for LinalgOps to make DPS init operands hoistable. If there is real computation on the init of a linalg op, then we would want to hoist that computation. The main way the current policy (not hoisting init operands) affects hoisting today is by preventing linalg.fill ops from being hoisted into splat constants, since the init operands are usually linalg.fill or tensor.empty. Since we want to preserve the behavior of not hoisting fills (and instead fusing them with consumers to handle in codegen), the interface implementation now treats fill ops as non-HoistableLeafOps.

2024-09-30 15:39 UTC, qedawkins approved these changes
Looks good, I assume this is already tested by existing tests?

2024-09-30 15:39 UTC, qedawkins commented on compiler/src/iree/compiler/ExternalInterfaces/UtilExternalModels.cpp
> +      return !isa<linalg::FillOp>(op);
nit: I think there is a `linalg::isaFillOpInterface`

2024-09-30 15:57 UTC, Max191 commented
This breaks the top_k e2e test, but it looks like the top_k lowering was broken to begin with, and constant folding the fills was "fixing" it by adding extra barriers at bufferization. I'm going to need to fix this before landing.

2024-09-30 22:32 UTC, hanhanW requested changes
Thanks for taking care of this! I'd like to take an additional review after the topk issue is fixed, so I put a "request changes" for now.

2024-09-30 22:32 UTC, hanhanW commented on compiler/src/iree/compiler/ExternalInterfaces/UtilExternalModels.cpp
> +  /// FillOp and broadcasting ops are not hoistableLeaf ops, since it is
style nit: adding a blank line before the comment usually helps the readability.

see https://google.github.io/styleguide/cppguide.html#Vertical_Whitespace for more details.

2024-10-01 14:33 UTC, Max191 commented
> Thanks for taking care of this! I'd like to take an additional review after the topk issue is fixed, so I put a "request changes" for now.

I talked to Mahesh offline and we decided it would be okay to open this in an issue and disable the test for now in this PR. @krzysz00 offered to take a look when he has some time, but it might take a few days. Since topK is not very important we decided it is okay to disable the test to unblock GPU data tiling progress. WDYT?

2024-10-01 21:47 UTC, hanhanW approved these changes
SGTM

2024-10-02 15:59 UTC, merged