[tuner]: Add a utility function to query supported MMA intrinsics and expose it to C API and python
iree-org/iree pull request #19124
Opened 2024-11-12 23:13 UTC by bangtianliu

This PR aims to address the task listed in https://github.com/nod-ai/SHARK-Platform/issues/453:  add a utility function (`QueryMMAIntrinsics`) to query supported MMA intrinsics and expose it to C API and python. 

A new test pass `TestLLVMGPUQueryMMAPass` has been added to validate the correctness of this utility function, along with a corresponding test to ensure reliable functionality.

2024-11-13 00:54 UTC, kuhar requested changes
> and expose it to C API and python

This doesn't expose the new helper to C or python. Did you forget to add some files when pushing or is that coming in a future PR?

2024-11-13 00:54 UTC, kuhar commented on compiler/src/iree/compiler/Codegen/LLVMGPU/TestLLVMGPUQueryMMAPass.cpp
> +  llvm::outs() << "\n";
This helper doesn't really do anything -- we can inline it into the pass use `llvm::interleaveComma` instead of the for loop.

2024-11-13 00:54 UTC, kuhar commented on compiler/src/iree/compiler/Codegen/LLVMGPU/TestLLVMGPUQueryMMAPass.cpp
> +                   " Before querying supported mma instrinsic instructions");
There's no point in printing an empty vector

2024-11-13 00:54 UTC, kuhar commented on compiler/src/iree/compiler/Codegen/LLVMGPU/test/test_query_mma.mlir
> +wgp = <compute =  fp64|fp32|fp16|int64|int32|int16|int8, storage =  b64|b32|b16|b8,
We don't need an exhaustive list all the other wgp properties -- we can trim it down to something minimal like `compute = int32, storage = b32, ...`

2024-11-13 00:54 UTC, kuhar commented on compiler/src/iree/compiler/Codegen/Utils/GPUUtils.cpp
> +  moduleOp.walk([&](func::FuncOp funcOp) {
Wouldn't it be enough to look up `hal.executable.variant` only? This is where the attribute is attached to.

2024-11-13 00:54 UTC, kuhar commented on compiler/src/iree/compiler/Codegen/Utils/GPUUtils.cpp
> +  // Walk through all `func::FuncOp` operations in `moduleOp`.
This comment doesn't clarify anything -- `moduleOp.walk` is a very basic function and the intention is obvious here.

2024-11-13 00:54 UTC, kuhar commented on compiler/src/iree/compiler/Codegen/Utils/GPUUtils.cpp
> +                        SmallVector<IREE::GPU::MMAAttr> &mmaAttrs) {
I think this should probably return a mapping of executable variants to their mma attrs. Should should also have a test of a module with two variants.

2024-11-13 00:54 UTC, kuhar commented on compiler/src/iree/compiler/Codegen/Utils/GPUUtils.cpp
> +      mmaAttrs.emplace_back(mma);
we should be able to append all of them at once with `llvm::append_range`

2024-11-13 00:54 UTC, kuhar commented on compiler/src/iree/compiler/Codegen/Utils/GPUUtils.h
> +void QueryMMAIntrinsics(mlir::ModuleOp moduleOp,
```suggestion
void queryMMAIntrinsics(mlir::ModuleOp moduleOp,
```

2024-11-13 01:11 UTC, kuhar commented on compiler/src/iree/compiler/Codegen/Utils/GPUUtils.h
> +                        SmallVector<IREE::GPU::MMAAttr> &mmaAttrs);
Can we return mma intrinsics attrs instead of mma attr? I think we can always go from an intrsic to an mma but not the other way round?

2024-11-14 03:10 UTC, kuhar commented on compiler/src/iree/compiler/Codegen/LLVMGPU/TestLLVMGPUQueryMMAPass.cpp
> +      const SmallVector<IREE::GPU::MMAIntrinsic> &mmaAttrs = entry.second;
You can use structured bindings to unpack these two members to variables

2024-11-14 03:16 UTC, kuhar reviewed
Looks pretty good now, just a few more comments.

We should also update the title of the PR so that we don't advertise C API  and Python bindings which are not in the PR.

2024-11-14 03:16 UTC, kuhar commented on compiler/src/iree/compiler/Codegen/LLVMGPU/TestLLVMGPUQueryMMAPass.cpp
> +      }
use  `llvm::interleaveComma`

2024-11-14 03:16 UTC, kuhar commented on compiler/src/iree/compiler/Codegen/LLVMGPU/test/test_query_mma.mlir
> +max_thread_count_per_workgroup = 1024, max_workgroup_memory_bytes = 65536,
could we further trim this down but skipping some of these `wgp` properties out entirely?

2024-11-14 03:16 UTC, kuhar commented on compiler/src/iree/compiler/Codegen/Utils/GPUUtils.h
> +        &mmaAttributesMap);
Why not return this map?

2024-11-14 03:20 UTC, kuhar commented on compiler/src/iree/compiler/Codegen/Utils/GPUUtils.cpp
> +          llvm::map_range(target.getWgp().getMma(),
Instead of appending to an empty range, use `llvm::map_to_vector`.

2024-11-14 13:45 UTC, kuhar commented on compiler/src/iree/compiler/Codegen/Utils/GPUUtils.h
> +llvm::SmallDenseMap<Operation *, SmallVector<IREE::GPU::MMAIntrinsic>>
Why do we want to return `Operation *` instead of `ExecutableVariantOp`? I think this would simplify both code and the documentation.

2024-11-14 13:45 UTC, kuhar commented on compiler/src/iree/compiler/Codegen/LLVMGPU/TestLLVMGPUQueryMMAPass.cpp
> +      }
Can this actually happen? I don't see it in the LIT test.

2024-11-14 13:46 UTC, kuhar commented on compiler/src/iree/compiler/Codegen/Utils/GPUUtils.cpp
> +      mmaAttributesMap[executableOp] = mmaIntrinsics;
```suggestion
      mmaAttributesMap[executableOp] = std::move(mmaIntrinsics);
```
to avoid needless copying

2024-11-14 13:46 UTC, kuhar commented on compiler/src/iree/compiler/Codegen/Utils/GPUUtils.cpp
> +#include "mlir/Dialect/Func/IR/FuncOps.h"
Is this include still necessary?

2024-11-14 17:16 UTC, kuhar commented on compiler/src/iree/compiler/Codegen/LLVMGPU/TestLLVMGPUQueryMMAPass.cpp
> +                   << cast<IREE::HAL::ExecutableVariantOp>(*op).getName()
Why do we need the cast? I'd think the type of op is already executable variant op, no?

2024-11-14 17:16 UTC, kuhar commented on compiler/src/iree/compiler/Codegen/Utils/GPUUtils.h
>  /// vector of `IREE::GPU::MMAIntrinsic` attributes.
This is out of date

2024-11-14 17:17 UTC, bangtianliu commented on compiler/src/iree/compiler/Codegen/LLVMGPU/TestLLVMGPUQueryMMAPass.cpp
> +                   << cast<IREE::HAL::ExecutableVariantOp>(*op).getName()
No, compiler assumes that it is operation* type.

2024-11-14 17:18 UTC, bangtianliu commented on compiler/src/iree/compiler/Codegen/Utils/GPUUtils.h
>  /// vector of `IREE::GPU::MMAIntrinsic` attributes.
yeah, forgot to update.

2024-11-14 17:39 UTC, kuhar approved these changes
LGTM

2024-11-14 19:31 UTC, merged