[Codegen][LLVMGPU] Drop TransposeSharedMem pipeline
iree-org/iree pull request #19188
Opened 2024-11-18 17:33 UTC by qedawkins

This pipeline is no longer maintained and is not critical for performance anymore. Today all transposes should be fused with a producer or consumer and use of shared memory for transposes is not clearly better for all targets.

2024-11-18 17:33 UTC, hanhanW approved these changes

2024-11-18 17:53 UTC, kuhar approved these changes
🚀

2024-11-18 18:03 UTC, qedawkins commented
aw man, maybe we are relying on this...
ok I can make this work with TileAndFuse.

2024-11-20 17:52 UTC, qedawkins commented
I looked at the pipeline again, and it's actually more reasonable than I initially thought. I went ahead and kept the configuration logic around but replaced it with TileAndFuse so we can at least drop the pipeline. The config logic is still way too hard coded, but this is a step in the right direction at least.

2024-11-20 17:59 UTC, hanhanW requested changes

2024-11-20 17:59 UTC, hanhanW commented on compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
> +  attrs.emplace_back(StringAttr::get(context, "workgroup"),
nit: use `b.getStringAttr("workgroup");`. Same for other codes.

2024-11-20 17:59 UTC, hanhanW commented on compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
> +  auto configDict = DictionaryAttr::get(context, attrs);
ditto: `b.getDictionaryAttr(attrs)`

2025-04-30 00:27 UTC, benvanik commented
(closing as stale)

2025-04-30 00:27 UTC, closed without merging

2025-04-30 01:29 UTC, qedawkins commented
Gah this one needs to happen but I got switched away. I'll reopen once I fix the regressions then.