[Codegen][GPU] Add reshape fusion and cleanup to tiling pass
iree-org/iree pull request #19231
Opened 2024-11-20 18:59 UTC by qedawkins

This adds a pattern to the cleanup pattern set for the SCFTileAndFuse options used in GPUApplyTilingLevel for swapping tensor.expand_shape ops with tensor.extract_slice ops. This enables decomposing pack/unpack ops before tiling.

2024-12-02 17:07 UTC, Max191 requested changes
Overall looks good, just a couple of small comments.

2024-12-02 17:07 UTC, Max191 commented on compiler/src/iree/compiler/Codegen/Common/GPU/GPUApplyTilingLevel.cpp
> +        return failure();
It is better to verify that the transformation is possible before doing any rewrites. Can you move matching logic to a separate function and run it before any affine apply ops are created?

2024-12-02 17:07 UTC, Max191 commented on compiler/src/iree/compiler/Codegen/Common/GPU/GPUApplyTilingLevel.cpp
> +LogicalResult swapExpandShapeWithSlice(RewriterBase &rewriter,
You should also check that the slice is not rank-reducing.

2024-12-02 17:10 UTC, Max191 commented
Btw, I have the same pattern for collapse_shape. I will send it out for review later when this and some of the other fusion patterns have landed.

2024-12-02 17:53 UTC, nirvedhmeshram commented on compiler/src/iree/compiler/Codegen/Common/GPU/test/gpu_apply_tiling_level.mlir
> +// THREAD-LABEL: func.func @swap_expand_shape_with_extract_slice
nit: swap_expand_shape_with_extract_slice_full_inner_dim

2024-12-02 17:53 UTC, nirvedhmeshram commented on compiler/src/iree/compiler/Codegen/Common/GPU/test/gpu_apply_tiling_level.mlir
> +  func.func @swap_expand_shape_with_extract_slice_multiple_groups(%0: tensor<120x56xf32>) -> tensor<3x4x10x7x8xf32> {
nit: I spent some time thinking what multiple_groups is - I think it means "multiple_expanded_dims" ignore if this is common to call that groups. Otherwise can rename.

2024-12-05 16:26 UTC, nirvedhmeshram commented on compiler/src/iree/compiler/Codegen/Common/GPU/GPUApplyTilingLevel.cpp
> +LogicalResult swapExpandShapeWithSlice(RewriterBase &rewriter,
need to make this function static

2024-12-06 20:50 UTC, Max191 approved these changes
Looks good thanks!

It would also be nice to move this to Codegen/Common/Transforms, since we're going to need this in other places too. That can be a follow up or I can just do it when I need to add the pattern in other places later, though.

2024-12-06 20:58 UTC, nirvedhmeshram approved these changes

2024-12-06 22:37 UTC, merged