[Codegen][Common] Add a pass to linearize memrefs
iree-org/iree pull request #19332
Opened 2024-11-28 06:03 UTC by Abhishek-Varma

-- This commit creates a pass to linearize memrefs.
-- The pass `iree-linearize-memrefs` will be iteratively worked upon to make it an inter-procedural pass.
-- Currently it supports limited operations.

Signed-off-by: Abhishek Varma <avarma094@gmail.com>

2024-12-02 17:13 UTC, qedawkins requested changes

2024-12-02 17:13 UTC, qedawkins commented on compiler/src/iree/compiler/Codegen/Common/LinearizeMemRefs.cpp
> +struct LinearizeMemrefAlloc : public OpRewritePattern<OpTy> {
Since this is changing the return type of the alloc op, this pass needs to be either a dialect conversion or insert `memref.expand/collapse_shape` ops at the boundaries of all memrefs to keep types consistent between pattern applications. There are some notes about this here: https://github.com/llvm/llvm-project/blob/bee33b5291a28aec76e98c0da25349266c7b653c/mlir/lib/Transforms/Utils/GreedyPatternRewriteDriver.cpp#L45-L54

The existing pass for memref linearization provides a good example for how to set up the type converter for this: https://github.com/iree-org/iree/blob/f2abfa8b5bdf17ad363cad0af198278c2e700113/compiler/src/iree/compiler/Codegen/Common/FlattenMemRefSubspanPass.cpp#L768

2024-12-03 23:34 UTC, MaheshRavishankar requested changes
Thanks Abhishek! Left a few comments.

2024-12-03 23:34 UTC, MaheshRavishankar commented on compiler/src/iree/compiler/Codegen/Common/LinearizeMemRefs.cpp
> +static LogicalResult linearizeType(MemRefType memrefType,
Please make this return a `FailureOr<MemRefType>` (thats the convention instead of return by reference).

2024-12-03 23:34 UTC, MaheshRavishankar commented on compiler/src/iree/compiler/Codegen/Common/LinearizeMemRefs.cpp
> +struct LinearizeMemrefAlloc : public OpRewritePattern<OpTy> {
There is another option. You could rebuild the original type using `memref.reinterpret_cast`. basically `memref.expand_strided_metadata` and `memref.reinterpret_cast` allow to convert from multi-dim memrefs to one-D memrefs without using type converter.

We could use type converter, but on balance, maybe better avoid it if unnecessary. Dialect conversion is harder to debug.

2024-12-03 23:34 UTC, MaheshRavishankar commented on compiler/src/iree/compiler/Codegen/Common/LinearizeMemRefs.cpp
> +        memref::getLinearizedMemRefOffsetAndSize(
I thought we prefered using `affine.linearize_index`. IIRC this method uses `affine.apply` instead.

2024-12-03 23:34 UTC, MaheshRavishankar commented on compiler/src/iree/compiler/Codegen/Common/test/linearize_memrefs.mlir
> +// RUN: iree-opt -iree-linearize-memrefs -allow-unregistered-dialect %s | FileCheck %s
Could you also add some tests with dynamic shapes, and where the strides and offsets are also dynamic?

2025-01-01 13:52 UTC, Abhishek-Varma commented
Hi @MaheshRavishankar @qedawkins - I've addressed the comments. This is ready for re-reviewing. Thanks!

2025-01-16 23:45 UTC, krzysz00 reviewed
A minor note

2025-01-16 23:45 UTC, krzysz00 commented on compiler/src/iree/compiler/Codegen/Common/LinearizeMemRefs.cpp
> +static SmallVector<Value> getDimValues(Location loc, PatternRewriter &rewriter,
Could this be `OpFoldResult`?

2025-01-16 23:45 UTC, krzysz00 commented on compiler/src/iree/compiler/Codegen/Common/LinearizeMemRefs.cpp
> +    FailureOr<SmallVector<Value>> basis =
Yeah, this should be `OpFoldResult` since it's a linearize  basis

2025-01-17 08:40 UTC, Abhishek-Varma commented on compiler/src/iree/compiler/Codegen/Common/LinearizeMemRefs.cpp
> +    FailureOr<SmallVector<Value>> basis =
Done.

2025-01-17 17:49 UTC, Abhishek-Varma commented
Hi @krzysz00 @qedawkins @MaheshRavishankar - I've addressed all comments and the CI seems to be happy now - you may re-review/approve. Thanks!

2025-01-28 20:28 UTC, qedawkins reviewed
A similar pass came up in a recent discussion, would be good to get a review from @krzysz00 too

2025-01-28 20:28 UTC, qedawkins commented on compiler/src/iree/compiler/Codegen/Common/LinearizeMemRefs.cpp
> +// Copyright 2024 The IREE Authors
```suggestion
// Copyright 2025 The IREE Authors
```

2025-01-28 20:28 UTC, qedawkins commented on compiler/src/iree/compiler/Codegen/Common/test/linearize_memrefs.mlir
> +// CHECK{LITERAL}:                          [[0, 1, 2]]
Oh neat, I didn't know this existed!

2025-01-28 20:28 UTC, qedawkins commented on compiler/src/iree/compiler/Codegen/Common/LinearizeMemRefs.cpp
> +  if (failed(getStridesAndOffset(linearizedType, strides, offset)))
nit: put braces around multiple lines

2025-01-28 20:28 UTC, qedawkins commented on compiler/src/iree/compiler/Codegen/Common/LinearizeMemRefs.cpp
> +  for (auto shape : type.getShape()) {
```suggestion
  for (int64_t shape : type.getShape()) {
```

2025-01-28 20:28 UTC, qedawkins commented on compiler/src/iree/compiler/Codegen/Common/LinearizeMemRefs.cpp
> +  if (!strides.empty() && strides.back() != 1)
I think we need a stronger condition than `strides.back() == 1`. For example, `memref<2x3x4xi32, <strides = [1000, 100, 1], offset = 0>>` is not linearizable. We shouldn't have cases where we need to linearize memrefs with non-trivial strides anyway, so just `if (!strides.empty())` should be good enough here.

2025-01-28 20:28 UTC, qedawkins commented on compiler/src/iree/compiler/Codegen/Common/LinearizeMemRefs.cpp
> +    OpFoldResult zeroOffset = rewriter.getIndexAttr(offset);
nit: name looks misleading, maybe `staticOffset`? Since I think it only works if the offset is static.

2025-01-28 20:28 UTC, qedawkins commented on compiler/src/iree/compiler/Codegen/Common/LinearizeMemRefs.cpp
> +static SmallVector<OpFoldResult> getDimValues(Location loc,
There is a helper `mlir::getMixedValues(ArrayRef<int64_t> staticValues, ValueRange dynamicValues, OpBuilder &b)` that can do this for you

2025-01-28 20:28 UTC, qedawkins commented on compiler/src/iree/compiler/Codegen/Common/LinearizeMemRefs.cpp
> +getMixedOrigSize(Location loc, PatternRewriter &rewriter, Value sourceValue) {
This method could be simpler if you use `memref::getMixedSizes`. Something like
```
  MemRefType sourceType = llvm::cast<MemRefType>(sourceValue.getType());
  Operation *sourceOp = sourceValue.getDefiningOp();
  if (!isa<memref::AllocOp, memref::AllocaOp>(sourceOp) && !sourceType.hasStaticShape()) {
    return failure();
  }
  return memref::getMixedSizes(rewriter, sourceValue);
```

2025-01-28 20:28 UTC, qedawkins commented on compiler/src/iree/compiler/Codegen/Common/LinearizeMemRefs.cpp
> +    SmallVector<int64_t, 2> indices(currentTypeOfSourceMemref.getRank());
```suggestion
    SmallVector<int64_t, 2> indices(currentTypeOfSourceMemref.getRank(), 0);
```

2025-01-28 20:28 UTC, qedawkins commented on compiler/src/iree/compiler/Codegen/Common/LinearizeMemRefs.cpp
> +    rewriter.replaceOp(loadOp, {linearizedLoad});
nit: can use `rewrite.replaceOpWithNewOp<memref::LoadOp>` instead of the separate create + replace

2025-01-28 20:28 UTC, qedawkins commented on compiler/src/iree/compiler/Codegen/Common/LinearizeMemRefs.cpp
> +    multiIndices[0] = llvm::dyn_cast_if_present<Value>(((*basis)[0]));
```suggestion
    multiIndices[0] = llvm::dyn_cast_if_present<Value>((*basis)[0]);
```

2025-01-28 20:28 UTC, qedawkins commented on compiler/src/iree/compiler/Codegen/Common/LinearizeMemRefs.cpp
> +    rewriter.replaceOp(loadOp, {linearizedLoad});
ditto, `replaceOpWithNewOp`

2025-01-29 20:27 UTC, krzysz00 commented
To link what I think we might want to do, https://github.com/iree-org/iree/issues/19851

2025-02-03 09:57 UTC, Abhishek-Varma commented on compiler/src/iree/compiler/Codegen/Common/LinearizeMemRefs.cpp
> +  if (!strides.empty() && strides.back() != 1)
Updated it to be `if (strides.empty())` instead.

2025-02-03 09:58 UTC, Abhishek-Varma commented on compiler/src/iree/compiler/Codegen/Common/LinearizeMemRefs.cpp
> +static SmallVector<OpFoldResult> getDimValues(Location loc,
For a static shape `2x3x4` it'd return `OpFoldResult(Attribute)`, but the users of this API (the op creation) need `OpFoldResult(Value)`.

2025-02-03 09:58 UTC, Abhishek-Varma commented on compiler/src/iree/compiler/Codegen/Common/LinearizeMemRefs.cpp
> +getMixedOrigSize(Location loc, PatternRewriter &rewriter, Value sourceValue) {
Similar reasoning as [previous thread](https://github.com/iree-org/iree/pull/19332#discussion_r1939100154).

2025-02-03 20:01 UTC, krzysz00 commented on compiler/src/iree/compiler/Codegen/Common/LinearizeMemRefs.cpp
> +static SmallVector<OpFoldResult> getDimValues(Location loc,
... Hold on, but `linearize_index` allows `OpFoldResult` in the `basis` bit

Who's using this that needs values?

2025-02-07 02:22 UTC, MaheshRavishankar commented on compiler/src/iree/compiler/Codegen/Common/LinearizeMemRefs.cpp
> +static SmallVector<OpFoldResult> getDimValues(Location loc,
`OpFoldResult` is a combined representation of `Attribute/Value` when the values can be static or dynamic. `OpFoldResult(Atttribute)` vs `OpFoldResult(Value)` shouldnt make a difference. Whether it is an `Attribute` or `Value` is an internal implementation detail of `OpFoldResult` (for the most part).

2025-02-07 02:22 UTC, MaheshRavishankar commented on compiler/src/iree/compiler/Codegen/Common/LinearizeMemRefs.cpp
> +getMixedOrigSize(Location loc, PatternRewriter &rewriter, Value sourceValue) {
Quinn is right. We should be able to just use `getMixedSizes`.  I think you dont even need the `if` condition that he has there.

2025-02-07 08:26 UTC, Abhishek-Varma commented on compiler/src/iree/compiler/Codegen/Common/LinearizeMemRefs.cpp
> +static SmallVector<OpFoldResult> getDimValues(Location loc,
My bad - I didn't explain properly.
So using the `basis` I'm forming `multiIndices` which requires `Value` instead of `Attribute` -  I meant that as the "user" - I understand that was an incorrect explanation.

I realized that I can perform casting for this instance after fetching `basis` the way @qedawkins correctly pointed out.

I've now gotten rid of both of the utilities I created and directly using `getMixedSizes` instead. The code looks much cleaner/concise now - I've created a utility `createLinearizeIndexOp` which I'm now invoking for all the patterns to linearize their `indices` (if required) and `sizes` - reduced code size.

Could you all please take a look?

2025-02-07 08:26 UTC, Abhishek-Varma commented on compiler/src/iree/compiler/Codegen/Common/LinearizeMemRefs.cpp
> +getMixedOrigSize(Location loc, PatternRewriter &rewriter, Value sourceValue) {
Correct. I've responded [here](https://github.com/iree-org/iree/pull/19332#discussion_r1946140768).

2025-04-30 00:31 UTC, benvanik commented
Has this gone stale? It seems like there was interest in it - can it be landed or closed if another direction has been taken?

2025-05-05 06:31 UTC, Abhishek-Varma commented
Closing as another direction was taken.

2025-05-05 06:31 UTC, closed without merging