Enable `hip` tests for the CI
iree-org/iree pull request #19349
Opened 2024-12-03 00:58 UTC by rsuderman

Switching this to run on a w7900 machine we can run presubmits on hip.

2024-12-03 00:59 UTC, rsuderman commented
This will likely fail due to a known `hip` failure but should be submitted once the sharktank CI is passing.

2024-12-03 16:24 UTC, ScottTodd requested changes
Can you add "sharktank" to the PR title somewhere? Maybe

```
Run sharktank tests using `hip` on CI.
```

2024-12-03 16:24 UTC, ScottTodd commented on .github/workflows/pkgci_test_sharktank.yml
> +            runs-on: nodai-amdgpu-w7900-x86-64
Add a matrix entry for GPU using the self-hosted runner instead. CPU tests should continue to run on GitHub-hosted runners for reliability/availability/cost.

Here's an example: https://github.com/iree-org/iree/blob/a30a4193bd58e7562e6b8a730e6f1c1962a71366/.github/workflows/pkgci_test_onnx.yml#L26-L42

2024-12-03 16:24 UTC, ScottTodd commented on .github/workflows/pkgci_test_sharktank.yml
> -              -m "target_cpu" \
There are two things that should vary here based on the `matrix`:

1. the environment variables
2. the pytest filters

How about something like this?

```yml
      matrix:
        include:
          # CPU
          - name: cpu_llvm_task
            runs-on: ubuntu-20.04
            pytest-extra-args: -m "target_cpu"
          # AMD GPU
          - name: amdgpu_hip_rdna3
            runs-on: nodai-amdgpu-w7900-x86-64
            pytest-extra-args: -m "target_hip"
            hip-target: gfx1100
```

Then here:
```yml
      - name: Run Sharktank models test suite
        run: |
          source ${VENV_DIR}/bin/activate
          pytest iree-test-suites/sharktank_models/ \
              -rA \
              --log-cli-level=info \
              --override-ini=xfail_strict=false \
              --timeout=120 \
              --durations=0 \
              ${{ matrix.pytest-extra-args }}
        env:
          HIP_TARGET: ${{ matrix.hip-target }}
```

---

You could also set environment variables like this:

```yml
    steps:
    # ...
    - name: Set HIP_TARGET
      if: contains(matrix.name, "rdna3")
      run: echo "HIP_TARGET=gfx1100" >> $GITHUB_ENV
```

or add a pytest arg:

```yml
      matrix:
        include:
          # CPU
          - name: cpu_llvm_task
            runs-on: ubuntu-20.04
            pytest-extra-args: -m "target_cpu" --hip-target "gfx1100"
```

but what I suggested above is consistent with some other workflow code we have: https://github.com/iree-org/iree/blob/a30a4193bd58e7562e6b8a730e6f1c1962a71366/.github/workflows/pkgci_regression_test.yml#L139-L147 https://github.com/iree-org/iree/blob/a30a4193bd58e7562e6b8a730e6f1c1962a71366/.github/workflows/pkgci_regression_test.yml#L194-L195

2024-12-10 16:27 UTC, ScottTodd reviewed
This LGTM structurally. How do you want to handle the failures?

* Wait to merge until the tests pass
* Ignore the failures (`pytest ... || true`)
* Mark as xfail and merge

2024-12-10 16:27 UTC, ScottTodd commented on .github/workflows/pkgci_test_sharktank.yml
> +            runs-on: nodai-amdgpu-w7900-x86-64
Can the cpu tests continue to run on github-hosted runners? Unless the tests are too slow (20+ minutes) or require large file downloads (2 minutes+ downloading, or bandwidth that we pay for and would rather have cached), prefer to use github-hosted runners to help with job reliability and allow this job to run in forks.

```suggestion
          - name: cpu_task
            target: target_cpu
            gpu: none
            runs-on: ubuntu-20.04
```

2024-12-10 16:28 UTC, ScottTodd commented on .github/workflows/pkgci_test_sharktank.yml
> +            runs-on: nodai-amdgpu-w7900-x86-64
More context in our docs: https://iree.dev/developers/general/github-actions/#using-github-hosted-and-self-hosted-runners

2024-12-10 17:38 UTC, rsuderman commented
> This LGTM structurally. How do you want to handle the failures?
> 
> * Wait to merge until the tests pass
> * Ignore the failures (`pytest ... || true`)
> * Mark as xfail and merge

Bumping ahead will use the flag that avoids the issue. Better to just use it so if other numerical issues arise we can catch them.

2024-12-10 17:51 UTC, ScottTodd approved these changes
LGTM. Please wait for https://github.com/iree-org/iree/actions/runs/12261567395/job/34209524596?pr=19349 to run (and pass) before merging.

2024-12-10 18:30 UTC, merged