[Codegen][Tuner] verifier for the default tuning spec
iree-org/iree pull request #19525
Opened 2024-12-19 01:45 UTC by bangtianliu

Add `iree_codegen.default_tuning_spec` unit attribute to indicate the default tuning spec. 

The verification for the default tuning spec is added  to ensure that it must contain one operation with a symbol name `__kernel_config`

2024-12-19 04:03 UTC, kuhar requested changes
Can you explain what are the alternatives you considered and why you decided on this way of verifying the default specs? IIRC, we first discussed a dedicated verification pass.

Also, please update the documentation in https://iree.dev/reference/tuning/

2024-12-19 04:03 UTC, kuhar commented on compiler/src/iree/compiler/Codegen/Dialect/Codegen/IR/IREECodegenAttrs.h
> +    "iree_codegen.default_tuning_spec";
I'm not sure this is the best name to use -- we should also allow user specs to specify that they have a single entry point. Maybe `iree_codegen.tuning_spec_with_default_entrypoint`?

2024-12-19 04:03 UTC, kuhar commented on compiler/src/iree/compiler/Codegen/Dialect/Codegen/IR/IREECodegenDialect.cpp
> +                  "operation with the symbol name '__kernel_config'.";
Don't hardcode the name here in case we want to rename it in the future.

2024-12-19 04:03 UTC, kuhar commented on compiler/src/iree/compiler/Codegen/Dialect/Codegen/IR/IREECodegenDialect.cpp
> +                   kKernelConfigSpecName;
Can you enumerate the named sequence ops and check only these instead? The check here doesn't guarantee that the symbol is a named sequence, it could be something else.

2024-12-19 04:03 UTC, kuhar commented on compiler/src/iree/compiler/Codegen/Dialect/Codegen/IR/IREECodegenDialect.cpp
> +  //       name `__kernel_config`. If not, emit an error.
```suggestion
  // - If the attribute's name matches `kTuningDefaultSpecAttrName`, make
  //   sure it contains a single named sequence op with name `__kernel_config`.
```
```

2024-12-19 04:03 UTC, kuhar commented on compiler/src/iree/compiler/Codegen/Common/test/verify_tuning_specs.mlir
> +}
We should also have a test for when there's some other op with named `__kernel_config`, e.g., `func.func`.

2024-12-19 04:04 UTC, kuhar commented
There are test failures.

2024-12-19 04:10 UTC, bangtianliu commented
> Can you explain what are the alternatives you considered and why you decided on this way of verifying the default specs? IIRC, we first discussed a dedicated verification pass.
> 
> Also, please update the documentation in https://iree.dev/reference/tuning/

During our discussion, you proposed two approaches: 1) use one separate pass to verify the default spec; 2) add one attribute and update the `verifyOperationAttribute ` function.  At the end, I think we both agree on second one, is my understanding wrong?

2024-12-19 04:11 UTC, kuhar commented
This is something that should be explained in the PR description for all the other folks who did not join the same meeting

2024-12-19 04:12 UTC, bangtianliu commented
> This is something that should be explained in the PR description for all the other folks who did not join the same meeting

Ok, will add it in the PR description.

2024-12-19 04:15 UTC, bangtianliu commented
> There are test failures.

Yeah, will work on fixing it.

2024-12-19 06:44 UTC, bangtianliu commented
In cases where both a user-provided tuning specification (tuning_spec_mmt_tile_and_fuse.mlir) and the default specification (iree_default_tuning_spec_gfx942.mlir) are used, the default spec, after linking the two MLIR files, contains a named sequence operation with the symbol name __kernel_config_1 instead of __kernel_config. This behavior is due to the logic implemented here: [LinkTuningSpecsPass.cpp, Line 110](https://github.com/iree-org/iree/blob/main/compiler/src/iree/compiler/Codegen/Common/LinkTuningSpecsPass.cpp#L110).

To address this which causes the ci errors, I updated the code  from

```
SymbolTable::getSymbolName(namedSeqOp).getValue() ==
                   kKernelConfigSpecName;
```
to   

```
SymbolTable::getSymbolName(namedSeqOp)
                  .getValue()
                  .contains(kKernelConfigSpecName);
```

2025-01-02 17:19 UTC, kuhar commented
> contains a named sequence operation with the symbol name __kernel_config_1 instead of __kernel_config. This behavior is due to the logic implemented here: [LinkTuningSpecsPass.cpp, Line 110](https://github.com/iree-org/iree/blob/main/compiler/src/iree/compiler/Codegen/Common/LinkTuningSpecsPass.cpp#L110).

Good observation, this needs to be handled.

> To address this which causes the ci errors, I updated the code from

This fix is incorrect. It no longer verifies the there's the exact entry point with the default name. If the outermost entrypoint is anything `__kernel_config`, the tuning spec won't be applied. Instead, we need to drop the module-level attribute whenever we rename entrypoints during linking.

2025-01-02 21:14 UTC, kuhar commented on compiler/plugins/target/ROCM/test/default_tuning_specs_amdgpu.mlir
> +// BOTH-LABEL: module @iree_linked_tuning_spec attributes {iree_codegen.tuning_spec_with_default_entrypoint, transform.with_named_sequence}
Can you use `BOTH-SAME` to make this match work for any ordering of these module-level attributes?

2025-01-02 21:14 UTC, kuhar commented on compiler/src/iree/compiler/Codegen/Common/LinkTuningSpecsPass.cpp
> +  // 'iree_codegen.tuning_spec_with_default_entrypoint' to indicate this change.
It's not clear to me what `this change` refers to. Instead, I'd add a comment higher up that this will create a named sequence op that conforms to the requirements of tuning specs with default entrypoint (not just the name).

2025-01-02 21:14 UTC, kuhar commented on compiler/src/iree/compiler/Codegen/Dialect/Codegen/IR/IREECodegenDialect.cpp
> +                     kKernelConfigSpecName;
Can we check the name directly (`.getName` or similar) instead of using the symbol table?

2025-01-02 23:56 UTC, kuhar commented on compiler/src/iree/compiler/Codegen/Common/LinkTuningSpecsPass.cpp
> +  // 'iree_codegen.tuning_spec_with_default_entrypoint' to indicate this change.
I don't think we need this comment anymore
```suggestion
```

2025-01-03 00:00 UTC, kuhar commented on compiler/src/iree/compiler/Codegen/Dialect/Codegen/IR/IREECodegenDialect.cpp
> +      if (!llvm::any_of(moduleOp.getOps(), [](auto &op) {
We don't need this to be generic. Also, let's not shadow the `op` variable from the parent scope.
```suggestion
      if (!llvm::any_of(moduleOp.getOps(), [](Operation *nestedOp) {
```

2025-01-03 00:00 UTC, kuhar commented on compiler/src/iree/compiler/Codegen/Dialect/Codegen/IR/IREECodegenDialect.cpp
> +      if (!llvm::any_of(moduleOp.getOps(), [](auto &op) {
Isn't there a helper that gets the ops of the specified type? Something like `getOps<SomeOp>()`?

2025-01-03 00:00 UTC, kuhar commented on docs/website/docs/reference/tuning.md
> +  the tuning spec includes a named sequence op marked with `__kernel_config`.
```suggestion
  the tuning spec includes a named sequence op with name `__kernel_config`.
```

2025-01-03 00:44 UTC, kuhar approved these changes
LGTM

2025-01-03 01:23 UTC, merged