[i1] Remove command line option to enable packed storage
iree-org/iree pull request #19528
Opened 2024-12-19 15:46 UTC by lialan

* only use `#iree_encoding.packed_storage` to designate if an `i1` tensor is of packed memory layout.
* remove `iree-experimental-packed-i1-storage` command line option.
* teach type converters to allow casting into packed tensor types

2024-12-31 03:11 UTC, lialan commented
This is a successor, improving PR to https://github.com/iree-org/iree/pull/19354

2025-01-07 07:51 UTC, hanhanW commented
The diff is off. There are some changes from https://github.com/iree-org/iree/pull/19354. E.g., the below is not part of this PR, right?

<img width="1175" alt="image" src="https://github.com/user-attachments/assets/3bd4e7da-0f85-4f57-95c3-dd8634c6cf83" />

Can you rebase and fix it?

2025-01-10 05:11 UTC, lialan commented
Note that changes that are not in this PR: #19618 

Changes in #19618 will be based on this PR.

2025-01-13 06:01 UTC, hanhanW requested changes
First round of the review comments, thanks for pushing on this!

2025-01-13 06:01 UTC, hanhanW commented on compiler/src/iree/compiler/Codegen/Common/EncodingUtils.cpp
> +RankedTensorType dropPackedStorageEncodingIfAny(RankedTensorType type) {
Why do we have two dropping encoding methods? Can we just have one? If we just look at the method name, `dropEncoding` should drop all the encodings.

2025-01-13 06:01 UTC, hanhanW commented on compiler/src/iree/compiler/Utils/ElementPackingUtils.h
> +Type legalizeTensorStorageElementType(Type tensorType);
IIRC, this is a rename of `legalizeStorageElementType`, and the implementation of `legalizeStorageElementType` is deleted. Can we just use `legalizeStorageElementType` without renaming? Also, the `legalizeStorageElementTypeImpl` seems no longer needed, can we remove the method, i.e., replace `legalizeStorageElementTypeImpl` with `legalizeStorageElementType`?

2025-01-13 06:01 UTC, hanhanW commented on compiler/src/iree/compiler/Utils/ElementPackingUtils.cpp
> +  return legalizeStorageElementTypeImpl(
I think we can move the logic of `legalizeStorageElementTypeImpl` to here, because this is the only user, right?

2025-01-13 06:01 UTC, hanhanW commented on compiler/src/iree/compiler/Utils/ElementPackingUtils.cpp
> +      !needToPackSubByteElementBitWidth(elementBits)) {
Perhaps we should pass the type to `needToPackSubByteElementBitWidth`, then we don't need `isI1WithPackedStorage` everywhere.

The other use is in EncodeTensor.cpp. Looking at the method, I think it is easy to update the logic, i.e., just pass the type but not `elementBits`.

https://github.com/iree-org/iree/blob/a583b25df17873b9ae214041ba107e47d00f22e1/compiler/src/iree/compiler/Dialect/Stream/Transforms/EncodeTensors.cpp#L155-L171

2025-01-13 06:01 UTC, hanhanW commented on tests/e2e/subbyte_types/subbyte_types_attr.mlir
> +  %flat_input_all = flow.tensor.bitcast %input : tensor<3xi8> -> tensor<24xi1, #packed>
I'm not familiar with how `flow.tensor.bitcast` works. Is the encoding dropped in the `TensorExportBufferViewOpPattern` pattern? How does it become a tensor_export_buffer_view op? I think we need some input from Ben about the change and the test.

2025-01-14 03:28 UTC, lialan commented on tests/e2e/subbyte_types/subbyte_types_attr.mlir
> +  %flat_input_all = flow.tensor.bitcast %input : tensor<3xi8> -> tensor<24xi1, #packed>
The encoding dropped when we do `EmulateNarrowTypes`, because at that time we are emitting a new i8 vector so the attribute gets dropped as well.

`flow.tensor.bitcast` is just an omni-potent caster here to cast a tensor to another tensor with `#packed_storage` attribute.

2025-01-14 03:54 UTC, lialan commented on compiler/src/iree/compiler/Utils/ElementPackingUtils.cpp
> +  return legalizeStorageElementTypeImpl(
yap, you are right. it was just some residual for my previous refactoring. Thanks for pointing this out!

2025-01-14 05:51 UTC, lialan commented on compiler/src/iree/compiler/Utils/ElementPackingUtils.h
> +Type legalizeTensorStorageElementType(Type tensorType);
done.

2025-01-14 06:10 UTC, lialan commented on compiler/src/iree/compiler/Utils/ElementPackingUtils.cpp
> +      !needToPackSubByteElementBitWidth(elementBits)) {
There is one function where the element type and the shape type are handled separately, specifically here: https://github.com/iree-org/iree/pull/19528/files#diff-9ccfc5b598b4e78bd96d52bb2d98f6a07d2d4c34803f80fe3a15248c8700b7a0L102-R75

Still I have made the function to take type instead of bitwidth. But that does not completely eliminate `isI1WithPackedStorage` in this function.

2025-01-15 05:32 UTC, hanhanW requested changes
Thanks for the update! Please also add a test to https://github.com/iree-org/iree/blob/main/compiler/src/iree/compiler/Codegen/Common/test/type_propagation_packing.mlir

2025-01-15 05:32 UTC, hanhanW commented on compiler/src/iree/compiler/Dialect/Encoding/IR/EncodingAttrs.td
> +                            ]>]> {
I don't expect changes other than this part in this file. Can you revert other changes?

2025-01-15 05:32 UTC, hanhanW commented on compiler/src/iree/compiler/Dialect/HAL/Conversion/StreamToHAL/Patterns.cpp
> +        dropEncoding(llvm::cast<RankedTensorType>(adaptor.getSourceEncoding()));
nit: need a comment about why we drop the encoding. If it were me, I'd write:

```cpp
auto tensorType = llvm::cast<RankedTensorType>(adaptor.getSourceEncoding());
// why we drop the encoding
tensorType = dropEncoding(tensorType)
```

2025-01-15 05:32 UTC, hanhanW commented on compiler/src/iree/compiler/Dialect/Stream/IR/StreamOps.cpp
> +
We do not need this. They are declared in the `EncodingTypes.h` and you already include it.

2025-01-15 05:32 UTC, hanhanW commented on compiler/src/iree/compiler/Dialect/Stream/IR/StreamOps.cpp
> +  if (getEncodingAttr(sourceEncoding) != getEncodingAttr(resultEncoding)) {
Is this required by `flow.tensor.bitcast` lowering? I.e., the op is lowered to flow.tensor.clone and you need to bypass the check?

I'm not convinced that the change is correct. Because the `getEncodingAttr` checks if the tensor type has `IREE::Encoding::EncodingAttr` attribute. There could be other encodings and it is a bug if we introduce new encodings. E.g., `tensor<3x4xi32, #whatever_other_encoding_with_padding_semantic>` can not be cloned to `tensor<3x4xi32>`. I think we need to have a stronger restriction. Perhaps just relax the check for packed_storage encoding?

https://github.com/iree-org/iree/blob/27e7a9058eded6a20dc098368352329263f77a23/compiler/src/iree/compiler/Dialect/Encoding/IR/EncodingAttrs.cpp#L278-L280

2025-01-15 05:32 UTC, hanhanW commented on compiler/src/iree/compiler/Dialect/Stream/Transforms/ConvertToStream.cpp
> +      if (auto rankedType = llvm::dyn_cast_or_null<RankedTensorType>(type)) {
Do we really need to check if the incoming type is null type or not? If not, we can just use `dyn_cast`.

Also, please add a comment for the below check.

2025-01-15 05:32 UTC, hanhanW commented on compiler/src/iree/compiler/Utils/ElementPackingUtils.cpp
> +                         IREE::Encoding::hasPackedStorageAttr(rankedTensorType);
Use dyn_cast because it is never a null type. Also, I think we can simplify it a bit, like:

```cpp
auto rankedTensorType = dyn_cast...
if (!rankedTensorType) {
  return false;
}
unsigned bitWidth = IREE::Util::getTypeBitWidth(rankedTensorType.getElementType());
if (bitWidth == 1 && IREE::Encoding::hasPackedStorageAttr...
```

2025-01-15 05:32 UTC, hanhanW commented on compiler/src/iree/compiler/Dialect/Encoding/IR/EncodingAttrs.cpp
> +    staticCount *= elementBits * 8;
Let's avoid magic number: We can move `constexpr int kNumBitsInByte = 8` to global and use it in the file.

https://github.com/iree-org/iree/blob/27e7a9058eded6a20dc098368352329263f77a23/compiler/src/iree/compiler/Dialect/Encoding/IR/EncodingAttrs.cpp#L217

2025-01-15 05:32 UTC, hanhanW commented on compiler/src/iree/compiler/Dialect/Encoding/IR/EncodingAttrs.cpp
> +  }
I think we can simplify this part a lot because we already assert if elementBits is 1 or not in the beginning. My mental model is keeping code simple, and extend it when needed. We definitely need to balance the mental model, but this part is much more complicated than the current need IMO.

btw, I recently learned that we prefer using CeilDivSIOp unless there is a specific reason. See https://github.com/iree-org/iree/pull/19686#discussion_r1915031028 for more details.

2025-01-15 08:58 UTC, lialan commented on compiler/src/iree/compiler/Dialect/Encoding/IR/EncodingAttrs.cpp
> +    staticCount *= elementBits * 8;
Great, I've updated all related parts in this file.

2025-01-15 09:18 UTC, lialan commented on compiler/src/iree/compiler/Dialect/Stream/IR/StreamOps.cpp
> +  if (getEncodingAttr(sourceEncoding) != getEncodingAttr(resultEncoding)) {
I think you are right. I added extra test for the packed attribute.

2025-01-15 13:40 UTC, lialan commented on compiler/src/iree/compiler/Dialect/Stream/IR/StreamOps.cpp
> +  if (getEncodingAttr(sourceEncoding) != getEncodingAttr(resultEncoding)) {
This is a little tricky. And yes this is required by `flow.tensor.bitcast`, and we would sometimes cast from a tensor without attribute to another tensor with packed attribute. In such case, we shouldn't check if both the source and result matches packed attribute.

I have slightly updated it to exclude packed attribute comparison. Suggestions are welcome.

2025-01-15 15:01 UTC, hanhanW requested changes
Reminder: the test is not added yet. https://github.com/iree-org/iree/pull/19528#pullrequestreview-2551569009

2025-01-15 15:01 UTC, hanhanW commented on compiler/src/iree/compiler/Codegen/Common/EncodingUtils.cpp
> +    MaterializeEncodingInfo encodingInfo = getEncodingInfo(type);
Sorry, I missed this in the previous review. Please move it back to where it was. It is not used until l.39 and the below check does not need this information. It also matches the comments better.

(The below comment is a little outdated, I'll fix them in a separate PR.)

2025-01-15 15:01 UTC, hanhanW commented on compiler/src/iree/compiler/Dialect/Encoding/IR/EncodingAttrs.cpp
> +  }
Just a note. The change is fine. In the future, the logic will be moved to `Codegen/ExternalInterfaces/Utils.cpp`. Now we are in a transition state. It will happen after we finish the encoding specialization pass.

https://github.com/iree-org/iree/blob/3c95042d82a310bedc67db2e065680dd85c58d96/compiler/src/iree/compiler/Codegen/ExternalInterfaces/Utils.cpp#L81-L90

2025-01-15 15:01 UTC, hanhanW commented on compiler/src/iree/compiler/Dialect/Encoding/IR/EncodingTypes.h
>  /// Returns true if the type contains packed_storage attribute.
nit:

```suggestion
/// Returns true if the type is a RankedTensorType type and it contains packed_storage attribute.
```

2025-01-15 15:01 UTC, hanhanW commented on compiler/src/iree/compiler/Dialect/HAL/Conversion/StreamToHAL/Patterns.cpp
> +#include "iree/compiler/Codegen/Common/EncodingUtils.h"
We do not want this dependency. I think you want to reuse `dropEncoding` method. Let's move it to `Encoding/EncodingTypes.h` and `EncodingAttr.cpp`. 

(Ideally we should move the implementation to `EncodingTypes.cpp`. I haven't started the work because we have few people touching the dialect at this moment. I'll send a cleanup after you finish the i1 work.)

2025-01-15 15:01 UTC, hanhanW commented on compiler/src/iree/compiler/Dialect/HAL/Conversion/StreamToHAL/Patterns.cpp
> +        dropEncoding(llvm::cast<RankedTensorType>(adaptor.getSourceEncoding()));
I'm confused. Won't this crash in debug build? We have below assertion in the implementation:

```
assert(!IREE::Encoding::hasPackedStorageAttr(type) &&
         "not expected `packed_storage` attribute.");
```

2025-01-15 15:01 UTC, hanhanW commented on compiler/src/iree/compiler/Dialect/Stream/IR/StreamOps.cpp
> +      !IREE::Encoding::hasPackedStorageAttr(resultEncoding)) {
It looks better to me. I think we need some input from @benvanik 

The previous comment is not tracked in the review mode. Here was the previous comment: https://github.com/iree-org/iree/pull/19528#discussion_r1915955126 

TLDR is that we use flow.tensor.bitcast to prepare packed data for e2e testing. The op becomes TensorClone op during the lowering. So we want to relax the verification here.

```
%flat_input_all = flow.tensor.bitcast %input : tensor<3xi8> -> tensor<24xi1, #packed>
```

2025-01-16 03:06 UTC, lialan commented on compiler/src/iree/compiler/Dialect/HAL/Conversion/StreamToHAL/Patterns.cpp
> +        dropEncoding(llvm::cast<RankedTensorType>(adaptor.getSourceEncoding()));
You are right, this is some code left in previous iteration. removed it and its deps.

2025-01-16 03:21 UTC, lialan commented on compiler/src/iree/compiler/Dialect/HAL/Conversion/StreamToHAL/Patterns.cpp
> +#include "iree/compiler/Codegen/Common/EncodingUtils.h"
removed all those deps.

2025-01-16 07:59 UTC, lialan commented
@hanhanW I've added a test to test type propagation.

2025-01-16 09:24 UTC, hanhanW reviewed
Just a few final nits. LGTM except the `TensorCloneOp::verify` part. Please coordinate with @benvanik about it.

2025-01-16 09:24 UTC, hanhanW commented on compiler/src/iree/compiler/Codegen/Common/test/type_propagation_packing.mlir
> +//       CHECK:   flow.dispatch.tensor.store %[[GENERIC]], %[[OUT]]
nit: missing new line at the end.

![Uploading image.png…]()

2025-01-16 09:24 UTC, hanhanW commented on compiler/src/iree/compiler/Dialect/Encoding/IR/EncodingAttrs.cpp
> +    return dyn_cast_or_null<PackedStorageAttr>(encoding) != nullptr;
I think this can be `return dyn_cast_or_null<xxx>(tensorType.getEncoding)`?

2025-01-16 09:24 UTC, hanhanW commented on compiler/src/iree/compiler/Dialect/Encoding/IR/EncodingTypes.h
>  /// Returns true if the type contains packed_storage attribute.
It is marked resolved. Is it addressed?

2025-02-05 18:37 UTC, lialan commented on compiler/src/iree/compiler/Dialect/Stream/IR/StreamOps.cpp
> +      !IREE::Encoding::hasPackedStorageAttr(resultEncoding)) {
@benvanik Do you have opinions on this?

2025-02-10 16:01 UTC, benvanik requested changes

2025-02-10 16:01 UTC, benvanik commented on compiler/src/iree/compiler/Utils/ElementPackingUtils.cpp
> +  bool isI1WithPackedStorage = elementBits == 1 && isPackedStorage;
There's a lot of i1 special casing in this file still - I think it could be simplified to be `isPackedStorage = IREE::Encoding::hasPackedStorageAttr(shapedType) || needToPackSubByteElementBitWidth(elementBits)` as I can't think of a case where we'd not have those both be the case. And really, we should now be putting packed storage attrs on everything we want packed and remove needToPackSubByteElementBitWidth entirely.

2025-02-10 16:01 UTC, benvanik commented on compiler/src/iree/compiler/Dialect/Stream/IR/StreamOps.cpp
> +using IREE::Encoding::getEncodingAttr;
directly reference this when required - it hurts readability to have aliases like this (as a user will just see getEncodingAttr and not know if it's on their type, in the dialect they are in, etc) - I'm not sure we want this function anywhere, though, as commented below (the flow/stream dialects should support all encodings, not just those in the encoding dialect)

2025-02-10 16:01 UTC, benvanik commented on compiler/src/iree/compiler/Dialect/Stream/IR/StreamOps.cpp
> +  if (getEncodingAttr(sourceEncoding) != getEncodingAttr(resultEncoding)) {
I agree with hanhan - I'm not sure why this changed - if it is indeed tricky it's too tricky to be as opaque as this. The op behavior and the comment both state the existing code was the check that was desired, and not that we should allow non-encoding-dialect encodings to be ignored.

2025-02-10 16:01 UTC, benvanik commented on compiler/src/iree/compiler/Dialect/HAL/Conversion/StreamToHAL/Patterns.cpp
> +#include "iree/compiler/Codegen/Common/EncodingUtils.h"
as a general rule there are to be no codegen deps in non-codegen directories - dropPackedStorageEncodingIfAny should be moved to EncodingTypes.h

2025-02-10 16:01 UTC, benvanik commented on tests/e2e/linalg_ext_ops/BUILD.bazel
> -iree_check_single_backend_test_suite(
you need to un-exclude the test from the above ALL_SRCS

2025-05-06 18:47 UTC, benvanik commented
Closing as stale for now (and renaming the branch to follow repository naming conventions). You can reopen/rebase if you still want to land it in the future.

2025-05-06 18:47 UTC, closed without merging