Add support for executable duplication in encoding specialization pass.
iree-org/iree pull request #19527
Opened 2024-12-19 09:59 UTC by hanhanW

Duplicates stream.executables based on the affinity analysis of stream.async.dispatch ops. Some executables can be launched by different devices. It can produce wrong codegen artifacts when bindings types are encoded (i.e., the tensor type has an encoding attribute). Because they can result in different layouts, especially when multi-device is involved. E.g., say that device_a and device_b interpret a tensor type with encodings in different layouts, and there is an executable that can be launch with resources from either device_a or device_b. It is confusing what the input layouts for the executable because there are two possibilities. In this case, we have to duplicate the executable with updated encoding, and modify the dispatch to launch proper executable based on device analysis.

2024-12-19 10:00 UTC, hanhanW commented
The PR depends on https://github.com/iree-org/iree/pull/19502. It is ready for review, which compares the diff to the parent mirror branch.

2025-01-09 09:22 UTC, hanhanW commented
I spent some time on the bazel failure, but I can't reproduce it on cmake build even with ASAN enabled. I'll try to set up the bazel one my env, the PR is ready to review. Please take a look, thanks!

2025-01-13 18:15 UTC, hanhanW commented
> I spent some time on the bazel failure, but I can't reproduce it on cmake build even with ASAN enabled. I'll try to set up the bazel one my env, the PR is ready to review. Please take a look, thanks!

I think I'd be able to reproduce it if I build it in release mode. I put a statement in an assertion because I wanted to check if the return value is true or not. However, the statement is dropped in release build..

2025-01-15 16:40 UTC, benvanik requested changes
We don't want to duplicate based on affinity - in your test we can see why: we don't want to double compile executables that are going to have the same exact compilation flow as we're just doubling our compile time (or on an 8 way config x8!).

`IREE::Stream::AffinityAttr` has a `areCompatible` / `canExecuteTogether` which indicates when two operations can execute in the same place (which is not what you want - that's for execution scheduling). Here you need something like `areTranslationCompatible` which indicates when two affinities share the same execution configuration and only duplicate when that's not the case (you want the smallest set of unique executable targets). We could probably rename `areCompatible` to `areExecutionCompatible` to differentiate (at some point we'll add an `areAllocationCompatible` for unified memory systems and stuff where execution and translation may differ but buffers can be shared).

You'll want to have a test like you have with two devices that share targets ensuring they don't get duplicated and two devices with different targets ensuring they do.

2025-01-15 16:40 UTC, benvanik commented on compiler/src/iree/compiler/Dialect/Stream/Transforms/SpecializeEncodings.cpp
> +  // 1. Gather per-export [execution affinity -> [resource affinities]] map.
style: prefer not using numbers - they always end up wrong when code is moved around or when code is inserted/removed. You can call out preconditions/postconditions if blocks of code do have to be performed in order (e.g. "build cache of valid ops after removing dead ops" etc)

if the algorithm has a flow then that can be documented in the function comment where someone landing on the function wants to know how it works. By keeping them inline a reader has to read the whole function (like I just did, wondering where 2 was for a page :)

2025-01-17 13:39 UTC, hanhanW commented
https://github.com/iree-org/iree/blob/36c2353653e69e8e38700c449f56ca5c71e63520/compiler/src/iree/compiler/Dialect/Stream/IR/StreamInterfaces.td#L108-L116

I found the above comment in `areCompatible` documentation, and I have a question. It seems like it'd return true if one of `desiredAffinity` is compatible with `requiredAffinity`. Does it mean that `[device_a, device_b]` is compatible with `[device_a]`? Does it mean that the compatibility could be unidirectional? I.e., X is compatible with Y, but Y is not compatible with X.

In the `areTranslationCompatible`, should we make it bidirectional?

> Note to make the compatibility checks scale better you can gather all (like you do), use llvm::EquivalenceClasses + areTranslationCompatible to build the sets of compatible devices, then run down your executables and duplicate for each non-intersecting set (this avoids doing areTranslationCompatible n^2).

IIUC, the `llvm::EquivalenceClasses` is a disjoint-set. Say that we have `areTranslationCompatible` implemented. The algorithm would be:

1. Collect all the affinities.
2. Categorize the affinities into few groups, using `llvm::EquivalenceClasses`.
3. Each group can map to a unique hash/affinity/whatever. We then use the unique affinity in my current implementation, which can reduce the number of duplications.

Do I understand it correctly?

Meanwhile, I'm going to study the compatibility things in Stream dialect. It's a new thing to me!

2025-01-17 13:51 UTC, hanhanW commented
I just found that the current implementation is simple. It does not consider the case that I listed above. I think I can start with a similar version.

https://github.com/iree-org/iree/blob/36c2353653e69e8e38700c449f56ca5c71e63520/compiler/src/iree/compiler/Dialect/Stream/IR/StreamTypes.cpp#L375-L384

2025-01-17 16:43 UTC, benvanik commented
the executable targets are what we care about matching, not the affinities - we don't want to cluster by affinities, but by those sets of targets, and then generate based on required sets of targets. CUDA GPU 0 and CUDA GPU 1 (two different affinities) have the same executable targets and we don't want to duplicate, CUDA GPU 0, CUDA GPU 1, and CPU (three different affinities) have CUDA GPU 0 and CUDA GPU 1 sharing the same targets but the CPU is different and we'd want one copy for the CUDA GPUs and one copy for the CPU (because we're talking about targets, not affinities).

2025-01-17 16:43 UTC, benvanik commented
(that may be what you're saying, I just realized I didn't word what I said very well :)

2025-01-20 17:59 UTC, hanhanW commented
I see what you mean. I also need to implement `AffinityAliasingSet`. The prototype is done, please take a look! (Many thanks for all the details, it is very helpful!)

2025-01-20 18:00 UTC, hanhanW commented
(I'll rebase after I land https://github.com/iree-org/iree/pull/19726)

2025-01-24 14:18 UTC, hanhanW commented
I don't want to force-push this PR because I want the code can be searched in the future. Just in case that someone is interested in TranslationCompatible support, and they can take a look at this. The new version, which duplicates executable based on binding layouts, is up: https://github.com/iree-org/iree/pull/19803

2025-01-24 14:18 UTC, closed without merging