Add missing definition of `build` method of `Flow::CallOp`
iree-org/iree pull request #19552
Opened 2024-12-21 06:09 UTC by PragmaTwice

In `flow.call` op, there are two custom `OpBuilder` declarations:
https://github.com/iree-org/iree/blob/76a7b893e4c62d52eae2c165bdb23952a8589689/compiler/src/iree/compiler/Dialect/Flow/IR/FlowOps.td#L983-L996

And the second one is defined in `FlowOp.cpp`:
https://github.com/iree-org/iree/blob/76a7b893e4c62d52eae2c165bdb23952a8589689/compiler/src/iree/compiler/Dialect/Flow/IR/FlowOps.cpp#L1579-L1583

However, the function definition of the first one is missing. If we try to use it, we'll get a "undefined symbol" linker error in build phase.

So in this PR I try to add a definition for the first `OpBuilder` (inside the tblgen file instead of `FlowOp.cpp`).

2024-12-21 06:12 UTC, PragmaTwice commented on compiler/src/iree/compiler/Dialect/Flow/IR/FlowOps.td
> +      "TypeRange":$resultTypes, "ValueRange":$resultDims,
The `argumentDims` can be inferred/constructed by `buildDynamicDimsForValues`, but I think it's hard for the `resultDims` so I add it to the parameter list. Feel free to comment for any idea here : )

2025-01-06 04:30 UTC, PragmaTwice commented
I would greatly appreciate it if some reviews were given. It was posted before the holiday, so the original notification may have been overlooked : )

2025-01-06 04:56 UTC, hanhanW requested changes
Sorry for the late review, I'm just back from vacation. Overall, it looks okay to me. Can you move the implementation to `FlowOps.cpp` for consistency?

2025-01-06 09:18 UTC, PragmaTwice commented
> Sorry for the late review, I'm just back from vacation. Overall, it looks okay to me. Can you move the implementation to `FlowOps.cpp` for consistency?

Sure! Moved.

2025-01-06 15:38 UTC, benvanik approved these changes

2025-01-06 16:03 UTC, hanhanW approved these changes

2025-01-06 16:03 UTC, merged