Exposing/implementing the HAL driver registry via the C API.
iree-org/iree pull request #3937
Opened 2020-11-20 07:46 UTC by benvanik

Enables drivers to be provided externally by callers and
discovered/loaded dynamically. Zero cost when applications
explicitly create their own drivers directly (LTO stripped).

Example use cases are compiling LLVM JIT in its own dylib,
remote/sandboxed drivers enumerated based on availability,
driver multiversioning, and out-of-tree drivers from
downstream projects.

2020-11-21 03:01 UTC, benvanik commented
@KoolJBlack scott mentioned you may be looking at HAL+android stuff soon - this is probably going to be very useful for you :) Happy to gvc and walk through this if you have questions (about this or the HAL API in general).

2020-12-01 01:12 UTC, ScottTodd requested changes

2020-12-01 18:14 UTC, benvanik commented on iree/hal/api.c
> +      iree_make_status(IREE_STATUS_UNIMPLEMENTED, "driver creation by id nyi");
It would - but not now.

2020-12-01 18:16 UTC, benvanik commented on iree/hal/api.h
> +  // Called with the driver registry lock held; may be called from any thread.
It's not an implementation detail - this is a user-provided function that is getting called with a lock held. It's part of the API. Like with any lock in any situation you can't call a function that also tries to take a lock (so don't call yourself) but can call functions that also expect the lock to be held (like enumerate + try_create).

2020-12-01 18:22 UTC, benvanik commented on iree/hal/drivers/init.h
> +iree_hal_register_all_available_drivers(iree_hal_driver_registry_t* registry);
The comment is precise and covers this ("registers all drivers that were linked into the current binary"). If someone doesn't understand the chicken-egg ("I have an empty registry and this method adds things to it! crazy?!") then they are going to have a lot more trouble with this than any comment here will help with.

2020-12-01 21:09 UTC, ScottTodd approved these changes

2020-12-01 21:09 UTC, ScottTodd commented on iree/hal/api.h
> +  // Called with the driver registry lock held; may be called from any thread.
Ah, I missed some of the "user-provided function" details. Makes more sense seeing how it is used in the `driver_module.cc` files.

2020-12-01 23:14 UTC, KoolJBlack approved these changes
I've looked through this. Would like to have more discussion with Ben, but it looks good. 

Thanks.

2020-12-02 17:41 UTC, merged