Add a pass to convert some std ops to mhlo ops.
iree-org/iree pull request #5906
Opened 2021-05-14 19:31 UTC by hanhanW

This provides more opportunities for fusion. It could prevent
unnecessary host readback of device memory because most of std ops are
run on host side.

2021-05-14 19:33 UTC, benvanik requested changes
This is the opposite of what we want - we are working hard to *remove* hlo from the flow dialect :)
If the issue is that there are missing std ops we should add to that or to the tensor dialect. If it's that our detection code somewhere is not detecting the std ops but is detecting the hlo ones, we should fix that.

2021-05-14 19:38 UTC, benvanik commented
(I do fully support reducing round trips - just not via HLO :)

2021-05-14 19:42 UTC, hanhanW commented
I actually just wanna convert them to linalg ops. What came in my mind is that the import tool generates such patterns and I think they should be converted to hlo ops. This is the reason that I put the pass into buildHLOInputTransformPassPipeline which is expected to move to other places like `HLOToHLOPreprocessingPass.cpp`.

Another approach is just convert it to Linalg ops and put the code to iree/compiler/Conversion/StandardToLinalg or extend ElementwiseToLinalg.cpp (in MLIR repro) to support it.

2021-05-14 19:46 UTC, benvanik commented
> I actually just wanna convert them to linalg ops. What came in my mind is that the import tool generates such patterns and I think they should be converted to hlo ops. This is the reason that I put the pass into buildHLOInputTransformPassPipeline which is expected to move to other places like `HLOToHLOPreprocessingPass.cpp`.
> 
> Another approach is just convert it to Linalg ops and put the code to iree/compiler/Conversion/StandardToLinalg or extend ElementwiseToLinalg.cpp (in MLIR repro) to support it.

ah sorry - I didn't spot that - if it's in there then that's probably ok, though that just shifts the issue to integrations/tensorflow/. If we think we'll need this code forever we'll want to upstream it into HLO directly so we don't have to maintain it. A StandardToLinalg would be best, though, because then as we get other frontends online we will get the same benefits (thinking of npcomp and tosa).

My major concern was that I was planning to move that hlo preprocessing pipeline this weekend and didn't want something new sneaking in :P

2021-05-14 19:48 UTC, MaheshRavishankar commented
> Another approach is just convert it to Linalg ops and put the code to iree/compiler/Conversion/StandardToLinalg or extend ElementwiseToLinalg.cpp (in MLIR repro) to support it.

Agree with Ben. We should definitely convert from standard to linalg using the patterns from core, and adapt those for our use going from standard to HLO and then to Linalg is unnecessarily jumping through hoops. Also standard to HLO should live in HLO if it ever needed to exist.

In the heirarchy of dialects we should be 

MHLO -> Tensor -> Linalg

(If we are having to convert Standard to Linalg it is just an indication that something that had to move to the tensor dialect hasnt been moved yet)

2021-05-21 01:06 UTC, hanhanW commented
I will add support for lowering select op on i1 pred to Linalg ops in core. We can revisit if this is needed for frontend later.

2021-05-21 01:06 UTC, closed without merging