Install external libraries and IREE runtime headers.
iree-org/iree pull request #8215
Opened 2022-02-01 06:36 UTC by stellaraccident

Our install directory is a bit of a mess and needs more triage. This PR just enables a minimal set of installations to plausibly build, including runtime headers and bundled external libraries (cpuinfo, libflatcc_parsing).

I haven't actually tried to build something but this at least makes it feasible that a mortal could in fact do so. Missing pieces are a config.h with compiler definitions and a package config file with necessary libraries to link against (but there are only three now so not too hard to figure out).

Progress on #7026

2022-02-01 16:52 UTC, marbre requested changes
Nice! I noticed that this also installs the header-files contained in `iree/base/internal`. Is this intended or just a missing `set(IREE_DISABLE_INSTALL_HEADERS ON)`?

2022-02-01 16:52 UTC, marbre commented on iree/testing/BUILD
> +    content = "set(IREE_DISABLE_INSTALL_HEADERS ON)",
The `set(IREE_DISABLE_INSTALL_HEADERS ON)` line needs to be added by hand to the corresponding `CMakeLists.txt` which doesn't use bazel_to_cmake:

https://github.com/google/iree/blob/f2ce179dd0a539858f035bd31e4b5ac77108991a/iree/testing/CMakeLists.txt#L7

Right now, `iree/testing/benchmark.h` gets installed.

2022-02-01 17:22 UTC, ScottTodd approved these changes

2022-02-01 17:22 UTC, ScottTodd commented on CMakeLists.txt
>  # TODO(scotttodd): Iterate some more and find a better place for this.
Maybe remove this TODO, if there's more flatcc configuration going here. I don't really remember what I had in mind for the `iree-flatcc-cli` install / crosscompiling logic there...

2022-07-01 02:22 UTC, benvanik commented
Closing as obsolete. #7026 is still open but it's been awhile and this probably needs to be re-evaluated.

2022-07-01 02:22 UTC, closed without merging