Add support for collecting statistics in the benchmark pipeline
iree-org/iree pull request #8271
Opened 2022-02-08 20:48 UTC by antiagainst

2022-03-09 00:30 UTC, ScottTodd requested changes
Scanned through, haven't yet reviewed all files.

2022-03-09 00:30 UTC, ScottTodd commented on build_tools/cmake/iree_benchmark_suite.cmake
>                -o "${_VMFB_FILE}"
This always generates stats, even if collection (`COLLECT_COMPILATION_STATISTICS`) is not enabled?
Could add a comment if that's intentional (e.g. "stats generation is cheap, so always perform it, even if not collecting the stats")

2022-03-09 00:30 UTC, ScottTodd commented on build_tools/cmake/iree_benchmark_suite.cmake
> +#       statistics.
Can you elaborate on what collection actually does? (writes a JSON file to disk when the target is built? Updates a database entry when a binary is ran?)

2022-03-09 00:30 UTC, ScottTodd commented on build_tools/cmake/iree_benchmark_suite.cmake
>      "BENCHMARK_MODES;BENCHMARK_TOOL;MODULES;TRANSLATION_FLAGS;RUNTIME_FLAGS"
Could we decouple compilation and compilation statistics collection from execution time benchmarking? It looks like this PR offers no way to track offline statistics for a configuration without tightly coupling that same configuration to an execution time benchmark.

(I have a feeling the answer will be "maybe in the future", but these sorts of infrastructure configurations are harder to split apart once they settle)

2022-03-09 00:30 UTC, ScottTodd commented on build_tools/buildkite/cmake/android/arm64-v8a/benchmark2.yml
>    - label: "Build"
unrelated, but isn't it about time to rename this `benchmark.yml` instead of `benchmark2.yml`? :P

2022-03-09 00:30 UTC, ScottTodd commented on build_tools/benchmarks/upload_benchmarks_to_dashboard.py
> +    statistic_info = statistic_case.statistic_info
If `statistic_results.statistics` is a list / typical iterable data type, can't you simplify this?

```suggestion
  for statistic_case in statistic_results.statistics:
    statistic_info = statistic_case.statistic_info
```

same above with 

```python
for benchmark_index in range(len(benchmark_results.benchmarks)):
    benchmark_case = benchmark_results.benchmarks[benchmark_index]
```

if you need the index, the pythonic way to iterate is https://stackoverflow.com/a/522578

```python
for idx, val in enumerate(ints):
    print(idx, val)
```

2022-03-09 00:30 UTC, ScottTodd commented on benchmarks/TFLite/CMakeLists.txt
> +  COLLECT_COMPILATION_STATISTICS
This is going to be a lot of statistics. Is each statistic for each benchmark configuration a new series?

The PR comment shows "[Top 3 out of 332 statistic results showed]". Isn't that going to be really difficult to sift through on the dashboard?

Can we group the statistics or prune the set of configurations that track them?

(Writing to a database then querying that database will offer much more flexibility than continuing to push adhoc updates to https://github.com/google/dana IMO)

2022-07-01 02:23 UTC, benvanik commented
Closing as obsolete. I believe @pzread has been wiring this up.

2022-07-01 02:23 UTC, closed without merging