Fix setting IREE_MEMORY_ACCESS_ALIGNMENT_REQUIRED
iree-org/iree pull request #9697
Opened 2022-07-01 11:43 UTC by marbre

Even if `IREE_MEMORY_ACCESS_ALIGNMENT_REQUIRED` was defined it was
always set to 0. However, it is only valid to set it to 0 if
`IREE_MEMORY_ACCESS_ALIGNMENT_REQUIRED` isn't defined.

Makes progress on #9593 and allows to control the alignment behavior
via `IREE_MEMORY_ACCESS_ALIGNMENT_REQUIRED` instead of being
forced to pass `-mno-unaligned-access`.

2022-07-01 13:38 UTC, benvanik requested changes
Coffee hasn't kicked in yet but I'm not sure this is doing what we want: I think just always turns on the unaligned access emulation everywhere?

It should only be turned on if the user specifies it to be on (`-DIREE_MEMORY_ACCESS_ALIGNMENT_REQUIRED=1` passed to compiler) _or_ the architecture requires it (not passed but arch says it's needed), but nowhere else as it's slow and has a large code size.

It's confusing as it is today, though, and we should change its use in alignment.h to #ifdef and then remove ever setting it to 0. Then a user either defines it to say it's required _or_ the arch sets it if needed.

2022-07-01 15:08 UTC, marbre commented
With what we have now `IREE_MEMORY_ACCESS_ALIGNMENT_REQUIRED` is always set to **0** (for Arm) for the following configurations:

*  `add_compile_definitions(IREE_MEMORY_ACCESS_ALIGNMENT_REQUIRED)`
*  `add_compile_definitions(IREE_MEMORY_ACCESS_ALIGNMENT_REQUIRED=0)`
*  `add_compile_definitions(IREE_MEMORY_ACCESS_ALIGNMENT_REQUIRED=1)`
* no compile definition at all

The architecture is only evaluated if `IREE_MEMORY_ACCESS_ALIGNMENT_REQUIRED` isn't set (the last case). So in fact a user cannot control the behavior. With the proposed change `IREE_MEMORY_ACCESS_ALIGNMENT_REQUIRED` is set

* to **1** with `add_compile_definitions(IREE_MEMORY_ACCESS_ALIGNMENT_REQUIRED)
* to **0** if no compile definition is added

However, the code just checks if `IREE_MEMORY_ACCESS_ALIGNMENT_REQUIRED` is defined, not if already a numerical value was passed by the user. (I can further iterate on this to allow passing 0 or 1.)
But I agree, we need to fix `alignment.h` and this is only an intermediate step on the way to a more complete fix. (Already on it. This is just something I noticed on the way.)

2022-07-01 17:23 UTC, benvanik commented
The issue is this:
![image](https://user-images.githubusercontent.com/75337/176941305-84e9f6a5-6847-435e-9bba-4966cd7ee11e.png)
That's saying if `IREE_MEMORY_ACCESS_ALIGNMENT_REQUIRED` _is_ defined then set it to 1 (which seems like it'd be a re-definition?) - there should be no else at all. Either the user specifies `IREE_MEMORY_ACCESS_ALIGNMENT_REQUIRED` as 0 or 1 _or_ we pick for them. What's there with that else is treating it as a #ifdef style "if `IREE_MEMORY_ACCESS_ALIGNMENT_REQUIRED` is defined then alignment is required" but the 0 and 1 values are treating it as an #if style "if `IREE_MEMORY_ACCESS_ALIGNMENT_REQUIRED` is 1 then alignment is required" - it's gotta be one or the other.

If you remove this else block then it can stay as the latter (`-DIREE_MEMORY_ACCESS_ALIGNMENT_REQUIRED=0` or `-DIREE_MEMORY_ACCESS_ALIGNMENT_REQUIRED=1`).

2022-07-04 10:12 UTC, marbre commented
> If you remove this else block then it can stay as the latter (`-DIREE_MEMORY_ACCESS_ALIGNMENT_REQUIRED=0` or `-DIREE_MEMORY_ACCESS_ALIGNMENT_REQUIRED=1`).

Ah got your point! I agree and dropped the block with the latest push. I thought you were referring to adding `#define IREE_MEMORY_ACCESS_ALIGNMENT_REQUIRED 0` to the `// IREE_ARCH_*` block which is a actually a need.

Thanks for clarifying!

2022-07-05 16:15 UTC, benvanik approved these changes

2022-07-05 16:15 UTC, merged